/* 월별 상여: 돈·평가 값은 원장 전용 표에만 저장한다. */
'use strict';
if(typeof globalThis!=='undefined')globalThis.HUB_BONUS_CATALOG=true;
function bonusPreviousMonths(month,n){const [y,m]=month.split('-').map(Number);return Array.from({length:n},(_,i)=>{const d=new Date(Date.UTC(y,m-2-i,1));return d.toISOString().slice(0,7);});}
function bonusCopyBlank(month,current,previous){const occupied=new Set(current.filter(r=>r.confirmed||r.amount!=null||String(r.memo||'').trim()||Object.keys(r.selections||{}).length).map(r=>r.person_key));return previous.filter(r=>!occupied.has(r.person_key)).map(r=>{const {id,updated_at,updated_by,confirmed,confirmed_at,confirmed_by,...v}=r;return {...v,month,criteria_snapshot:[]};});}
function bonusCriteriaTotal(criteria,selections){const rate=Number(criteria.find(c=>c.kind==='point_rate'&&c.active!==false)?.value)||0;return criteria.filter(c=>c.active!==false&&c.kind!=='point_rate').reduce((sum,c)=>sum+(c.kind==='amount'?(selections[c.id]?Number(c.value)||0:0):Math.max(0,Math.min(Number(c.value)||0,Number(selections[c.id])||0))*rate),0);}
function payrollActiveProfiles(profiles){return (profiles||[]).filter(p=>p.active!==false&&p.approved!==false&&p.account_access_status!=='차단');}
function bonusRoster(profiles,extras,entries){const people=new Map(payrollActiveProfiles(profiles).filter(p=>p.role!=='owner').map(p=>[p.user_id,{person_key:p.user_id,user_id:p.user_id,source_name:p.name}]));(extras||[]).filter(p=>p.source_sheet==='급여대장').forEach(p=>{const key=p.user_id||'name:'+p.source_name;if(!people.has(key))people.set(key,{person_key:key,user_id:p.user_id||null,source_name:p.source_name});});(entries||[]).forEach(r=>{if(!people.has(r.person_key))people.set(r.person_key,{person_key:r.person_key,user_id:r.user_id,source_name:r.source_name});});return [...people.values()];}
function bonusCriteriaSnapshotFor(snapshot,current){const old=snapshot||[],ids=new Set(old.map(c=>c.id));return [...old,...current.filter(c=>c.active!==false&&!ids.has(c.id))];}
function bonusMoney(v){return v==null||v===''?'—':Number(v).toLocaleString('ko-KR');}
function bonusDifference(amount,ledger){return amount==null||ledger==null?null:Number(amount)-Number(ledger);}
function bonusT(k,d,v){return typeof hubT==='function'?hubT('pay.bonus.'+k,d,v):String(d).replace(/\{([a-z_]+)\}/g,(m,k)=>v?.[k]??m);}
function bonusOwner(){return typeof ME!=='undefined'&&ME.role==='owner';}
let BONUS={month:'',defaults:[],criteria:[],entries:[],previous:[],payroll:[],extras:[],people:[],drafts:new Map(),timers:new Map(),saving:new Set(),copying:false,confirming:false,suggestions:[],csvGeneration:0,importNotice:'',inflight:new Map(),generation:0};
function bonusBusy(){return BONUS.copying||BONUS.confirming;}
function bonusDirty(){return BONUS.drafts.size>0||BONUS.saving.size>0;}
function bonusCanLeave(){if(bonusBusy())return false;return !bonusDirty()||confirm(bonusT('unsaved','상여에 저장 안 된 변경이 있습니다. 화면을 바꿀까요? 변경은 다시 상여 화면에서 확인할 수 있습니다.'));}
function bonusNav(){return !bonusOwner()?'':`<button class="mini ${PAY_VIEW==='bonus'?'stamp':''}" onclick="setPayView('bonus')">${esc(bonusT('tab','상여'))}</button>`;}
function bonusEntry(p){return BONUS.drafts.get(p.person_key)?.row||BONUS.entries.find(r=>r.person_key===p.person_key)||{...p,month:BONUS.month,amount:null,memo:'',selections:{},criteria_snapshot:[]};}
function bonusSnapshot(){return BONUS.criteria.filter(c=>c.active!==false).map(c=>({id:c.id,name:c.name,kind:c.kind,value:c.value,sort_order:c.sort_order,active:c.active}));}
function bonusRowHtml(p,i){const row=bonusEntry(p),criteria=bonusCriteriaSnapshotFor(row.criteria_snapshot,bonusSnapshot()),ledger=BONUS.payroll.find(r=>r.user_id===p.user_id&&p.user_id)||BONUS.extras.find(r=>(r.user_id||'name:'+r.source_name)===p.person_key&&r.source_sheet==='급여대장'),diff=bonusDifference(row.amount,ledger?.items?.bonus),history=bonusPreviousMonths(BONUS.month,hubN('pay.bonus.months',3));
 return `<tr id="bonus-row-${i}"><td>${esc(p.source_name)}</td><td><input aria-label="${esc(bonusT('amount','세후 상여'))}" class="mini" type="number" min="0" step="1" value="${row.amount??''}" oninput="bonusEdit(${i},'amount',this.value)"></td><td><input aria-label="${esc(bonusT('memo','사유 메모'))}" class="mini" value="${esc(row.memo||'')}" oninput="bonusEdit(${i},'memo',this.value)"></td><td>${criteria.filter(c=>c.kind!=='point_rate').map(c=>`<label class="bonus-choice">${c.kind==='points'?`<input class="mini" type="number" min="0" max="${Number(c.value)}" value="${Number(row.selections?.[c.id])||0}" oninput="bonusEdit(${i},'criterion',this.value,'${c.id}')">`:`<input type="checkbox" ${row.selections?.[c.id]?'checked':''} onchange="bonusEdit(${i},'criterion',this.checked,'${c.id}')">`} ${esc(c.name)} (${Number(c.value).toLocaleString()})</label>`).join('')}</td><td><span id="bonus-total-${i}">${bonusCriteriaTotal(criteria,row.selections||{}).toLocaleString()}</span> <button class="mini" onclick="bonusApplyTotal(${i})">${esc(bonusT('apply_total','기준 합계 넣기'))}</button></td><td>${bonusMoney(ledger?.items?.bonus)}</td><td id="bonus-diff-${i}" class="${diff?'bonus-diff':''}">${bonusMoney(diff)}</td>${history.map(month=>`<td>${bonusMoney(BONUS.previous.find(r=>r.month===month&&r.person_key===p.person_key)?.amount)}</td>`).join('')}<td id="bonus-state-${i}" role="status">${bonusStatusHtml(row,i)}</td></tr>`;
}
function bonusPanelHtml(){if(!bonusOwner())return '';const history=bonusPreviousMonths(BONUS.month,hubN('pay.bonus.months',3)),heads=[bonusT('person','직원'),bonusT('amount','세후 상여'),bonusT('memo','사유 메모'),bonusT('criteria','기준 항목'),bonusT('total','기준 합계(참고)'),bonusT('ledger','노무사 대장 상여금(세후)'),bonusT('diff','차이'),...history,bonusT('state','저장 상태')],rate=BONUS.criteria.find(c=>c.kind==='point_rate');
 return `<section class="card bonus-panel"><h2>${esc(bonusT('tab','상여'))}</h2><div class="rowflex bonus-toolbar"><label>${esc(bonusT('month','대상 월'))} <input type="month" value="${BONUS.month}" onchange="bonusSetMonth(this.value,this)"></label><button class="mini" onclick="bonusCopyPrevious()">${esc(bonusT('copy','지난달 그대로 가져오기'))}</button><button class="mini" onclick="bonusConfirm()">${esc(bonusT('confirm_all','이 달 전부 확정'))}</button><button class="mini" onclick="bonusShowHistory()">${esc(bonusT('history','고친 기록 보기'))}</button></div><div class="tblwrap"><table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${BONUS.people.map(bonusRowHtml).join('')}</tbody><tfoot><tr><th>${esc(bonusT('sum','합계'))}</th><td id="bonus-month-total">${BONUS.people.reduce((s,p)=>s+(Number(bonusEntry(p).amount)||0),0).toLocaleString()}</td><td colspan="5"></td>${history.map(month=>`<td>${BONUS.previous.filter(r=>r.month===month).reduce((s,r)=>s+(Number(r.amount)||0),0).toLocaleString()}</td>`).join('')}<td></td></tr></tfoot></table></div><p id="bonus-confirm-summary" class="hint">${esc(bonusConfirmationSummary())}</p><div id="bonusMessage" class="hint" role="status">${esc(BONUS.importNotice)}</div><div id="bonusHistory"></div></section>
 <section class="card bonus-panel"><h3>${esc(bonusT('criteria','기준 항목'))}</h3><div class="rowflex bonus-toolbar"><label>${esc(bonusT('point_rate','1점당 금액'))} <input id="bonusPointRate" class="mini" type="number" min="0" value="${rate?.value??''}"></label><button class="mini" onclick="bonusSaveRate()">${esc(bonusT('save','저장'))}</button><button class="mini" onclick="bonusAddCriterion()">${esc(bonusT('add','항목 추가'))}</button></div><div class="tblwrap"><table><tr>${['name','kind','value','order','active','save'].map((k,j)=>`<th>${esc(bonusT(k,['항목 이름','종류','값','순서','사용','저장'][j]))}</th>`).join('')}</tr>${BONUS.criteria.filter(c=>c.kind!=='point_rate').map(c=>`<tr><td><input id="bc-name-${c.id}" value="${esc(c.name)}"></td><td><select id="bc-kind-${c.id}">${(typeof hubList==='function'?hubList('list.pay_bonus_kinds',[{code:'amount',label:'금액'},{code:'points',label:'배점'}]):[{code:'amount',label:'금액'},{code:'points',label:'배점'}]).map(x=>`<option value="${esc(x.code)}" ${x.code===c.kind?'selected':''}>${esc(x.label)}</option>`).join('')}</select></td><td><input id="bc-value-${c.id}" type="number" min="0" value="${c.value}"></td><td><input id="bc-order-${c.id}" type="number" value="${c.sort_order}" style="width:60px"></td><td><input id="bc-active-${c.id}" type="checkbox" ${c.active?'checked':''}></td><td><button class="mini" onclick="bonusSaveCriterion('${c.id}')">${esc(bonusT('save','저장'))}</button></td></tr>`).join('')}</table></div></section>${bonusDefaultsHtml()}${bonusImportHtml()}`;
}
async function renderBonus(m){if(!bonusOwner())return;const month=BONUS.month||bonusPreviousMonths(today().slice(0,7),1)[0];BONUS.month=month;const gen=++BONUS.generation;const hist=bonusPreviousMonths(month,hubN('pay.bonus.months',3));m.innerHTML=payTop()+`<div class="card">${esc(bonusT('loading','불러오는 중…'))}</div>`;
 try{const applied=await sb.rpc('bonus_apply_defaults',{p_month:month});if(applied.error)throw applied.error;if(m.isConnected===false||gen!==BONUS.generation||PAY_VIEW!=='bonus')return;const queries=[sb.from('bonus_criteria').select('*').order('sort_order'),sb.from('bonus_entries').select('*').eq('month',month),sb.from('bonus_entries').select('*').in('month',hist),sb.from('payroll_rows').select('user_id,items').eq('month',month),sb.from('payroll_extra_rows').select('*').eq('month',month).eq('archived',false),sb.from('bonus_defaults').select('*').order('source_name')];const results=await Promise.all(queries);if(results.some(r=>r.error))throw results.find(r=>r.error).error;if(m.isConnected===false||gen!==BONUS.generation||PAY_VIEW!=='bonus')return;[BONUS.criteria,BONUS.entries,BONUS.previous,BONUS.payroll,BONUS.extras,BONUS.defaults]=results.map(r=>r.data||[]);BONUS.people=bonusRoster(PROFILES,BONUS.extras,[...BONUS.entries,...BONUS.defaults]);m.innerHTML=payTop()+bonusPanelHtml();if(bonusBusy())bonusControlsLock(true);BONUS.people.forEach((p,i)=>{const d=BONUS.drafts.get(p.person_key);if(d)bonusState(i,'error',bonusT('pending','변경 저장 대기'));});}catch(e){if(m.isConnected!==false&&gen===BONUS.generation)m.innerHTML=payTop()+`<div class="card bonus-diff">${esc(bonusT('load_fail','불러오기 실패: {detail}',{detail:e.message}))}</div>`;}}
function bonusStatusHtml(row,i){const text=row.confirmed?bonusT('confirmed','확정 {time}',{time:new Date(row.confirmed_at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false})}):bonusT('unconfirmed','미확정');return esc(text)+` <button class="mini" onclick="bonusConfirm(${i})" ${row.confirmed?'disabled':''}>${esc(bonusT('confirm','저장(확정)'))}</button>`;}
function bonusConfirmationSummary(){const rows=BONUS.people.filter(p=>BONUS.drafts.has(p.person_key)||BONUS.entries.some(r=>r.person_key===p.person_key)).map(bonusEntry);return bonusT('confirmation_summary','확정 합계 {amount} · 미확정 {n}건',{amount:rows.filter(r=>r.confirmed).reduce((s,r)=>s+(Number(r.amount)||0),0).toLocaleString('ko-KR'),n:rows.filter(r=>!r.confirmed).length});}
function bonusState(i,kind,text){const el=$('#bonus-state-'+i),row=$('#bonus-row-'+i);if(row)row.classList.toggle('bonus-error',kind==='error');if(el)el.innerHTML=esc(text)+' · '+bonusStatusHtml(bonusEntry(BONUS.people[i]),i)+(kind==='error'?` <button class="mini" onclick="bonusSave(${i})">${esc(bonusT('retry','다시 저장'))}</button>`:'');}
function bonusEdit(i,field,value,key){if(!bonusOwner()||bonusBusy())return;const p=BONUS.people[i],prior=BONUS.drafts.get(p.person_key),row=JSON.parse(JSON.stringify(bonusEntry(p)));if(field==='amount')row.amount=value===''?null:Number(value);else if(field==='memo')row.memo=value;else{row.selections=row.selections||{};row.selections[key]=value;row.criteria_snapshot=bonusCriteriaSnapshotFor(row.criteria_snapshot,bonusSnapshot());}row.criteria_snapshot=bonusCriteriaSnapshotFor(row.criteria_snapshot,bonusSnapshot());row.confirmed=false;row.confirmed_at=null;row.confirmed_by=null;BONUS.drafts.set(p.person_key,{row,revision:(prior?.revision||0)+1});clearTimeout(BONUS.timers.get(p.person_key));BONUS.timers.set(p.person_key,setTimeout(()=>bonusSave(i),1000));bonusState(i,'pending',bonusT('pending','변경 저장 대기'));const total=$('#bonus-total-'+i);if(total)total.textContent=bonusCriteriaTotal(row.criteria_snapshot,row.selections||{}).toLocaleString();bonusRefreshTotals(i);}
async function bonusSaveNow(i){if(!bonusOwner()||BONUS.copying)return;const p=BONUS.people[i],d=BONUS.drafts.get(p?.person_key);if(!d||BONUS.saving.has(p.person_key))return;const row=d.row,revision=d.revision;if(row.amount!=null&&(!Number.isFinite(row.amount)||row.amount<0)){bonusState(i,'error',bonusT('invalid','0 이상의 금액을 입력하세요.'));return;}BONUS.saving.add(p.person_key);bonusState(i,'pending',bonusT('saving','저장 중…'));try{const {id,updated_at,updated_by,confirmed,confirmed_at,confirmed_by,...payload}=row;const {data,error}=await sb.from('bonus_entries').upsert(payload,{onConflict:'month,person_key'}).select('*');if(error)throw error;const savedRow=data[0];const index=BONUS.entries.findIndex(r=>r.person_key===row.person_key);if(index<0)BONUS.entries.push(savedRow);else BONUS.entries[index]=savedRow;if(BONUS.drafts.get(p.person_key)?.revision===revision){BONUS.drafts.delete(p.person_key);bonusState(i,'saved',bonusT('saved','저장됨 {time}',{time:new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}));}else BONUS.timers.set(p.person_key,setTimeout(()=>bonusSave(i),1000));bonusRefreshTotals(i);}catch(e){bonusState(i,'error',bonusT('save_fail','저장 실패: {detail}',{detail:e.message}));}finally{BONUS.saving.delete(p.person_key);}}
function bonusApplyTotal(i){if(bonusBusy())return;const row=bonusEntry(BONUS.people[i]);bonusEdit(i,'amount',bonusCriteriaTotal(bonusCriteriaSnapshotFor(row.criteria_snapshot,bonusSnapshot()),row.selections||{}));const input=$('#bonus-row-'+i+' input[type=number]');if(input)input.value=bonusEntry(BONUS.people[i]).amount;}
async function bonusSetMonth(month,input){if(bonusBusy()){if(input)input.value=BONUS.month;return;}if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||!bonusCanLeave()){if(input)input.value=BONUS.month;return;}if(bonusDirty()){await Promise.all(BONUS.people.map((p,i)=>bonusSave(i)));if(bonusDirty()){if(input)input.value=BONUS.month;return;}}BONUS.month=month;render();}
function bonusCopyLock(locked){BONUS.copying=locked;bonusControlsLock(locked);}
function bonusControlsLock(locked){if(typeof document!=='undefined')document.querySelectorAll('.bonus-panel input,.bonus-panel select,.bonus-panel button').forEach(el=>{if(locked){if(el.dataset.bonusCopyDisabled==null)el.dataset.bonusCopyDisabled=el.disabled?'1':'0';el.disabled=true;}else{el.disabled=el.dataset.bonusCopyDisabled==='1';delete el.dataset.bonusCopyDisabled;}});}
async function bonusCopyPrevious(){
 if(!bonusOwner()||bonusDirty()||bonusBusy())return;
 if(!confirm(bonusT('copy_confirm','이번 달 빈 칸만 지난달 값으로 채울까요?')))return;
 const month=BONUS.month,generation=BONUS.generation;bonusCopyLock(true);
 const message=$('#bonusMessage');if(message)message.textContent=bonusT('copying','지난달 빈 칸을 가져오는 중…');
 try{
  // 응답 뒤 월 확인을 유지하되, 실제 복사는 DB가 최신 행을 읽어 조건부 저장한다.
  const {error}=await sb.from('bonus_entries').select('person_key').eq('month',bonusPreviousMonths(month,1)[0]);if(error)throw error;
  if(BONUS.month!==month||BONUS.generation!==generation){if(message)message.textContent=bonusT('copy_month_changed','대상 월이 바뀌어 가져오기를 취소했습니다. 선택한 월에서 다시 가져오세요.');return;}
  const saved=await sb.rpc('bonus_copy_previous',{p_month:month});if(saved.error)throw saved.error;
 }catch(e){if(message)message.textContent=bonusT('save_fail','저장 실패: {detail}',{detail:e.message});return;}
 finally{bonusCopyLock(false);}
 render();
}
async function bonusCriterionWrite(payload){if(!bonusOwner()||bonusBusy())return;try{const {error}=await sb.from('bonus_criteria').upsert(payload);if(error)throw error;render();}catch(e){$('#bonusMessage').textContent=bonusT('save_fail','저장 실패: {detail}',{detail:e.message});}}
function bonusAddCriterion(){const name=prompt(bonusT('new_name','새 기준 항목 이름'));if(name?.trim())bonusCriterionWrite({name:name.trim(),kind:'amount',value:0,sort_order:BONUS.criteria.length,active:true});}
function bonusSaveCriterion(id){bonusCriterionWrite({id,name:$('#bc-name-'+id).value.trim(),kind:$('#bc-kind-'+id).value,value:Number($('#bc-value-'+id).value),sort_order:Number($('#bc-order-'+id).value),active:$('#bc-active-'+id).checked});}
function bonusSaveRate(){const r=BONUS.criteria.find(c=>c.kind==='point_rate');bonusCriterionWrite({...(r?{id:r.id}:{}),name:bonusT('point_rate','1점당 금액'),kind:'point_rate',value:Number($('#bonusPointRate').value),sort_order:-1,active:true});}
async function bonusShowHistory(){if(!bonusOwner())return;const {data,error}=await sb.from('bonus_history').select('*').or('month.eq.'+BONUS.month+',month.is.null').order('changed_at',{ascending:false}).limit(50);$('#bonusHistory').innerHTML=error?esc(error.message):`<div class="tblwrap"><table><tr>${['when','who','before','after'].map((k,i)=>`<th>${esc(bonusT(k,['언제','누가','전','후'][i]))}</th>`).join('')}</tr>${(data||[]).map(r=>`<tr><td>${esc(r.changed_at)}</td><td>${esc(nameOf(r.actor)||r.actor)}</td><td><pre>${esc(JSON.stringify(r.before_row,null,2))}</pre></td><td><pre>${esc(JSON.stringify(r.after_row,null,2))}</pre></td></tr>`).join('')}</table></div>`;}
if(typeof window!=='undefined')window.addEventListener('beforeunload',e=>{if(bonusDirty()){e.preventDefault();e.returnValue='';}});
if(typeof module!=='undefined')module.exports={bonusPreviousMonths,bonusCopyBlank,bonusCriteriaTotal,bonusCriteriaSnapshotFor,bonusRoster,bonusDifference,payrollActiveProfiles,bonusSuggestionsFromCsv};

function bonusRefreshTotals(i){const summary=$('#bonus-confirm-summary');if(summary)summary.textContent=bonusConfirmationSummary();const total=$('#bonus-month-total');if(total)total.textContent=BONUS.people.reduce((sum,p)=>sum+(Number(bonusEntry(p).amount)||0),0).toLocaleString();const p=BONUS.people[i],ledger=BONUS.payroll.find(r=>p.user_id&&r.user_id===p.user_id)||BONUS.extras.find(r=>(r.user_id||'name:'+r.source_name)===p.person_key&&r.source_sheet==='급여대장'),d=bonusDifference(bonusEntry(p).amount,ledger?.items?.bonus),el=$('#bonus-diff-'+i);if(el){el.textContent=bonusMoney(d);el.classList.toggle('bonus-diff',!!d);}}

// 확정 전에 진행 중 자동 저장을 기다리고 그 사이 생긴 변경도 저장한다.
function bonusSave(i){const key=BONUS.people[i]?.person_key;if(!key)return Promise.resolve();if(BONUS.inflight.has(key))return BONUS.inflight.get(key);const pending=bonusSaveNow(i);BONUS.inflight.set(key,pending);pending.finally(()=>{if(BONUS.inflight.get(key)===pending)BONUS.inflight.delete(key);});return pending;}
async function bonusFlush(){BONUS.timers.forEach(clearTimeout);BONUS.timers.clear();await Promise.all([...BONUS.inflight.values()]);await Promise.all(BONUS.people.map((p,i)=>bonusSave(i)));return !bonusDirty();}
async function bonusConfirm(i){
 if(!bonusOwner()||bonusBusy())return;
 const month=BONUS.month,keys=i==null?null:[BONUS.people[i]?.person_key];if(keys&&!keys[0])return;
 if(i==null&&!confirm(bonusT('confirm_all_prompt','저장 안 된 입력을 먼저 저장하고 이 달 상여를 전부 확정할까요?')))return;
 BONUS.confirming=true;bonusControlsLock(true);
 const message=$('#bonusMessage');
 try{
  if(!await bonusFlush()){if(message)message.textContent=bonusT('confirm_pending','저장하지 못한 입력이 있습니다. 다시 저장한 뒤 확정해 주세요.');return;}
  const result=await sb.rpc('bonus_confirm',{p_month:month,p_person_keys:keys});if(result.error)throw result.error;
 }catch(e){if(message)message.textContent=bonusT('save_fail','저장 실패: {detail}',{detail:e.message});return;}
 finally{BONUS.confirming=false;bonusControlsLock(false);}
 render();
}

function bonusDefaultsHtml(){return `<section class="card bonus-panel"><h3>${esc(bonusT('defaults','기본 제안값'))}</h3><p class="hint">${esc(bonusT('defaults_hint','빈 달에만 미확정 제안으로 채웁니다. 0은 상여 없음이며 사용을 끄면 새 달에 채우지 않습니다.'))}</p><div class="tblwrap"><table><tr>${['person','amount','memo','active','save'].map((k,j)=>`<th>${esc(bonusT(k,['직원','세후 상여','사유 메모','사용','저장'][j]))}</th>`).join('')}</tr>${BONUS.people.map((p,i)=>{const d=BONUS.defaults.find(r=>r.person_key===p.person_key)||{};return `<tr><td>${esc(p.source_name)}</td><td><input id="bd-amount-${i}" aria-label="${esc(bonusT('default_amount','기본 제안 금액'))}" class="mini" type="number" min="0" value="${d.amount??''}"></td><td><input id="bd-memo-${i}" aria-label="${esc(bonusT('memo','사유 메모'))}" value="${esc(d.memo||'')}"></td><td><input id="bd-active-${i}" aria-label="${esc(bonusT('active','사용'))}" type="checkbox" ${d.active!==false?'checked':''}></td><td><button class="mini" onclick="bonusSaveDefault(${i})">${esc(bonusT('save','저장'))}</button></td></tr>`;}).join('')}</table></div></section>`;}
async function bonusSaveDefault(i){
 if(!bonusOwner()||bonusBusy())return;const p=BONUS.people[i];if(!p)return;
 const value=$('#bd-amount-'+i).value,amount=value===''?null:Number(value),message=$('#bonusMessage');
 if(amount!=null&&(!Number.isFinite(amount)||amount<0)){if(message)message.textContent=bonusT('invalid','0 이상의 금액을 입력하세요.');return;}
 const payload={...p,amount,memo:$('#bd-memo-'+i).value,active:$('#bd-active-'+i).checked};BONUS.confirming=true;bonusControlsLock(true);
 try{if(!await bonusFlush()){if(message)message.textContent=bonusT('confirm_pending','저장하지 못한 입력이 있습니다. 다시 저장한 뒤 확정해 주세요.');return;}const {error}=await sb.from('bonus_defaults').upsert(payload,{onConflict:'person_key'});if(error)throw error;}
 catch(e){if(message)message.textContent=bonusT('save_fail','저장 실패: {detail}',{detail:e.message});return;}
 finally{BONUS.confirming=false;bonusControlsLock(false);}
 render();
}

function bonusCsvRows(text){
 const out=[],source=String(text).replace(/^\uFEFF/,'');let row=[],cell='',quoted=false,closed=false;
 const fail=()=>{throw Error(bonusT('csv_invalid','CSV 형식이 올바르지 않습니다. 머리줄과 따옴표를 확인하세요.'));};
 for(let i=0;i<source.length;i++){const c=source[i];
  if(quoted){if(c==='"'){if(source[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=c;continue;}
  if(c==='"'){if(cell||closed)fail();quoted=true;continue;}
  if(c===','||c==='\n'||c==='\r'){row.push(cell);cell='';closed=false;if(c!==','){out.push(row);row=[];if(c==='\r'&&source[i+1]==='\n')i++;}continue;}
  if(closed){if(!/\s/.test(c))fail();continue;}cell+=c;
 }
 if(quoted)fail();if(cell||row.length||closed){row.push(cell);out.push(row);}return out.filter(r=>r.some(v=>v.trim()));
}
function bonusSuggestionsFromCsv(text,profiles=[]){
 const rows=bonusCsvRows(text),header=rows.shift()||[],indexes=['직원','근무월','상여(입금-세후)','메모'].map(k=>header.findIndex(h=>h.trim()===k));
 if(indexes.some(i=>i<0))throw Error(bonusT('csv_headers','CSV 머리줄에 직원·근무월·상여(입금-세후)·메모가 필요합니다.'));
 const active=payrollActiveProfiles(profiles);
 return rows.map((row,i)=>{const name=(row[indexes[0]]||'').trim(),month=(row[indexes[1]]||'').trim(),value=(row[indexes[2]]||'').trim().replace(/[,\s₩원]/g,''),amount=value===''?null:Number(value),memo=row[indexes[3]]||'';
  if(!name||!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||(amount!=null&&(!Number.isFinite(amount)||amount<0)))throw Error(bonusT('csv_row_invalid','CSV {n}번째 데이터 줄의 직원·근무월·금액을 확인하세요.',{n:i+1}));
  const matches=active.filter(p=>p.name===name),user_id=matches.length===1?matches[0].user_id:null;return {month,person_key:user_id||'name:'+name,user_id,source_name:name,amount,memo};
 });
}
function bonusImportPreviewHtml(){const rows=BONUS.suggestions;if(!rows.length)return '';return `<div class="tblwrap"><table><tr>${['person','month','amount','memo','csv_link'].map((k,i)=>`<th>${esc(bonusT(k,['직원','대상 월','세후 상여','사유 메모','사람 연결'][i]))}</th>`).join('')}</tr>${rows.map(r=>`<tr><td>${esc(r.source_name)}</td><td>${esc(r.month)}</td><td>${bonusMoney(r.amount)}</td><td>${esc(r.memo)}</td><td>${esc(r.user_id?bonusT('csv_account','활성 계정'):bonusT('csv_name','이름으로 보관'))}</td></tr>`).join('')}</table></div><button class="mini" onclick="bonusImportSuggestions()">${esc(bonusT('import_apply','제안으로 넣기'))}</button>`;}
function bonusImportHtml(){return `<section class="card bonus-panel"><h3>${esc(bonusT('import','제안 불러오기'))}</h3><p class="hint">${esc(bonusT('import_hint','CSV는 이 화면에서만 읽으며 원본 파일은 서버에 올리지 않습니다. 이미 값이 있거나 확정한 줄은 건너뜁니다.'))}</p><input type="file" accept=".csv,text/csv" aria-label="${esc(bonusT('import','제안 불러오기'))}" onchange="bonusReadSuggestions(this.files[0])"><div id="bonusImportPreview">${bonusImportPreviewHtml()}</div></section>`;}
async function bonusReadSuggestions(file){
 if(!bonusOwner()||bonusBusy()||!file)return;const gen=++BONUS.csvGeneration;BONUS.suggestions=[];const preview=$('#bonusImportPreview');if(preview)preview.innerHTML='';
 try{const text=await file.text();if(gen!==BONUS.csvGeneration||!bonusOwner())return;BONUS.suggestions=bonusSuggestionsFromCsv(text,typeof PROFILES==='undefined'?[]:PROFILES);const target=$('#bonusImportPreview');if(target)target.innerHTML=bonusImportPreviewHtml();}
 catch(e){if(gen===BONUS.csvGeneration){const message=$('#bonusMessage');if(message)message.textContent=e.message;}}
}
async function bonusImportSuggestions(){
 if(!bonusOwner()||bonusBusy()||!BONUS.suggestions.length)return;
 if(!confirm(bonusT('import_confirm','미리보기의 빈 줄에만 미확정 제안을 넣을까요?')))return;
 const rows=BONUS.suggestions.map(r=>({...r})),gen=++BONUS.csvGeneration;BONUS.confirming=true;bonusControlsLock(true);const message=$('#bonusMessage');
 try{if(!await bonusFlush()){if(message)message.textContent=bonusT('confirm_pending','저장하지 못한 입력이 있습니다. 다시 저장한 뒤 확정해 주세요.');return;}const result=await sb.rpc('bonus_import_suggestions',{p_rows:rows});if(result.error)throw result.error;BONUS.importNotice=bonusT('import_result','제안 {inserted}건 넣음 · 기존 값·확정·중복 {skipped}건 건너뜀',{inserted:result.data.inserted,skipped:result.data.skipped});if(message)message.textContent=BONUS.importNotice;if(gen===BONUS.csvGeneration)BONUS.suggestions=[];}
 catch(e){if(message)message.textContent=bonusT('save_fail','저장 실패: {detail}',{detail:e.message});return;}
 finally{BONUS.confirming=false;bonusControlsLock(false);}
 render();
}
