/* 대조는 조회만 한다. 노무사 원본과 허브 값의 차이를 저장하지 않는다. */
'use strict';
function compareT(k,d,v){return hubT('pay.compare.'+k,d,v);}
function payrollCompareCell(ledger,hub,tolerance){const n=v=>v==null||v===''?null:Number(v),a=n(ledger),b=n(hub),missing=a==null||b==null||!Number.isFinite(a)||!Number.isFinite(b),diff=missing?null:b-a;return {ledger:missing&&a==null?null:a,hub:b,diff,different:!missing&&Math.abs(diff)>Number(tolerance??0)+1e-9,missing};}
function payrollComparisonModel(reply,ledgers=[],extras=[],settings={}){const out={noLedger:!ledgers.length&&!extras.length,rows:[]},time=settings.timeTolerance??0.1,money=settings.moneyTolerance??0;for(const p of reply.monthly){const l=ledgers.find(r=>r.user_id===p.userId)||extras.find(r=>r.user_id===p.userId&&r.source_sheet==='급여대장'),s=l?.side||{};out.rows.push({name:p.name,type:'monthly',cells:[['overtime',s['OT시간(시간)'],p.overtimeOnly,time],['attendance',s['근태횟수(시간)'],p.late+p.early,time],['holiday',s['휴일근로(시간)'],p.holiday,time],['holiday_overtime',s['휴일연장(분)']==null?null:Number(s['휴일연장(분)'])/60,p.holidayOvertime,time],['bonus',l?.items?.bonus,p.bonus,money]].map(([key,a,b,t])=>({key,...payrollCompareCell(a,key==='bonus'&&p.bonusUnconfirmed?null:b,t),unconfirmed:key==='bonus'&&!!p.bonusUnconfirmed}))});}
 for(const p of reply.hourly){const candidates=[...ledgers.filter(r=>r.user_id===p.userId),...extras.filter(r=>r.user_id===p.userId)],fields=[['weekday_work'],['weekday_over'],['weekend_work'],['weekend_over']];const labels=['평일근무','평일오버','주말근무','주말오버'],keys=['weekdayWork','weekdayOver','weekendWork','weekendOver'];out.rows.push({name:p.name,type:'hourly',cells:fields.map(([key],i)=>{const values=candidates.map(r=>r.side?.[labels[i]]).filter(v=>v!=null&&v!=='');return {key,...payrollCompareCell(values.length?values.reduce((s,v)=>s+Number(v),0):null,p[keys[i]],time)};})});}return out;
}
function payrollCompareNav(){if(!bonusOwner())return '';return `<button class="mini ${PAY_VIEW==='compare'?'stamp':''}" onclick="setPayView('compare')">${esc(compareT('tab','대조'))}</button>`;}
function payrollCompareDisplay(key,value){return value==null?'—':key==='bonus'?Number(value).toLocaleString('ko-KR'):value;}
function payrollComparisonHtml(model){if(!bonusOwner())return '';if(model.noLedger)return `<p class="hint">${esc(compareT('no_ledger','급여대장을 먼저 올려 주세요'))}</p>`;const labels={overtime:compareT('overtime','연장(포괄 초과분)'),attendance:compareT('attendance','지각+조퇴 시간'),holiday:compareT('holiday','휴일근로 시간'),holiday_overtime:compareT('holiday_overtime','공휴일 휴일연장 시간'),bonus:compareT('bonus','상여금(세후)'),weekday_work:compareT('weekday_work','평일근무'),weekday_over:compareT('weekday_over','평일오버'),weekend_work:compareT('weekend_work','주말근무'),weekend_over:compareT('weekend_over','주말오버')};return `<div class="tblwrap"><table><tr>${['person','item','ledger','hub','diff'].map((k,i)=>`<th>${esc(compareT(k,['직원','항목','노무사 대장','허브','차이'][i]))}</th>`).join('')}</tr>${model.rows.flatMap(p=>p.cells.map(c=>`<tr><td>${esc(p.name)}</td><td>${esc(labels[c.key])}</td><td>${esc(payrollCompareDisplay(c.key,c.ledger))}</td><td>${esc(c.unconfirmed?compareT('bonus_unconfirmed','미확정'):payrollCompareDisplay(c.key,c.hub))}</td><td class="${c.different?'bonus-diff':''}">${c.unconfirmed?esc(compareT('bonus_unconfirmed','미확정')):c.missing?esc(compareT('missing','근거 없음')):esc(payrollCompareDisplay(c.key,Number(c.diff.toFixed(4))))}</td></tr>`)).join('')}</table></div>`;}
let COMPARE={month:'',generation:0};
async function renderPayrollCompare(m){if(!bonusOwner())return;const month=COMPARE.month||bonusPreviousMonths(today().slice(0,7),1)[0];COMPARE.month=month;const gen=++COMPARE.generation;m.innerHTML=payTop()+`<section class="card bonus-panel"><h2>${esc(compareT('tab','대조'))}</h2><label>${esc(compareT('month','대상 월'))} <input type="month" value="${month}" onchange="COMPARE.month=this.value;render()"></label><div id="compareContent">${esc(compareT('loading','불러오는 중…'))}</div></section>`;try{const [reply,ledger,extra]=await Promise.all([payrollFetchReply(month),sb.from('payroll_rows').select('user_id,items,side').eq('month',month),sb.from('payroll_extra_rows').select('*').eq('month',month).eq('archived',false)]);if(ledger.error||extra.error)throw ledger.error||extra.error;if(m.isConnected===false||gen!==COMPARE.generation||PAY_VIEW!=='compare')return;$('#compareContent').innerHTML=payrollComparisonHtml(payrollComparisonModel(reply,ledger.data||[],extra.data||[],{timeTolerance:hubN('pay.compare.time_tolerance',0.1),moneyTolerance:hubN('pay.compare.money_tolerance',0)}));}catch(e){if(m.isConnected!==false&&gen===COMPARE.generation&&$('#compareContent'))$('#compareContent').textContent=compareT('failed','불러오기 실패: {detail}',{detail:e.message});}}
if(typeof module!=='undefined')module.exports={payrollCompareCell,payrollComparisonModel};
