/* 노무사 회신: 저장된 월근태와 기존 시급제 RPC의 분을 시간으로 출력한다. */
'use strict';
function replyT(k,d,v){return hubT('pay.reply.'+k,d,v);}
function payrollReplyHours(minutes,digits=2){return Number((Number(minutes||0)/60).toFixed(digits));}
function payrollReplyTime(s){return typeof timeToMin==='function'?timeToMin(s):/^\d{2}:\d{2}/.test(s||'')?Number(s.slice(0,2))*60+Number(s.slice(3,5)):null;}
function payrollReplyOverlap(a,b,c,d){return typeof overlapMinutes==='function'?overlapMinutes(a,b,c,d):Math.max(0,Math.min(b,d)-Math.max(a,c));}
function payrollReplyNight(cin,cout,start,end){let a=payrollReplyTime(cin),b=payrollReplyTime(cout);if(a==null||b==null)return null;if(b<a)b+=1440;let total=0;for(let day=-1;day<=1;day++){const ns=day*1440+start,ne=day*1440+end+(end<=start?1440:0);total+=payrollReplyOverlap(a,b,ns,ne);}return total;}
function payrollReplyWage(wages,uid,date){return wages.filter(w=>w.user_id===uid&&w.effective_from<=date).sort((a,b)=>b.effective_from.localeCompare(a.effective_from))[0]||{};}
function payrollReplyCategoryColumn(c){if(c?.reply_column==='weekday'||c?.reply_column==='weekend')return c.reply_column;const days=c?.days||[];return c?.code==='weekend'||(days.length&&days.every(d=>Number(d)===0||Number(d)===6))||c?.dates?.length?'weekend':'weekday';}
function payrollReplyCategoryFor(date,categories=[]){const day=new Date(date+'T00:00:00Z').getUTCDay();return categories.find(c=>c.dates?.includes(date))||categories.find(c=>c.days?.some(d=>Number(d)===day))||{code:day===0||day===6?'weekend':'weekday',days:[day],dates:[]};}
function payrollReplyHourlySegments(days,wages,uid,month,categories=[]){
 const source=[];
 for(const d of days){const a=payrollReplyTime(d.clockIn),b=payrollReplyTime(d.clockOut);if(a==null||b==null||a===b)continue;
  const midnight=Date.parse(d.date+'T00:00:00Z');let cursor=midnight+a*60000;const end=midnight+(b<a?b+1440:b)*60000;
  while(cursor<end){const date=new Date(cursor).toISOString().slice(0,10),next=Date.parse(date+'T00:00:00Z')+86400000,segmentEnd=Math.min(end,next);
   if(date.slice(0,7)===month&&payrollReplyWage(wages,uid,date).hourly_enabled)source.push({date,work_date:d.date,minutes:(segmentEnd-cursor)/60000,category:payrollReplyCategoryFor(date,categories).code});
   cursor=segmentEnd;
  }
 }
 return source;
}
function payrollReplyModel(model,wages=[],bonuses=[],holidays=[],settings={},hourlyData=null){const digits=settings.digits??2,h=m=>payrollReplyHours(m,digits),publicDays=new Set(holidays),out={month:model.month,monthly:[],hourly:[],basis:[],notes:[],settings};
 const msg=(k,d,v)=>typeof settings.text==='function'?settings.text(k,d,v):String(d).replace(/\{([a-z_]+)\}/g,(m,k)=>v?.[k]??m);
 for(const p of model.employees){
  const days=p.days||[],complete=d=>payrollReplyTime(d.clockIn)!=null&&payrollReplyTime(d.clockOut)!=null&&d.clockIn!==d.clockOut;
  const carryDays=p.carryDays||[],replyDays=p.replyDays||days,replyCarryDays=p.replyCarryDays||carryDays;if(!days.length&&!carryDays.length)continue;
  const wageFor=d=>payrollReplyWage(wages,p.userId,d.date),monthlyDays=days.filter(d=>d.date.slice(0,7)===model.month&&complete(d)&&!wageFor(d).hourly_enabled),hourlyDays=replyDays.filter(d=>d.date.slice(0,7)===model.month&&complete(d)&&wageFor(d).hourly_enabled);
  const entry=bonuses.find(b=>b.user_id===p.userId&&b.month===model.month),base={userId:p.userId,name:p.name,dept:p.dept||'',absence:'',bonus:entry?(entry.confirmed===true?entry.amount??'':msg('bonus_unconfirmed','미확정')):'',bonusUnconfirmed:!!entry&&entry.confirmed!==true,otherBonus:'',bonusBasis:settings.bonusBasis||'세후'};
  const basisDays=days.map(d=>payrollReplyWage(wages,p.userId,d.date).hourly_enabled?replyDays.find(r=>r.date===d.date)||d:d);
  for(const d of basisDays.concat(replyCarryDays.filter(d=>payrollReplyHourlySegments([d],wages,p.userId,model.month,settings.categories).length))){const w=wageFor(d),inclusive=w.hourly_enabled?'':w.inclusive_overtime_hours;let a=payrollReplyTime(d.clockIn),b=payrollReplyTime(d.clockOut);if(a!=null&&b!=null&&b<a)b+=1440;const hm=complete(d)&&(publicDays.has(d.date)||Number(d.holidayMinutes)>0)?b-a:0;
   out.basis.push([p.name,p.dept||'',d.date,d.clockIn,d.clockOut,d.lateMinutes??0,d.earlyMinutes??0,d.overtimeMinutes??0,hm,d.basis||'',[(d.needsClockReview||!complete(d))?msg('clock_review','출퇴근 시각 확인 필요'):'',base.bonusUnconfirmed?msg('bonus_review','상여 미확정'):''].filter(Boolean).join(' · '),inclusive??msg('inclusive_missing','포괄 시간 미입력')]);
  }
  if(base.bonusUnconfirmed)out.notes.push([p.name,msg('bonus_review','상여 미확정')]);
  if(monthlyDays.length){
   const wage=wageFor([...monthlyDays].sort((a,b)=>b.date.localeCompare(a.date))[0]),inclusive=wage.inclusive_overtime_hours,missing=inclusive==null||inclusive==='';
   const sum=k=>monthlyDays.reduce((n,d)=>n+(Number(d[k])||0),0),total=k=>monthlyDays.length===days.length?(Number(p.summary?.[k])||sum(k)):sum(k);
   let night=0,holiday=0,holidayOver=0;
   for(const d of monthlyDays){let a=payrollReplyTime(d.clockIn),b=payrollReplyTime(d.clockOut);if(b<a)b+=1440;night+=payrollReplyNight(d.clockIn,d.clockOut,settings.nightStart??1320,settings.nightEnd??360)||0;if(publicDays.has(d.date)||Number(d.holidayMinutes)>0)holiday+=b-a;if(publicDays.has(d.date))holidayOver+=Math.max(0,b-a-(settings.holidayHours??8)*60);}
   const ot=Math.max(0,total('overtimeMinutes')-(missing?0:Number(inclusive)*60));
   out.monthly.push({...base,early:h(total('earlyMinutes')),late:h(total('lateMinutes')),overtime:h(ot+holiday),overtimeOnly:h(ot),holiday:h(holiday),holidayOvertime:h(holidayOver),night:h(night),inclusive:inclusive??'',inclusiveMissing:missing});
   if(missing)out.notes.push([p.name,msg('inclusive_missing','포괄 시간 미입력')]);
  }
  const daily=hourlyData?.users?.find(u=>u.user_id===p.userId)?.days;
  const source=daily?.filter(d=>d.date.slice(0,7)===model.month&&payrollReplyWage(wages,p.userId,d.date).hourly_enabled)||payrollReplyHourlySegments([...replyCarryDays,...replyDays],wages,p.userId,model.month,settings.categories);
  if(hourlyDays.length||source.some(d=>d.minutes!=null&&Number(d.minutes)>0)){const totals={weekdayWork:0,weekdayOver:0,weekendWork:0,weekendOver:0},grouped=new Map();let needsReview=false;
   for(const d of source){if(d.minutes==null){needsReview=true;continue;}const category=settings.categories?.find(c=>c.code===d.category)||{...payrollReplyCategoryFor(d.date,settings.categories),code:d.category},kind=payrollReplyCategoryColumn(category),k=d.date+'|'+kind;grouped.set(k,(grouped.get(k)||0)+Number(d.minutes));}
   for(const [key,min] of grouped){const category=key.split('|')[1],kind=category==='weekend'?'weekend':'weekday';totals[kind+'Work']+=Math.min(min,(settings.hourlyDayHours??8)*60);totals[kind+'Over']+=Math.max(0,min-(settings.hourlyDayHours??8)*60);}
   Object.keys(totals).forEach(k=>totals[k]=needsReview?null:h(totals[k]));out.hourly.push({...base,...totals,needsReview});
   if(!daily)out.notes.push([p.name,msg('hourly_fallback','시급제 RPC 대상에 없는 과거 인원: 월근태 출퇴근 시각으로 시간 계산')]);
  }
  if(days.some(d=>!complete(d)))out.notes.push([p.name,msg('night_missing','야간시간: 출퇴근 시각 근거 부족')]);
 }
 out.notes.push([msg('rule_calc_label','계산'),msg('absence_hint','허브는 미기록을 결근으로 판정하지 않음')],[msg('rule_time_label','시간'),msg('rule_time','분 ÷ 60; 소수 {digits}자리',{digits})],[msg('rule_overtime_label','연장'),msg('rule_overtime','max(0, 허브 연장 분 − 포괄 포함 시간×60) + 휴일근로 분')],[msg('rule_holiday_label','휴일'),msg('rule_holiday','출퇴근 시각 구간; 휴게시간 미차감')],[msg('rule_public_label','공휴일 연장'),msg('rule_public','공휴일 하루 {hours}시간 초과분',{hours:settings.holidayHours??8})],[msg('rule_night_label','야간'),msg('rule_night','{start}분부터 다음 {end}분까지',{start:settings.nightStart??1320,end:settings.nightEnd??360})],[msg('rule_inclusive_label','포괄'),msg('rule_inclusive','직원별 wage_info 적용일 기준; 비어 있으면 전체 연장')]);return out;
}
function payrollReplyWorkbook(model,label=(k,d)=>d){const m=model.monthly,h=model.hourly;return {filename:'급여회신_'+model.month+'.xlsx',sheets:[{name:label('monthly_sheet','월급제'),rows:[[label('name','이름'),label('dept','담당/직위'),...['absence','early','late','overtime','holiday_overtime','night','bonus','other_bonus','bonus_basis'].map((k,i)=>label(k,['결근일수','근태공제시간','지각시간','연장/휴일근로시간','공휴일 휴일연장시간','야간시간','인센티브','기타 인센티브','인센티브 기준'][i])),label('check','확인필요')],...m.map(r=>[r.name,r.dept,r.absence,r.early,r.late,r.overtime,r.holidayOvertime,r.night??'',r.bonus,r.otherBonus,r.bonusBasis,[r.inclusiveMissing?label('inclusive_missing','포괄 시간 미입력'):'',r.bonusUnconfirmed?label('bonus_review','상여 미확정'):''].filter(Boolean).join(' · ')])]},{name:label('hourly_sheet','시급제'),rows:[[label('name','이름'),...['weekday_work','weekday_over','weekend_work','weekend_over'].map((k,i)=>label(k,['평일근무','평일오버','주말근무','주말오버'][i]))],...h.map(r=>[r.name,r.weekdayWork??'',r.weekdayOver??'',r.weekendWork??'',r.weekendOver??''])]},{name:label('basis_sheet','근거'),rows:[[label('name','이름'),label('dept','담당/직위'),label('date','날짜'),label('clock_in','출근'),label('clock_out','퇴근'),label('late_min','지각(분)'),label('early_min','조퇴(분)'),label('overtime_min','연장(분)'),label('holiday_min','휴일(분)'),label('source','원 자료'),label('check','확인필요'),label('inclusive','포괄 포함 연장시간(월)')],...model.basis,[],...model.notes]}]};}
let REPLY={month:'',model:null,generation:0};
function payrollReplyNav(){if(!bonusOwner())return '';return `<button class="mini ${PAY_VIEW==='reply'?'stamp':''}" onclick="setPayView('reply')">${esc(replyT('tab','노무사 회신'))}</button>`;}
function payrollReplySettings(){return {digits:hubN('pay.reply.digits',2),nightStart:hubN('pay.reply.night_start',1320),nightEnd:hubN('pay.reply.night_end',360),holidayHours:hubN('pay.reply.holiday_hours',8),hourlyDayHours:hubN('pay.reply.hourly_day_hours',8),bonusBasis:hubT('pay.reply.bonus_basis_value','세후'),text:replyT};}
async function payrollFetchReply(month){if(!bonusOwner())throw Error(replyT('owner','원장만 사용할 수 있습니다.'));const {start,next}=attendanceMonthBounds(month);const results=await Promise.all([fetchAttMonthlyData(month,{includeCarry:true,forReply:true}),sb.from('wage_info').select('*').lt('effective_from',next),sb.from('bonus_entries').select('*').eq('month',month),sb.from('holidays').select('date,name').gte('date',start).lt('date',next),sb.rpc('wage_hourly_month',{p_month:month,p_user_id:null}),sb.rpc('wage_hourly_config')]);for(const r of results.slice(1,4))if(r.error)throw r.error;if(results[4].error&&!/disabled|does not exist|schema cache/i.test(results[4].error.message||''))throw results[4].error;if(results[5].error&&!/disabled|does not exist|schema cache/i.test(results[5].error.message||''))throw results[5].error;const settings=payrollReplySettings();settings.categories=results[5].data?.settings?.categories||[];return payrollReplyModel(results[0],results[1].data||[],results[2].data||[],(results[3].data||[]).map(r=>r.date),settings,results[4].data);}
function payrollReplyTable(model){if(!bonusOwner())return '';const book=payrollReplyWorkbook(model,replyT);return book.sheets.slice(0,2).map((s,i)=>`<h3>${esc(s.name)}</h3><div class="tblwrap"><table><tr>${s.rows[0].map(v=>`<th>${esc(v)}</th>`).join('')}</tr>${s.rows.slice(1).map((r,j)=>`<tr>${r.map((v,col)=>`<td class="${i===0&&col===11&&model.monthly[j].inclusiveMissing?'payroll-warning':''}">${esc(v)}</td>`).join('')}</tr>`).join('')}</table></div>`).join('')+`<div class="hint">${esc(replyT('absence_hint','허브는 미기록을 결근으로 판정하지 않음'))}</div>`;}
function payrollReplyDeadline(month){const [y,m]=month.split('-').map(Number),d=new Date(Date.UTC(y,m,1));return replyT('deadline','{month}월분 회신 기한: {next}월 {reply_day}일 · 급여일 {next}월 {pay_day}일',{month:m,next:d.getUTCMonth()+1,reply_day:hubN('pay.reply.deadline',3),pay_day:hubN('pay.reply.payday',10)});}
async function renderPayrollReply(m){if(!bonusOwner())return;REPLY.month=REPLY.month||bonusPreviousMonths(today().slice(0,7),1)[0];const month=REPLY.month,gen=++REPLY.generation;REPLY.model=null;m.innerHTML=payTop()+`<section class="card bonus-panel"><h2>${esc(replyT('tab','노무사 회신'))}</h2><div class="rowflex bonus-toolbar"><label>${esc(replyT('month','대상 월'))} <input type="month" value="${month}" onchange="REPLY.month=this.value;render()"></label><button class="mini" id="replyExport" onclick="payrollReplyExport()" disabled>${esc(replyT('export','엑셀 받기'))}</button></div><p class="hint">${esc(payrollReplyDeadline(month))}</p><div id="replyContent">${esc(replyT('loading','불러오는 중…'))}</div></section>`;try{const model=await payrollFetchReply(month);if(m.isConnected===false||gen!==REPLY.generation||PAY_VIEW!=='reply')return;REPLY.model=model;$('#replyContent').innerHTML=payrollReplyTable(model);$('#replyExport').disabled=false;}catch(e){if(m.isConnected!==false&&gen===REPLY.generation&&$('#replyContent'))$('#replyContent').textContent=replyT('failed','불러오기 실패: {detail}',{detail:e.message});}}
function payrollReplyExport(){if(!bonusOwner()||!REPLY.model)return;const model=payrollReplyWorkbook(REPLY.model,replyT),book=XLSX.utils.book_new();for(const s of model.sheets){const ws=XLSX.utils.aoa_to_sheet(s.rows);XLSX.utils.book_append_sheet(book,ws,s.name);}XLSX.writeFile(book,model.filename);}
if(typeof module!=='undefined')module.exports={payrollReplyHourlySegments,payrollReplyCategoryColumn,payrollReplyCategoryFor,payrollReplyHours,payrollReplyNight,payrollReplyModel,payrollReplyWorkbook};
