const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),html=read('hr.html');
const esc=s=>String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function helpers(){const block=html.match(/\/\* ai-usage:test-start \*\/[\s\S]*?\/\* ai-usage:test-end \*\//)?.[0];assert.ok(block,'AI 사용량 순수 helper가 없습니다.');const c={esc};vm.createContext(c);vm.runInContext(block+';this.h={aiUsageSummary,aiUsagePanelHtml,aiCostSectionHtml,aiExternalSectionHtml,aiSessionSectionHtml};',c);return c.h;}
const won=v=>Math.round(v).toLocaleString('ko-KR');
const COST={fx:1375.642214,fx_src:'open.er-api.com',generated:'2026-09-22 17:35',total_usd:16074.96,this_month:'2026-09',this_usd:6289.71,
  agents:{kimi:{cumUSD:250.26,months:[{m:'2026-07',usd:134.77},{m:'2026-08',usd:99.08},{m:'2026-09',usd:16.41}],inTok:374575114,outTok:2283194,ok:true},
    claude:{cumUSD:12626.65,months:[{m:'2026-07',usd:3992.29},{m:'2026-08',usd:4631.24},{m:'2026-09',usd:4003.12}],inTok:12777754284,outTok:63426244,ok:true},
    codex:{cumUSD:3197.81,months:[{m:'2026-07',usd:648.5},{m:'2026-08',usd:279.12},{m:'2026-09',usd:2270.19}],inTok:6262044960,outTok:22934163,ok:true},
    openclaw:{cumUSD:0.25,months:[{m:'2026-07',usd:0.25}],inTok:311977908,outTok:2317997,ok:true}},
  month_usd:{'2026-02':1,'2026-03':2,'2026-04':3,'2026-05':4,'2026-06':5,'2026-07':4775.81,'2026-08':5009.44,'2026-09':6289.71}};
const SESS={generated:'2026-09-22 17:33',won_today_total:193974,tok_today_total:775000000,flagged:[
  {name:'T8 인프라 <작업>',thread:'019a1b2c',sev:'red',active:true,tok_today:21475513,won_today:5368,share:2.8,reasons:['대기만 반복(최근60분 wait 23·편집0)','기록 72MB(매 턴 다시 읽음)']},
  {name:'',thread:'019a9999',sev:'orange',active:false,tok_today:40000000,won_today:10000,share:5,reasons:['오늘 4천만 토큰']}]};

test('정가 환산 구역은 청구액이 아님을 밝히고 이번 달·누적·플랫폼·월별 합계를 환율로 환산한다',()=>{const h=helpers(),out=h.aiCostSectionHtml({cost:COST,error:''});assert.match(out,/정가 환산/);assert.match(out,/청구액 아님/);assert.ok(out.includes('₩'+won(6289.71*1375.642214)),'이번 달 합계 환산이 없습니다.');assert.ok(out.includes('₩'+won(16074.96*1375.642214)),'누적 환산이 없습니다.');const iC=out.indexOf('data-ai-cost-platform="claude"'),iX=out.indexOf('data-ai-cost-platform="codex"'),iK=out.indexOf('data-ai-cost-platform="kimi"'),iO=out.indexOf('data-ai-cost-platform="openclaw"');assert.ok(iC>0&&iC<iX&&iX<iK&&iK<iO,'플랫폼이 누적 큰 순서가 아닙니다.');assert.match(out,/Claude Code/);assert.match(out,/Codex \(OpenAI\)/);assert.match(out,/Kimi \(Moonshot\)/);const kimiRow=out.slice(iK,iO);assert.ok(kimiRow.includes('₩'+won(16.41*1375.642214)),'이번 달 값은 this_month 항목이어야 합니다.');const clawRow=out.slice(iO,out.indexOf('</tr>',iO));assert.ok(clawRow.includes('₩0'),'이번 달 항목이 없는 플랫폼은 0이어야 합니다.');assert.equal(out.match(/data-ai-cost-month="/g)?.length,6,'월별 합계는 최근 6개월만 그립니다.');assert.doesNotMatch(out,/data-ai-cost-month="2026-02"/);assert.match(out,/data-ai-cost-month="2026-09"/);assert.match(out,/2026-09-22 17:35/);assert.match(out,/US\$1 = ₩1,376/);});

test('정가 환산 구역은 기록 없음·조회 실패를 알리고 외부 문자열을 이스케이프한다',()=>{const h=helpers();assert.match(h.aiCostSectionHtml({cost:null,error:''}),/아직 올라온 비용 기록이 없습니다/);const failed=h.aiCostSectionHtml({cost:null,error:'bad <x>'});assert.match(failed,/비용 기록을 불러오지 못했습니다/);assert.match(failed,/bad &lt;x&gt;/);const evil=h.aiCostSectionHtml({cost:{...COST,fx_src:'<script>x</script>',generated:'<b>t</b>',agents:{'<i>':{cumUSD:1,months:[],inTok:0,outTok:0,ok:true}}},error:''});assert.doesNotMatch(evil,/<script>x<\/script>|<b>t<\/b>|<i>/);assert.match(evil,/&lt;script&gt;/);});

test('대화 효율 구역은 빨강·주황 표시, 활성 여부, 추정 비용, 사유를 보여 주고 이름을 이스케이프한다',()=>{const h=helpers(),out=h.aiSessionSectionHtml({sessions:SESS,error:''});assert.match(out,/Codex 대화 효율 점검/);assert.match(out,/오늘 전체 약 ₩193,974/);assert.match(out,/2026-09-22 17:33/);assert.match(out,/🔴/);assert.match(out,/🟠/);assert.match(out,/T8 인프라 &lt;작업&gt;/);assert.doesNotMatch(out,/<작업>/);assert.match(out,/019a9999/,'이름이 비면 thread로 대신 표시해야 합니다.');assert.match(out,/활성/);assert.match(out,/멈춤/);assert.match(out,/약 ₩5,368/);assert.match(out,/대기만 반복\(최근60분 wait 23·편집0\) · 기록 72MB/);const many={...SESS,flagged:Array.from({length:10},(_,i)=>({name:'대화'+i,thread:'t'+i,sev:'orange',active:false,won_today:i,tok_today:i,share:0,reasons:[]}))};assert.equal(h.aiSessionSectionHtml({sessions:many,error:''}).match(/data-ai-session="/g)?.length,8,'최대 8개만 보여야 합니다.');});

test('대화 효율 구역은 돈이 새는 대화 없음·기록 없음·조회 실패를 구분한다',()=>{const h=helpers();assert.match(h.aiSessionSectionHtml({sessions:{...SESS,flagged:[]},error:''}),/지금 돈이 새는 대화 없음/);assert.match(h.aiSessionSectionHtml({sessions:null,error:''}),/아직 올라온 점검 기록이 없습니다/);assert.match(h.aiSessionSectionHtml({sessions:null,error:'x<y'}),/점검 기록을 불러오지 못했습니다: x&lt;y/);});

test('현황판 카드는 모델별 사용량·정가 환산·대화 점검 순서로 한 카드에 묶는다',()=>{const h=helpers(),s=h.aiUsageSummary([{usage_date:'2026-09-20',model:'Astra',tokens:3,turns:1}],'2026-09-16','2026-09-22'),out=h.aiUsagePanelHtml({summary:s,start:'2026-09-16',end:'2026-09-22',error:'',cost:COST,costError:'',sessions:SESS,sessionsError:''});assert.equal(out.match(/id="aiUsagePanel"/g)?.length,1);const iModel=out.indexOf('모델별 사용량(최근 7일)'),iCost=out.indexOf('data-ai-cost-section'),iSess=out.indexOf('data-ai-session-section');assert.ok(iModel>0&&iModel<iCost&&iCost<iSess,'구역 순서가 다릅니다.');assert.match(out,/data-ai-usage-astra="true"/);});

test('AI비용 탭은 스냅샷을 원장 확인 뒤 읽기 전용으로 조회하고 실패를 해당 구역에만 표시한다',()=>{const body=html.match(/async function renderAicost\(m\)\{[\s\S]*?\r?\n\}\r?\n/)?.[0];assert.ok(body);const guard=body.indexOf("if(ME.role!=='owner')"),q=body.indexOf("sb.from('ai_usage_snapshots').select('kind,payload,synced_at').in('kind',['platform_cost','codex_sessions','external_ai'])");assert.ok(guard>0&&q>guard,'원장 확인 뒤 스냅샷 조회가 없습니다.');assert.match(body,/if\(error\|\|historyError\|\|eventsError\)\{/);assert.match(body,/costError:snapshotError\?snapshotError\.message:''/);assert.match(body,/sessionsError:snapshotError\?snapshotError\.message:''/);assert.doesNotMatch(html,/from\('ai_usage_snapshots'\)\.(insert|upsert|update|delete)\(/);});

test('스냅샷 SQL은 원장 읽기 전용 RLS·크기 제한·service-role 전용 저장 함수만 두고 Task 6 객체를 건드리지 않는다',()=>{const sql=read('db/ai_usage_snapshots.sql'),rollback=read('db/ai_usage_snapshots_rollback.sql');assert.match(sql,/create table if not exists public\.ai_usage_snapshots/i);assert.match(sql,/kind text primary key check\(kind in\('platform_cost','codex_sessions'\)\)/i);assert.match(sql,/octet_length\(payload::text\)<=131072/i);assert.match(sql,/alter table public\.ai_usage_snapshots enable row level security/i);assert.match(sql,/revoke all on table public\.ai_usage_snapshots from public,anon,authenticated/i);assert.match(sql,/create policy ai_usage_snapshots_owner_select on public\.ai_usage_snapshots for select to authenticated using\(\(select public\.my_role\(\)\)='owner'\)/i);assert.doesNotMatch(sql,/for (insert|update|delete|all)\b/i);assert.match(sql,/function public\.ai_usage_snapshot_put\(p_kind text,p_payload jsonb\)[\s\S]*security invoker set search_path=''/i);assert.match(sql,/revoke all on function public\.ai_usage_snapshot_put\(text,jsonb\) from public,anon,authenticated/i);assert.match(sql,/grant execute on function public\.ai_usage_snapshot_put\(text,jsonb\) to service_role/i);for(const s of [sql,rollback])assert.doesNotMatch(s,/notice|storage\.|deposits|bucket/i);assert.match(rollback,/drop function if exists public\.ai_usage_snapshot_put\(text,jsonb\)/i);assert.match(rollback,/drop table if exists public\.ai_usage_snapshots/i);});

test('Edge Function은 kind로 사용량·스냅샷을 나누고, 모르는 kind는 거절하며, 본문은 64KB를 넘는 순간 읽기를 멈춘다',()=>{const edge=read('supabase/functions/ai-usage-sync/index.ts');assert.match(edge,/new URL\(req\.url\)\.searchParams\.get\('kind'\)\|\|'model_usage'/);assert.match(edge,/SNAPSHOT_KINDS\.has\(kind\)/);assert.match(edge,/\.rpc\('ai_usage_snapshot_put',\{p_kind:kind,p_payload:snap\.value\}\)/);assert.match(edge,/\.rpc\('ai_model_usage_replace',\{p_usage:parsed\.value\.usage\}\)/);assert.match(edge,/response\(400,\{error:'unknown_kind'\}\)/);assert.match(edge,/readLimited\(req,MAX_BODY_BYTES\)/);assert.match(edge,/reader\.cancel\(\)/);assert.doesNotMatch(edge,/req\.text\(\)/);assert.ok(edge.indexOf("sameHex(await sha256Hex(token)")<edge.indexOf("readLimited(req,MAX_BODY_BYTES)"),'토큰 확인 전에 본문을 읽습니다.');});

test('비용 스냅샷은 알려진 필드만 남기고, 잘못된 항목만 버리며, DB가 못 받는 숫자·문자는 정리한다',async()=>{const {validatePlatformCost,MAX_BODY_BYTES}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const C=String.fromCharCode;const ok=validatePlatformCost({...COST,extra:'drop-me'});assert.equal(ok.ok,true);assert.equal('extra' in ok.value,false);assert.deepEqual(Object.keys(ok.value.agents).sort(),['claude','codex','kimi','openclaw']);assert.equal(ok.value.agents.claude.months.length,3);assert.equal(ok.value.fx,1375.642214);assert.equal(validatePlatformCost({...COST,this_month:null}).ok,true);
  const month=j=>`${2021+Math.floor(j/12)}-${String(j%12+1).padStart(2,'0')}`,tiny={...COST,fx_src:'a'+C(0)+'b'+C(0xd800)+'c',generated:'2026-09-22 17:35'+'x'.repeat(40),agents:Object.fromEntries(Array.from({length:10},(_,i)=>['a'+i,{cumUSD:5e-324,months:Array.from({length:60},(_,j)=>({m:month(j),usd:5e-324})),inTok:1,outTok:1,ok:true}]))};
  const t=validatePlatformCost(tiny);assert.equal(t.ok,true);assert.equal(t.value.agents.a0.months[0].usd,0);assert.equal(t.value.agents.a0.cumUSD,0);assert.equal(t.value.fx_src.includes(C(0)),false);assert.equal(t.value.fx_src.isWellFormed(),true);assert.ok(t.value.generated.length<=32);assert.ok(Buffer.byteLength(JSON.stringify(t.value))<=MAX_BODY_BYTES);assert.doesNotMatch(JSON.stringify(t.value),/e-/,'지수 표기 숫자가 남아 있습니다.');
  const tol=validatePlatformCost({...COST,agents:{...COST.agents,'Bad Key!':COST.agents.claude,daily:{cumUSD:1,months:[{m:'2026-09-22',usd:1},{m:'Sept',usd:1}],inTok:1,outTok:1,ok:true}},this_month:'2026-09-22',month_usd:{'2026-09-22':1,bad:2}});assert.equal(tol.ok,true);assert.equal('Bad Key!' in tol.value.agents,false);assert.deepEqual(JSON.parse(JSON.stringify(tol.value.agents.daily.months)),[{m:'2026-09-22',usd:1}]);assert.equal(tol.value.this_month,'2026-09-22');assert.deepEqual(Object.keys(tol.value.month_usd),['2026-09-22']);
  const proto=validatePlatformCost(JSON.parse('{"fx":1,"generated":"g","agents":{"__proto__":{"cumUSD":1,"months":[],"inTok":0,"outTok":0}}}'));assert.equal(proto.ok,true);assert.ok(JSON.stringify(proto.value).includes('"__proto__"'),'__proto__ 플랫폼이 사라졌습니다.');
  for(const b of [null,[],{...COST,agents:undefined},{...COST,fx:0},{...COST,fx:'1375'},{...COST,generated:undefined},{...COST,agents:{'Bad Key!':COST.agents.claude}}])assert.equal(validatePlatformCost(b).ok,false,JSON.stringify(b)?.slice(0,90));});

test('대화 점검 스냅샷은 모르는 필드·PC 경로·세션 ID를 버리고, 표시 필드는 자르고 정리해 받아들인다',async()=>{const {validateSessionHealth,MAX_FLAGGED,MAX_BODY_BYTES}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const C=String.fromCharCode;const raw={...SESS,scanned:40,new_top_field:{x:1},flagged:[{...SESS.flagged[0],file:'C:\\Users\\x\\.codex\\sessions\\rollout.jsonl',tid:'uuid',mtime:'17:30',size_mb:72.1,new_field:'x'},SESS.flagged[1]]};const ok=validateSessionHealth(raw);assert.equal(ok.ok,true);assert.deepEqual(Object.keys(ok.value.flagged[0]).sort(),['active','name','reasons','sev','share','thread','tok_today','won_today']);assert.equal(JSON.stringify(ok.value).includes('rollout'),false);assert.equal(JSON.stringify(ok.value).includes('new_top_field'),false);
  const many=validateSessionHealth({...SESS,won_today_total:'1',flagged:Array.from({length:MAX_FLAGGED+5},()=>SESS.flagged[1])});assert.equal(many.ok,true);assert.equal(many.value.flagged.length,MAX_FLAGGED);assert.equal(many.value.won_today_total,0);
  const odd=validateSessionHealth({...SESS,flagged:[{...SESS.flagged[0],sev:'purple',active:'yes',name:'ab'+C(0)+C(0xdc00)+'x'.repeat(300),reasons:['r'.repeat(500),1,...Array(10).fill('y')],won_today:-1,share:'5'}]});assert.equal(odd.ok,true);const f=odd.value.flagged[0];assert.ok(f.name.length<=120);assert.equal(f.name.includes(C(0)),false);assert.equal(f.name.isWellFormed(),true);assert.ok(f.reasons.length<=6);assert.ok(f.reasons.every(r=>typeof r==='string'&&r.length<=200));assert.equal(f.won_today,0);assert.equal(f.share,0);assert.equal(f.active,false);assert.ok(typeof f.sev==='string'&&f.sev.length<=16);
  const huge=validateSessionHealth({...SESS,flagged:Array.from({length:MAX_FLAGGED},()=>({...SESS.flagged[0],name:'가'.repeat(120),reasons:Array(6).fill('나'.repeat(200))}))});assert.equal(huge.ok,false,'정리 후에도 64KB를 넘으면 거절해야 합니다.');assert.equal(huge.error,'too_large');assert.ok(MAX_BODY_BYTES===65536);
  for(const b of [null,[],{...SESS,flagged:{}},{...SESS,generated:undefined}])assert.equal(validateSessionHealth(b).ok,false,JSON.stringify(b)?.slice(0,90));});

test('스냅샷 글자 칸에 객체 같은 잘못된 값이 와도 예외 없이 그 값만 비우고 뒤의 정상 항목은 그대로 받는다(Astra 2차 I1)',async()=>{const {validateSessionHealth,validatePlatformCost}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const s=validateSessionHealth(JSON.parse('{"generated":"g","won_today_total":1,"flagged":[{"name":{"toString":null},"thread":{"toString":null},"sev":{"a":1},"reasons":[{"toString":null},"ok"]},{"name":"정상 항목","thread":"t2","sev":"red","active":true,"won_today":1,"reasons":[]}]}'));assert.equal(s.ok,true);assert.equal(s.value.flagged.length,2);assert.equal(s.value.flagged[0].name,'');assert.equal(s.value.flagged[0].thread,'');assert.equal(s.value.flagged[0].sev,'');assert.deepEqual([...s.value.flagged[0].reasons],['ok']);assert.equal(s.value.flagged[1].name,'정상 항목');assert.equal(s.value.flagged[1].sev,'red');const c=validatePlatformCost(JSON.parse('{"fx":1,"fx_src":{"toString":null},"generated":"g","agents":{"claude":{"cumUSD":1,"months":[],"inTok":0,"outTok":0}}}'));assert.equal(c.ok,true);assert.equal(c.value.fx_src,'');assert.equal(validateSessionHealth(JSON.parse('{"generated":{"toString":null},"flagged":[]}')).ok,false,'최상위 generated가 문자열이 아니면 거절');});

test('모델명이 constructor·toString·__proto__여도 집계·검사·플랫폼 이름에서 빠지거나 바뀌지 않는다',async()=>{const h=helpers(),s=h.aiUsageSummary([{usage_date:'2026-09-20',model:'constructor',tokens:7,turns:1},{usage_date:'2026-09-20',model:'Sol',tokens:3,turns:1},{usage_date:'2026-09-20',model:'toString',tokens:5,turns:1},{usage_date:'2026-09-20',model:'__proto__',tokens:5,turns:1}],'2026-09-16','2026-09-22');assert.equal(s.total,20);assert.deepEqual([...s.models].map(m=>m.model).sort(),['Sol','__proto__','constructor','toString']);assert.equal(Math.round([...s.models].reduce((a,m)=>a+m.share,0)),100);
  const cost=h.aiCostSectionHtml({cost:{fx:1,generated:'g',agents:JSON.parse('{"constructor":{"cumUSD":1,"months":[],"inTok":0,"outTok":0},"__proto__":{"cumUSD":2,"months":[],"inTok":0,"outTok":0}}'),month_usd:{}},error:''});assert.doesNotMatch(cost,/function|native code/);assert.match(cost,/data-ai-cost-platform="constructor"/);assert.match(cost,/data-ai-cost-platform="__proto__"/);
  const {validateUsagePayload}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const u=validateUsagePayload(JSON.parse('{"2026-09-21":{"__proto__":{"tokens":1,"turns":1},"Sol":{"tokens":2,"turns":1}}}'),'2026-09-22');assert.equal(u.ok,true);assert.equal(u.value.rows,2);assert.ok(JSON.stringify(u.value.usage).includes('"__proto__"'),'__proto__ 모델 행이 사라졌습니다.');});
const EXT={generated:'2026-09-30 13:20',fx:1500,days:{
  '2026-09-29':{deepseek:{calls:9,ok:4,fail:5,sec:957.5,tin:0,tout:0,krw:0,costed_calls:0},step5:{calls:10,ok:10,fail:0,sec:0,tin:0,tout:0,krw:0,costed_calls:0}},
  '2026-09-30':{deepseek:{calls:4,ok:4,fail:0,sec:435.5,tin:8241,tout:88,krw:4,costed_calls:1},'?':{calls:1,ok:0,fail:1,sec:903.5,tin:0,tout:0,krw:0,costed_calls:0}}},
  totals:{deepseek:{calls:40,ok:28,fail:12,tin:8241,tout:88,krw:4,costed_calls:1},step5:{calls:29,ok:29,fail:0,tin:0,tout:0,krw:0,costed_calls:0},'?':{calls:2,ok:0,fail:2,tin:0,tout:0,krw:0,costed_calls:0}}};

test('외부 AI 구역은 AI별 카드(건수·성공/실패·금액)와 날짜별 표를 그리고 09-30 이전과 금액 없는 칸은 금액 기록 전으로 표시한다',()=>{const h=helpers(),out=h.aiExternalSectionHtml({external:EXT,error:''});assert.match(out,/외부 AI\(딥시크·스텝5 등\)/);const iD=out.indexOf('data-ai-external-ai="deepseek"'),iS=out.indexOf('data-ai-external-ai="step5"'),iQ=out.indexOf('data-ai-external-ai="?"');assert.ok(iD>0&&iD<iS&&iS<iQ,'카드가 건수 내림차순이 아닙니다.');const dCard=out.slice(iD,iS);assert.match(dCard,/딥시크/);assert.match(dCard,/40건/);assert.match(dCard,/성공 28 · 실패 12/);assert.match(dCard,/₩4/);assert.match(dCard,/1\/40건 기록/);assert.match(out.slice(iS,iQ),/스텝5[\s\S]*29건[\s\S]*금액 기록 전/);assert.match(out.slice(iQ),/이름 모름/);
  const rows=[...out.matchAll(/<tr data-ai-external-day="([^"]+)" data-ai-external-row="([^"]+)">([\s\S]*?)<\/tr>/g)];assert.deepEqual(rows.map(r=>r[1]+'/'+r[2]),['2026-09-30/deepseek','2026-09-30/?','2026-09-29/step5','2026-09-29/deepseek'],'날짜 내림차순·건수 내림차순이 아닙니다.');const cell=(i)=>rows[i][3];assert.match(cell(0),/₩4/);assert.doesNotMatch(cell(0),/금액 기록 전/);assert.match(cell(1),/금액 미집계\(0\/1건\)/);assert.match(cell(2),/금액 기록 전/);assert.match(cell(3),/금액 기록 전/);assert.match(out,/US\$1 = ₩1,500/);assert.match(out,/2026-09-30 13:20/);});

test('외부 AI 구역은 기록 없음·조회 실패를 알리고 외부 문자열을 이스케이프하며 15일째부터는 표에서 뺀다',()=>{const h=helpers();assert.match(h.aiExternalSectionHtml({external:null,error:''}),/아직 올라온 외부 AI 기록이 없습니다/);const failed=h.aiExternalSectionHtml({external:null,error:'bad <x>'});assert.match(failed,/외부 AI 기록을 불러오지 못했습니다: bad &lt;x&gt;/);const evil=h.aiExternalSectionHtml({external:{generated:'<b>g</b>',fx:1500,days:{'2026-09-30':{'<i>':{calls:1,ok:1,fail:0,krw:0,costed_calls:0}}},totals:{'<i>':{calls:1,ok:1,fail:0,krw:0,costed_calls:0},constructor:{calls:1,ok:1,fail:0,krw:0,costed_calls:0}}},error:''});assert.doesNotMatch(evil,/<i>|<b>g<\/b>/);assert.match(evil,/&lt;i&gt;/);assert.doesNotMatch(evil,/function|native code/);
  const days={};for(let i=0;i<20;i++)days['2026-09-'+String(i+1).padStart(2,'0')]={deepseek:{calls:1,ok:1,fail:0,krw:0,costed_calls:0}};const many=h.aiExternalSectionHtml({external:{generated:'g',fx:1500,days,totals:{}},error:''});assert.equal(many.match(/data-ai-external-day="/g)?.length,14);assert.match(many,/data-ai-external-day="2026-09-20"/);assert.doesNotMatch(many,/data-ai-external-day="2026-09-06"/);});

test('현황판 카드는 외부 AI 구역을 정가 환산과 대화 점검 사이에 한 번만 넣는다',()=>{const h=helpers(),s=h.aiUsageSummary([{usage_date:'2026-09-20',model:'Astra',tokens:3,turns:1}],'2026-09-16','2026-09-22'),out=h.aiUsagePanelHtml({summary:s,start:'2026-09-16',end:'2026-09-22',error:'',cost:COST,costError:'',external:EXT,externalError:'',sessions:SESS,sessionsError:''});assert.equal(out.match(/data-ai-external-section/g)?.length,1);const iCost=out.indexOf('data-ai-cost-section'),iExt=out.indexOf('data-ai-external-section'),iSess=out.indexOf('data-ai-session-section');assert.ok(iCost>0&&iCost<iExt&&iExt<iSess,'구역 순서가 다릅니다.');});

test('외부 AI 스냅샷은 알려진 필드만 남기고, 최신 60일·ai 8개로 자르고, 잘못된 항목만 버리며, DB가 못 받는 값은 정리한다',async()=>{const {validateExternalAi,MAX_EXT_DAYS,MAX_EXT_AIS,MAX_BODY_BYTES}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const C=String.fromCharCode;
  const ok=validateExternalAi({...EXT,extra:'drop-me',days:{...EXT.days,'2026-09-28':{deepseek:{...EXT.days['2026-09-29'].deepseek,file:'C:\\x',new_field:1}}}});assert.equal(ok.ok,true);assert.equal('extra' in ok.value,false);assert.deepEqual(Object.keys(ok.value).sort(),['days','fx','generated','totals']);assert.deepEqual(Object.keys(ok.value.days['2026-09-28'].deepseek).sort(),['calls','costed_calls','fail','krw','ok','sec','tin','tout']);assert.deepEqual(Object.keys(ok.value.totals.deepseek).sort(),['calls','costed_calls','fail','krw','ok','tin','tout'],'totals에는 sec이 없어야 합니다.');assert.equal(JSON.stringify(ok.value).includes('C:'),false);assert.equal(ok.value.fx,1500);assert.equal(ok.value.days['2026-09-30'].deepseek.krw,4);
  const many={};for(let i=0;i<MAX_EXT_DAYS+10;i++)many[new Date(Date.UTC(2026,7,1+i)).toISOString().slice(0,10)]={deepseek:EXT.days['2026-09-30'].deepseek};const cut=validateExternalAi({...EXT,days:many});assert.equal(cut.ok,true);const dk=Object.keys(cut.value.days);assert.equal(dk.length,MAX_EXT_DAYS);assert.equal(dk.includes('2026-08-01'),false,'오래된 날짜부터 잘려야 합니다.');assert.equal(dk.includes(new Date(Date.UTC(2026,7,MAX_EXT_DAYS+10)).toISOString().slice(0,10)),true);
  const ais=Object.fromEntries(Array.from({length:MAX_EXT_AIS+4},(_,i)=>['ai'+i,EXT.totals.deepseek]));const capped=validateExternalAi({...EXT,days:{'2026-09-30':ais},totals:ais});assert.equal(Object.keys(capped.value.days['2026-09-30']).length,MAX_EXT_AIS);assert.equal(Object.keys(capped.value.totals).length,MAX_EXT_AIS);
  const tol=validateExternalAi({...EXT,days:{'2026-09-30':{'Bad Key!':EXT.totals.deepseek,'':EXT.totals.deepseek,x:'no',step5:{calls:-1,ok:1.5,fail:'3',sec:1e12,tin:1e16,tout:5e-324,krw:'9',costed_calls:1e10}},'bad-date':{deepseek:EXT.totals.deepseek},'2026-02-30':{deepseek:EXT.totals.deepseek}},totals:{'Bad Key!':EXT.totals.deepseek,deepseek:EXT.totals.deepseek}});assert.equal(tol.ok,true);assert.deepEqual(Object.keys(tol.value.days),['2026-09-30']);assert.deepEqual(Object.keys(tol.value.days['2026-09-30']),['step5']);assert.deepEqual({...tol.value.days['2026-09-30'].step5},{calls:0,ok:0,fail:0,tin:0,tout:0,krw:0,costed_calls:0,sec:0});assert.deepEqual(Object.keys(tol.value.totals),['deepseek']);assert.doesNotMatch(JSON.stringify(tol.value),/e-/,'지수 표기 숫자가 남아 있습니다.');
  const odd=validateExternalAi({...EXT,generated:'2026-09-30'+C(0)+C(0xd800)+'x'.repeat(60)});assert.equal(odd.ok,true);assert.ok(odd.value.generated.length<=32);assert.equal(odd.value.generated.includes(C(0)),false);assert.equal(odd.value.generated.isWellFormed(),true);
  const proto=validateExternalAi(JSON.parse('{"fx":1500,"generated":"g","days":{"2026-09-30":{"__proto__":{"calls":1,"ok":1,"fail":0,"sec":0,"tin":0,"tout":0,"krw":0,"costed_calls":0}}},"totals":{"__proto__":{"calls":1,"ok":1,"fail":0,"tin":0,"tout":0,"krw":0,"costed_calls":0}}}'));assert.equal(proto.ok,true);assert.ok(JSON.stringify(proto.value).includes('"__proto__"'),'__proto__ 이름의 AI가 사라졌습니다.');
  const big=validateExternalAi({...EXT,days:Object.fromEntries(Array.from({length:MAX_EXT_DAYS},(_,i)=>[new Date(Date.UTC(2026,6,1+i)).toISOString().slice(0,10),Object.fromEntries(Array.from({length:MAX_EXT_AIS},(_,j)=>['a'.repeat(31)+j,{calls:999999999,ok:999999999,fail:999999999,sec:999999999.999999,tin:999999999999999,tout:999999999999999,krw:999999999999.999999,costed_calls:999999999}]))]))});assert.equal(big.ok,false,'정리 후에도 64KB를 넘으면 거절해야 합니다.');assert.equal(big.error,'too_large');assert.equal(MAX_BODY_BYTES,65536);
  for(const b of [null,[],{...EXT,days:undefined},{...EXT,days:[]},{...EXT,fx:0},{...EXT,fx:'1500'},{...EXT,generated:undefined},{fx:1500,generated:'g',days:{},totals:{}},{fx:1500,generated:'g',days:{'2026-09-30':{}},totals:{'Bad Key!':EXT.totals.deepseek}}])assert.equal(validateExternalAi(b).ok,false,JSON.stringify(b)?.slice(0,90));});

test('외부 AI SQL은 kind 허용 목록에 external_ai만 더하고 되돌림은 그 한 줄만 지우며 다른 객체를 건드리지 않는다',()=>{const sql=read('db/ai_usage_snapshots_external_ai.sql'),rollback=read('db/ai_usage_snapshots_external_ai_rollback.sql');assert.match(sql,/drop constraint if exists ai_usage_snapshots_kind_check/i);assert.match(sql,/add constraint ai_usage_snapshots_kind_check check\(kind in\('platform_cost','codex_sessions','external_ai'\)\)/i);assert.match(rollback,/delete from public\.ai_usage_snapshots where kind='external_ai'/i);assert.match(rollback,/add constraint ai_usage_snapshots_kind_check check\(kind in\('platform_cost','codex_sessions'\)\)/i);for(const s of [sql,rollback]){assert.doesNotMatch(s,/drop table|create policy|drop policy|grant |revoke |notice|storage\.|deposits|bucket/i);assert.match(s,/public\.ai_usage_snapshots/);}assert.equal(read('db/ai_usage_snapshots.sql').includes('external_ai'),false,'기존 마이그레이션은 고치지 않습니다.');});

test('Edge Function은 external_ai kind를 스냅샷으로 받고 화면은 external_ai 스냅샷을 원장 확인 뒤 읽기만 한다',()=>{const edge=read('supabase/functions/ai-usage-sync/index.ts');assert.match(edge,/\['external_ai',validateExternalAi\]/);assert.match(edge,/validateExternalAi,validatePlatformCost/);const body=html.match(/async function renderAicost\(m\)\{[\s\S]*?\r?\n\}\r?\n/)?.[0];assert.match(body,/\.in\('kind',\['platform_cost','codex_sessions','external_ai'\]\)/);assert.match(body,/external:snap\.external_ai\|\|null,externalError:snapshotError\?snapshotError\.message:''/);assert.ok(body.indexOf("if(ME.role!=='owner')")<body.indexOf("'external_ai'"),'원장 확인 전에 조회합니다.');});
