const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),html=read('hr.html');
const esc=s=>String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function helpers(){const block=html.match(/\/\* ai-usage:test-start \*\/[\s\S]*?\/\* ai-usage:test-end \*\//)?.[0];assert.ok(block,'AI 사용량 순수 helper가 없습니다.');const c={esc};vm.createContext(c);vm.runInContext(block+';this.h={aiUsageSummary,aiUsagePanelHtml,aiCostSectionHtml,aiSessionSectionHtml};',c);return c.h;}
const won=v=>Math.round(v).toLocaleString('ko-KR');
const COST={fx:1375.642214,fx_src:'open.er-api.com',generated:'2026-09-22 17:35',total_usd:16074.96,this_month:'2026-09',this_usd:6289.71,
  agents:{kimi:{cumUSD:250.26,months:[{m:'2026-07',usd:134.77},{m:'2026-08',usd:99.08},{m:'2026-09',usd:16.41}],inTok:374575114,outTok:2283194,ok:true},
    claude:{cumUSD:12626.65,months:[{m:'2026-07',usd:3992.29},{m:'2026-08',usd:4631.24},{m:'2026-09',usd:4003.12}],inTok:12777754284,outTok:63426244,ok:true},
    codex:{cumUSD:3197.81,months:[{m:'2026-07',usd:648.5},{m:'2026-08',usd:279.12},{m:'2026-09',usd:2270.19}],inTok:6262044960,outTok:22934163,ok:true},
    openclaw:{cumUSD:0.25,months:[{m:'2026-07',usd:0.25}],inTok:311977908,outTok:2317997,ok:true}},
  month_usd:{'2026-02':1,'2026-03':2,'2026-04':3,'2026-05':4,'2026-06':5,'2026-07':4775.81,'2026-08':5009.44,'2026-09':6289.71}};
const SESS={generated:'2026-09-22 17:33',won_today_total:193974,tok_today_total:775000000,flagged:[
  {name:'T8 인프라 <작업>',thread:'019a1b2c',sev:'red',active:true,tok_today:21475513,won_today:5368,share:2.8,reasons:['대기만 반복(최근60분 wait 23·편집0)','기록 72MB(매 턴 다시 읽음)']},
  {name:'',thread:'019a9999',sev:'orange',active:false,tok_today:40000000,won_today:10000,share:5,reasons:['오늘 4천만 토큰']}]};

test('정가 환산 구역은 청구액이 아님을 밝히고 이번 달·누적·플랫폼·월별 합계를 환율로 환산한다',()=>{const h=helpers(),out=h.aiCostSectionHtml({cost:COST,error:''});assert.match(out,/정가 환산/);assert.match(out,/청구액 아님/);assert.ok(out.includes('₩'+won(6289.71*1375.642214)),'이번 달 합계 환산이 없습니다.');assert.ok(out.includes('₩'+won(16074.96*1375.642214)),'누적 환산이 없습니다.');const iC=out.indexOf('data-ai-cost-platform="claude"'),iX=out.indexOf('data-ai-cost-platform="codex"'),iK=out.indexOf('data-ai-cost-platform="kimi"'),iO=out.indexOf('data-ai-cost-platform="openclaw"');assert.ok(iC>0&&iC<iX&&iX<iK&&iK<iO,'플랫폼이 누적 큰 순서가 아닙니다.');assert.match(out,/Claude Code/);assert.match(out,/Codex \(OpenAI\)/);assert.match(out,/Kimi \(Moonshot\)/);const kimiRow=out.slice(iK,iO);assert.ok(kimiRow.includes('₩'+won(16.41*1375.642214)),'이번 달 값은 this_month 항목이어야 합니다.');const clawRow=out.slice(iO,out.indexOf('</tr>',iO));assert.ok(clawRow.includes('₩0'),'이번 달 항목이 없는 플랫폼은 0이어야 합니다.');assert.equal(out.match(/data-ai-cost-month="/g)?.length,6,'월별 합계는 최근 6개월만 그립니다.');assert.doesNotMatch(out,/data-ai-cost-month="2026-02"/);assert.match(out,/data-ai-cost-month="2026-09"/);assert.match(out,/2026-09-22 17:35/);assert.match(out,/US\$1 = ₩1,376/);});

test('정가 환산 구역은 기록 없음·조회 실패를 알리고 외부 문자열을 이스케이프한다',()=>{const h=helpers();assert.match(h.aiCostSectionHtml({cost:null,error:''}),/아직 올라온 비용 기록이 없습니다/);const failed=h.aiCostSectionHtml({cost:null,error:'bad <x>'});assert.match(failed,/비용 기록을 불러오지 못했습니다/);assert.match(failed,/bad &lt;x&gt;/);const evil=h.aiCostSectionHtml({cost:{...COST,fx_src:'<script>x</script>',generated:'<b>t</b>',agents:{'<i>':{cumUSD:1,months:[],inTok:0,outTok:0,ok:true}}},error:''});assert.doesNotMatch(evil,/<script>x<\/script>|<b>t<\/b>|<i>/);assert.match(evil,/&lt;script&gt;/);});

test('대화 효율 구역은 빨강·주황 표시, 활성 여부, 추정 비용, 사유를 보여 주고 이름을 이스케이프한다',()=>{const h=helpers(),out=h.aiSessionSectionHtml({sessions:SESS,error:''});assert.match(out,/Codex 대화 효율 점검/);assert.match(out,/오늘 전체 약 ₩193,974/);assert.match(out,/2026-09-22 17:33/);assert.match(out,/🔴/);assert.match(out,/🟠/);assert.match(out,/T8 인프라 &lt;작업&gt;/);assert.doesNotMatch(out,/<작업>/);assert.match(out,/019a9999/,'이름이 비면 thread로 대신 표시해야 합니다.');assert.match(out,/활성/);assert.match(out,/멈춤/);assert.match(out,/약 ₩5,368/);assert.match(out,/대기만 반복\(최근60분 wait 23·편집0\) · 기록 72MB/);const many={...SESS,flagged:Array.from({length:10},(_,i)=>({name:'대화'+i,thread:'t'+i,sev:'orange',active:false,won_today:i,tok_today:i,share:0,reasons:[]}))};assert.equal(h.aiSessionSectionHtml({sessions:many,error:''}).match(/data-ai-session="/g)?.length,8,'최대 8개만 보여야 합니다.');});

test('대화 효율 구역은 돈이 새는 대화 없음·기록 없음·조회 실패를 구분한다',()=>{const h=helpers();assert.match(h.aiSessionSectionHtml({sessions:{...SESS,flagged:[]},error:''}),/지금 돈이 새는 대화 없음/);assert.match(h.aiSessionSectionHtml({sessions:null,error:''}),/아직 올라온 점검 기록이 없습니다/);assert.match(h.aiSessionSectionHtml({sessions:null,error:'x<y'}),/점검 기록을 불러오지 못했습니다: x&lt;y/);});

test('현황판 카드는 모델별 사용량·정가 환산·대화 점검 순서로 한 카드에 묶는다',()=>{const h=helpers(),s=h.aiUsageSummary([{usage_date:'2026-09-20',model:'Astra',tokens:3,turns:1}],'2026-09-16','2026-09-22'),out=h.aiUsagePanelHtml({summary:s,start:'2026-09-16',end:'2026-09-22',error:'',cost:COST,costError:'',sessions:SESS,sessionsError:''});assert.equal(out.match(/id="aiUsagePanel"/g)?.length,1);const iModel=out.indexOf('모델별 사용량(최근 7일)'),iCost=out.indexOf('data-ai-cost-section'),iSess=out.indexOf('data-ai-session-section');assert.ok(iModel>0&&iModel<iCost&&iCost<iSess,'구역 순서가 다릅니다.');assert.match(out,/data-ai-usage-astra="true"/);});

test('AI비용 탭은 스냅샷을 원장 확인 뒤 읽기 전용으로 조회하고 실패를 해당 구역에만 표시한다',()=>{const body=html.match(/async function renderAicost\(m\)\{[\s\S]*?\r?\n\}\r?\n/)?.[0];assert.ok(body);const guard=body.indexOf("if(ME.role!=='owner')"),q=body.indexOf("sb.from('ai_usage_snapshots').select('kind,payload,synced_at').in('kind',['platform_cost','codex_sessions'])");assert.ok(guard>0&&q>guard,'원장 확인 뒤 스냅샷 조회가 없습니다.');assert.match(body,/if\(error\|\|historyError\|\|eventsError\)\{/);assert.match(body,/costError:snapshotError\?snapshotError\.message:''/);assert.match(body,/sessionsError:snapshotError\?snapshotError\.message:''/);assert.doesNotMatch(html,/from\('ai_usage_snapshots'\)\.(insert|upsert|update|delete)\(/);});

test('스냅샷 SQL은 원장 읽기 전용 RLS·크기 제한·service-role 전용 저장 함수만 두고 Task 6 객체를 건드리지 않는다',()=>{const sql=read('db/ai_usage_snapshots.sql'),rollback=read('db/ai_usage_snapshots_rollback.sql');assert.match(sql,/create table if not exists public\.ai_usage_snapshots/i);assert.match(sql,/kind text primary key check\(kind in\('platform_cost','codex_sessions'\)\)/i);assert.match(sql,/octet_length\(payload::text\)<=131072/i);assert.match(sql,/alter table public\.ai_usage_snapshots enable row level security/i);assert.match(sql,/revoke all on table public\.ai_usage_snapshots from public,anon,authenticated/i);assert.match(sql,/create policy ai_usage_snapshots_owner_select on public\.ai_usage_snapshots for select to authenticated using\(\(select public\.my_role\(\)\)='owner'\)/i);assert.doesNotMatch(sql,/for (insert|update|delete|all)\b/i);assert.match(sql,/function public\.ai_usage_snapshot_put\(p_kind text,p_payload jsonb\)[\s\S]*security invoker set search_path=''/i);assert.match(sql,/revoke all on function public\.ai_usage_snapshot_put\(text,jsonb\) from public,anon,authenticated/i);assert.match(sql,/grant execute on function public\.ai_usage_snapshot_put\(text,jsonb\) to service_role/i);for(const s of [sql,rollback])assert.doesNotMatch(s,/notice|storage\.|deposits|bucket/i);assert.match(rollback,/drop function if exists public\.ai_usage_snapshot_put\(text,jsonb\)/i);assert.match(rollback,/drop table if exists public\.ai_usage_snapshots/i);});

test('Edge Function은 kind로 사용량·스냅샷을 나누고, 모르는 kind는 거절하며, 본문은 64KB를 넘는 순간 읽기를 멈춘다',()=>{const edge=read('supabase/functions/ai-usage-sync/index.ts');assert.match(edge,/new URL\(req\.url\)\.searchParams\.get\('kind'\)\|\|'model_usage'/);assert.match(edge,/SNAPSHOT_KINDS\.has\(kind\)/);assert.match(edge,/\.rpc\('ai_usage_snapshot_put',\{p_kind:kind,p_payload:snap\.value\}\)/);assert.match(edge,/\.rpc\('ai_model_usage_replace',\{p_usage:parsed\.value\.usage\}\)/);assert.match(edge,/response\(400,\{error:'unknown_kind'\}\)/);assert.match(edge,/readLimited\(req,MAX_BODY_BYTES\)/);assert.match(edge,/reader\.cancel\(\)/);assert.doesNotMatch(edge,/req\.text\(\)/);assert.ok(edge.indexOf("sameHex(await sha256Hex(token)")<edge.indexOf("readLimited(req,MAX_BODY_BYTES)"),'토큰 확인 전에 본문을 읽습니다.');});

test('비용 스냅샷은 알려진 필드만 남기고, 잘못된 항목만 버리며, DB가 못 받는 숫자·문자는 정리한다',async()=>{const {validatePlatformCost,MAX_BODY_BYTES}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const C=String.fromCharCode;const ok=validatePlatformCost({...COST,extra:'drop-me'});assert.equal(ok.ok,true);assert.equal('extra' in ok.value,false);assert.deepEqual(Object.keys(ok.value.agents).sort(),['claude','codex','kimi','openclaw']);assert.equal(ok.value.agents.claude.months.length,3);assert.equal(ok.value.fx,1375.642214);assert.equal(validatePlatformCost({...COST,this_month:null}).ok,true);
  const month=j=>`${2021+Math.floor(j/12)}-${String(j%12+1).padStart(2,'0')}`,tiny={...COST,fx_src:'a'+C(0)+'b'+C(0xd800)+'c',generated:'2026-09-22 17:35'+'x'.repeat(40),agents:Object.fromEntries(Array.from({length:10},(_,i)=>['a'+i,{cumUSD:5e-324,months:Array.from({length:60},(_,j)=>({m:month(j),usd:5e-324})),inTok:1,outTok:1,ok:true}]))};
  const t=validatePlatformCost(tiny);assert.equal(t.ok,true);assert.equal(t.value.agents.a0.months[0].usd,0);assert.equal(t.value.agents.a0.cumUSD,0);assert.equal(t.value.fx_src.includes(C(0)),false);assert.equal(t.value.fx_src.isWellFormed(),true);assert.ok(t.value.generated.length<=32);assert.ok(Buffer.byteLength(JSON.stringify(t.value))<=MAX_BODY_BYTES);assert.doesNotMatch(JSON.stringify(t.value),/e-/,'지수 표기 숫자가 남아 있습니다.');
  const tol=validatePlatformCost({...COST,agents:{...COST.agents,'Bad Key!':COST.agents.claude,daily:{cumUSD:1,months:[{m:'2026-09-22',usd:1},{m:'Sept',usd:1}],inTok:1,outTok:1,ok:true}},this_month:'2026-09-22',month_usd:{'2026-09-22':1,bad:2}});assert.equal(tol.ok,true);assert.equal('Bad Key!' in tol.value.agents,false);assert.deepEqual(JSON.parse(JSON.stringify(tol.value.agents.daily.months)),[{m:'2026-09-22',usd:1}]);assert.equal(tol.value.this_month,'2026-09-22');assert.deepEqual(Object.keys(tol.value.month_usd),['2026-09-22']);
  const proto=validatePlatformCost(JSON.parse('{"fx":1,"generated":"g","agents":{"__proto__":{"cumUSD":1,"months":[],"inTok":0,"outTok":0}}}'));assert.equal(proto.ok,true);assert.ok(JSON.stringify(proto.value).includes('"__proto__"'),'__proto__ 플랫폼이 사라졌습니다.');
  for(const b of [null,[],{...COST,agents:undefined},{...COST,fx:0},{...COST,fx:'1375'},{...COST,generated:undefined},{...COST,agents:{'Bad Key!':COST.agents.claude}}])assert.equal(validatePlatformCost(b).ok,false,JSON.stringify(b)?.slice(0,90));});

test('대화 점검 스냅샷은 모르는 필드·PC 경로·세션 ID를 버리고, 표시 필드는 자르고 정리해 받아들인다',async()=>{const {validateSessionHealth,MAX_FLAGGED,MAX_BODY_BYTES}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const C=String.fromCharCode;const raw={...SESS,scanned:40,new_top_field:{x:1},flagged:[{...SESS.flagged[0],file:'C:\\Users\\x\\.codex\\sessions\\rollout.jsonl',tid:'uuid',mtime:'17:30',size_mb:72.1,new_field:'x'},SESS.flagged[1]]};const ok=validateSessionHealth(raw);assert.equal(ok.ok,true);assert.deepEqual(Object.keys(ok.value.flagged[0]).sort(),['active','name','reasons','sev','share','thread','tok_today','won_today']);assert.equal(JSON.stringify(ok.value).includes('rollout'),false);assert.equal(JSON.stringify(ok.value).includes('new_top_field'),false);
  const many=validateSessionHealth({...SESS,won_today_total:'1',flagged:Array.from({length:MAX_FLAGGED+5},()=>SESS.flagged[1])});assert.equal(many.ok,true);assert.equal(many.value.flagged.length,MAX_FLAGGED);assert.equal(many.value.won_today_total,0);
  const odd=validateSessionHealth({...SESS,flagged:[{...SESS.flagged[0],sev:'purple',active:'yes',name:'ab'+C(0)+C(0xdc00)+'x'.repeat(300),reasons:['r'.repeat(500),1,...Array(10).fill('y')],won_today:-1,share:'5'}]});assert.equal(odd.ok,true);const f=odd.value.flagged[0];assert.ok(f.name.length<=120);assert.equal(f.name.includes(C(0)),false);assert.equal(f.name.isWellFormed(),true);assert.ok(f.reasons.length<=6);assert.ok(f.reasons.every(r=>typeof r==='string'&&r.length<=200));assert.equal(f.won_today,0);assert.equal(f.share,0);assert.equal(f.active,false);assert.ok(typeof f.sev==='string'&&f.sev.length<=16);
  const huge=validateSessionHealth({...SESS,flagged:Array.from({length:MAX_FLAGGED},()=>({...SESS.flagged[0],name:'가'.repeat(120),reasons:Array(6).fill('나'.repeat(200))}))});assert.equal(huge.ok,false,'정리 후에도 64KB를 넘으면 거절해야 합니다.');assert.equal(huge.error,'too_large');assert.ok(MAX_BODY_BYTES===65536);
  for(const b of [null,[],{...SESS,flagged:{}},{...SESS,generated:undefined}])assert.equal(validateSessionHealth(b).ok,false,JSON.stringify(b)?.slice(0,90));});

test('모델명이 constructor·toString·__proto__여도 집계·검사·플랫폼 이름에서 빠지거나 바뀌지 않는다',async()=>{const h=helpers(),s=h.aiUsageSummary([{usage_date:'2026-09-20',model:'constructor',tokens:7,turns:1},{usage_date:'2026-09-20',model:'Sol',tokens:3,turns:1},{usage_date:'2026-09-20',model:'toString',tokens:5,turns:1},{usage_date:'2026-09-20',model:'__proto__',tokens:5,turns:1}],'2026-09-16','2026-09-22');assert.equal(s.total,20);assert.deepEqual([...s.models].map(m=>m.model).sort(),['Sol','__proto__','constructor','toString']);assert.equal(Math.round([...s.models].reduce((a,m)=>a+m.share,0)),100);
  const cost=h.aiCostSectionHtml({cost:{fx:1,generated:'g',agents:JSON.parse('{"constructor":{"cumUSD":1,"months":[],"inTok":0,"outTok":0},"__proto__":{"cumUSD":2,"months":[],"inTok":0,"outTok":0}}'),month_usd:{}},error:''});assert.doesNotMatch(cost,/function|native code/);assert.match(cost,/data-ai-cost-platform="constructor"/);assert.match(cost,/data-ai-cost-platform="__proto__"/);
  const {validateUsagePayload}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const u=validateUsagePayload(JSON.parse('{"2026-09-21":{"__proto__":{"tokens":1,"turns":1},"Sol":{"tokens":2,"turns":1}}}'),'2026-09-22');assert.equal(u.ok,true);assert.equal(u.value.rows,2);assert.ok(JSON.stringify(u.value.usage).includes('"__proto__"'),'__proto__ 모델 행이 사라졌습니다.');});
