const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),html=read('hr.html');
const esc=s=>String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function helpers(){const block=html.match(/\/\* ai-usage:test-start \*\/[\s\S]*?\/\* ai-usage:test-end \*\//)?.[0];assert.ok(block,'AI 사용량 순수 helper가 없습니다.');const c={esc};vm.createContext(c);vm.runInContext(block+';this.h={aiUsageSummary,aiUsagePanelHtml,aiCostSectionHtml,aiSessionSectionHtml};',c);return c.h;}
const won=v=>Math.round(v).toLocaleString('ko-KR');
const COST={fx:1375.642214,fx_src:'open.er-api.com',generated:'2026-09-22 17:35',total_usd:16074.96,this_month:'2026-09',this_usd:6289.71,
  agents:{kimi:{cumUSD:250.26,months:[{m:'2026-07',usd:134.77},{m:'2026-08',usd:99.08},{m:'2026-09',usd:16.41}],inTok:374575114,outTok:2283194,ok:true},
    claude:{cumUSD:12626.65,months:[{m:'2026-07',usd:3992.29},{m:'2026-08',usd:4631.24},{m:'2026-09',usd:4003.12}],inTok:12777754284,outTok:63426244,ok:true},
    codex:{cumUSD:3197.81,months:[{m:'2026-07',usd:648.5},{m:'2026-08',usd:279.12},{m:'2026-09',usd:2270.19}],inTok:6262044960,outTok:22934163,ok:true},
    openclaw:{cumUSD:0.25,months:[{m:'2026-07',usd:0.25}],inTok:311977908,outTok:2317997,ok:true}},
  month_usd:{'2026-02':1,'2026-03':2,'2026-04':3,'2026-05':4,'2026-06':5,'2026-07':4775.81,'2026-08':5009.44,'2026-09':6289.71}};
const SESS={generated:'2026-09-22 17:33',won_today_total:193974,tok_today_total:775000000,flagged:[
  {name:'T8 인프라 <작업>',thread:'019a1b2c',sev:'red',active:true,tok_today:21475513,won_today:5368,share:2.8,reasons:['대기만 반복(최근60분 wait 23·편집0)','기록 72MB(매 턴 다시 읽음)']},
  {name:'',thread:'019a9999',sev:'orange',active:false,tok_today:40000000,won_today:10000,share:5,reasons:['오늘 4천만 토큰']}]};

test('정가 환산 구역은 청구액이 아님을 밝히고 이번 달·누적·플랫폼·월별 합계를 환율로 환산한다',()=>{const h=helpers(),out=h.aiCostSectionHtml({cost:COST,error:''});assert.match(out,/정가 환산/);assert.match(out,/청구액 아님/);assert.ok(out.includes('₩'+won(6289.71*1375.642214)),'이번 달 합계 환산이 없습니다.');assert.ok(out.includes('₩'+won(16074.96*1375.642214)),'누적 환산이 없습니다.');const iC=out.indexOf('data-ai-cost-platform="claude"'),iX=out.indexOf('data-ai-cost-platform="codex"'),iK=out.indexOf('data-ai-cost-platform="kimi"'),iO=out.indexOf('data-ai-cost-platform="openclaw"');assert.ok(iC>0&&iC<iX&&iX<iK&&iK<iO,'플랫폼이 누적 큰 순서가 아닙니다.');assert.match(out,/Claude Code/);assert.match(out,/Codex \(OpenAI\)/);assert.match(out,/Kimi \(Moonshot\)/);const kimiRow=out.slice(iK,iO);assert.ok(kimiRow.includes('₩'+won(16.41*1375.642214)),'이번 달 값은 this_month 항목이어야 합니다.');const clawRow=out.slice(iO,out.indexOf('</tr>',iO));assert.ok(clawRow.includes('₩0'),'이번 달 항목이 없는 플랫폼은 0이어야 합니다.');assert.equal(out.match(/data-ai-cost-month="/g)?.length,6,'월별 합계는 최근 6개월만 그립니다.');assert.doesNotMatch(out,/data-ai-cost-month="2026-02"/);assert.match(out,/data-ai-cost-month="2026-09"/);assert.match(out,/2026-09-22 17:35/);assert.match(out,/US\$1 = ₩1,376/);});

test('정가 환산 구역은 기록 없음·조회 실패를 알리고 외부 문자열을 이스케이프한다',()=>{const h=helpers();assert.match(h.aiCostSectionHtml({cost:null,error:''}),/아직 올라온 비용 기록이 없습니다/);const failed=h.aiCostSectionHtml({cost:null,error:'bad <x>'});assert.match(failed,/비용 기록을 불러오지 못했습니다/);assert.match(failed,/bad &lt;x&gt;/);const evil=h.aiCostSectionHtml({cost:{...COST,fx_src:'<script>x</script>',generated:'<b>t</b>',agents:{'<i>':{cumUSD:1,months:[],inTok:0,outTok:0,ok:true}}},error:''});assert.doesNotMatch(evil,/<script>x<\/script>|<b>t<\/b>|<i>/);assert.match(evil,/&lt;script&gt;/);});

test('대화 효율 구역은 빨강·주황 표시, 활성 여부, 추정 비용, 사유를 보여 주고 이름을 이스케이프한다',()=>{const h=helpers(),out=h.aiSessionSectionHtml({sessions:SESS,error:''});assert.match(out,/Codex 대화 효율 점검/);assert.match(out,/오늘 전체 약 ₩193,974/);assert.match(out,/2026-09-22 17:33/);assert.match(out,/🔴/);assert.match(out,/🟠/);assert.match(out,/T8 인프라 &lt;작업&gt;/);assert.doesNotMatch(out,/<작업>/);assert.match(out,/019a9999/,'이름이 비면 thread로 대신 표시해야 합니다.');assert.match(out,/활성/);assert.match(out,/멈춤/);assert.match(out,/약 ₩5,368/);assert.match(out,/대기만 반복\(최근60분 wait 23·편집0\) · 기록 72MB/);const many={...SESS,flagged:Array.from({length:10},(_,i)=>({name:'대화'+i,thread:'t'+i,sev:'orange',active:false,won_today:i,tok_today:i,share:0,reasons:[]}))};assert.equal(h.aiSessionSectionHtml({sessions:many,error:''}).match(/data-ai-session="/g)?.length,8,'최대 8개만 보여야 합니다.');});

test('대화 효율 구역은 돈이 새는 대화 없음·기록 없음·조회 실패를 구분한다',()=>{const h=helpers();assert.match(h.aiSessionSectionHtml({sessions:{...SESS,flagged:[]},error:''}),/지금 돈이 새는 대화 없음/);assert.match(h.aiSessionSectionHtml({sessions:null,error:''}),/아직 올라온 점검 기록이 없습니다/);assert.match(h.aiSessionSectionHtml({sessions:null,error:'x<y'}),/점검 기록을 불러오지 못했습니다: x&lt;y/);});

test('현황판 카드는 모델별 사용량·정가 환산·대화 점검 순서로 한 카드에 묶는다',()=>{const h=helpers(),s=h.aiUsageSummary([{usage_date:'2026-09-20',model:'Astra',tokens:3,turns:1}],'2026-09-16','2026-09-22'),out=h.aiUsagePanelHtml({summary:s,start:'2026-09-16',end:'2026-09-22',error:'',cost:COST,costError:'',sessions:SESS,sessionsError:''});assert.equal(out.match(/id="aiUsagePanel"/g)?.length,1);const iModel=out.indexOf('모델별 사용량(최근 7일)'),iCost=out.indexOf('data-ai-cost-section'),iSess=out.indexOf('data-ai-session-section');assert.ok(iModel>0&&iModel<iCost&&iCost<iSess,'구역 순서가 다릅니다.');assert.match(out,/data-ai-usage-astra="true"/);});

test('AI비용 탭은 스냅샷을 원장 확인 뒤 읽기 전용으로 조회하고 실패를 해당 구역에만 표시한다',()=>{const body=html.match(/async function renderAicost\(m\)\{[\s\S]*?\r?\n\}\r?\n/)?.[0];assert.ok(body);const guard=body.indexOf("if(ME.role!=='owner')"),q=body.indexOf("sb.from('ai_usage_snapshots').select('kind,payload,synced_at').in('kind',['platform_cost','codex_sessions'])");assert.ok(guard>0&&q>guard,'원장 확인 뒤 스냅샷 조회가 없습니다.');assert.match(body,/if\(error\|\|historyError\|\|eventsError\)\{/);assert.match(body,/costError:snapshotError\?snapshotError\.message:''/);assert.match(body,/sessionsError:snapshotError\?snapshotError\.message:''/);assert.doesNotMatch(html,/from\('ai_usage_snapshots'\)\.(insert|upsert|update|delete)\(/);});

test('스냅샷 SQL은 원장 읽기 전용 RLS·크기 제한·service-role 전용 저장 함수만 두고 Task 6 객체를 건드리지 않는다',()=>{const sql=read('db/ai_usage_snapshots.sql'),rollback=read('db/ai_usage_snapshots_rollback.sql');assert.match(sql,/create table if not exists public\.ai_usage_snapshots/i);assert.match(sql,/kind text primary key check\(kind in\('platform_cost','codex_sessions'\)\)/i);assert.match(sql,/octet_length\(payload::text\)<=131072/i);assert.match(sql,/alter table public\.ai_usage_snapshots enable row level security/i);assert.match(sql,/revoke all on table public\.ai_usage_snapshots from public,anon,authenticated/i);assert.match(sql,/create policy ai_usage_snapshots_owner_select on public\.ai_usage_snapshots for select to authenticated using\(\(select public\.my_role\(\)\)='owner'\)/i);assert.doesNotMatch(sql,/for (insert|update|delete|all)\b/i);assert.match(sql,/function public\.ai_usage_snapshot_put\(p_kind text,p_payload jsonb\)[\s\S]*security invoker set search_path=''/i);assert.match(sql,/revoke all on function public\.ai_usage_snapshot_put\(text,jsonb\) from public,anon,authenticated/i);assert.match(sql,/grant execute on function public\.ai_usage_snapshot_put\(text,jsonb\) to service_role/i);for(const s of [sql,rollback])assert.doesNotMatch(s,/notice|storage\.|deposits|bucket/i);assert.match(rollback,/drop function if exists public\.ai_usage_snapshot_put\(text,jsonb\)/i);assert.match(rollback,/drop table if exists public\.ai_usage_snapshots/i);});

test('Edge Function은 kind로 사용량·스냅샷을 나누고 모르는 kind는 거절한다',()=>{const edge=read('supabase/functions/ai-usage-sync/index.ts');assert.match(edge,/new URL\(req\.url\)\.searchParams\.get\('kind'\)\|\|'model_usage'/);assert.match(edge,/SNAPSHOT_KINDS\.has\(kind\)/);assert.match(edge,/\.rpc\('ai_usage_snapshot_put',\{p_kind:kind,p_payload:snap\.value\}\)/);assert.match(edge,/\.rpc\('ai_model_usage_replace',\{p_usage:parsed\.value\.usage\}\)/);assert.match(edge,/response\(400,\{error:'unknown_kind'\}\)/);assert.ok(edge.indexOf("sameHex(await sha256Hex(token)")<edge.indexOf("req.text()"),'토큰 확인 전에 본문을 읽습니다.');});

test('비용 스냅샷 검증은 알려진 필드만 남기고 형식·범위를 확인한다',async()=>{const {validatePlatformCost}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const ok=validatePlatformCost({...COST,extra:'drop-me'});assert.equal(ok.ok,true);assert.equal('extra' in ok.value,false);assert.deepEqual(Object.keys(ok.value.agents).sort(),['claude','codex','kimi','openclaw']);assert.equal(ok.value.agents.claude.months.length,3);assert.equal(ok.value.fx,1375.642214);assert.equal(validatePlatformCost({...COST,this_month:null}).ok,true);const bad=[null,[],{...COST,agents:undefined},{...COST,fx:0},{...COST,fx:'1375'},{...COST,generated:'x'.repeat(33)},{...COST,agents:{'Claude Code!':COST.agents.claude}},{...COST,agents:{claude:{...COST.agents.claude,cumUSD:-1}}},{...COST,agents:{claude:{...COST.agents.claude,months:{}}}},{...COST,agents:{claude:{...COST.agents.claude,months:[{m:'Sept',usd:1}]}}},{...COST,agents:{claude:{...COST.agents.claude,inTok:1.5}}},{...COST,month_usd:{'2026-09':'1'}},{...COST,this_month:'2026-9'}];for(const b of bad)assert.equal(validatePlatformCost(b).ok,false,JSON.stringify(b)?.slice(0,90));});

test('대화 점검 스냅샷 검증은 PC 경로·세션 ID 같은 필드를 버리고 표시 필드만 검사한다',async()=>{const {validateSessionHealth,MAX_FLAGGED}=await import('../supabase/functions/ai-usage-sync/payload.mjs');const raw={...SESS,scanned:40,flagged:[{...SESS.flagged[0],file:'C:\\Users\\x\\.codex\\sessions\\rollout.jsonl',tid:'uuid',mtime:'17:30',size_mb:72.1},SESS.flagged[1]]};const ok=validateSessionHealth(raw);assert.equal(ok.ok,true);assert.deepEqual(Object.keys(ok.value.flagged[0]).sort(),['active','name','reasons','sev','share','thread','tok_today','won_today']);assert.equal(JSON.stringify(ok.value).includes('rollout'),false);const many={...SESS,flagged:Array.from({length:MAX_FLAGGED+1},()=>SESS.flagged[1])};const bad=[null,{...SESS,flagged:{}},many,{...SESS,generated:undefined},{...SESS,flagged:[{...SESS.flagged[0],sev:'purple'}]},{...SESS,flagged:[{...SESS.flagged[0],reasons:'x'}]},{...SESS,flagged:[{...SESS.flagged[0],reasons:['x'.repeat(201)]}]},{...SESS,flagged:[{...SESS.flagged[0],name:'x'.repeat(121)}]},{...SESS,flagged:[{...SESS.flagged[0],won_today:-1}]},{...SESS,won_today_total:'1'}];for(const b of bad)assert.equal(validateSessionHealth(b).ok,false,JSON.stringify(b)?.slice(0,90));});
