const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const hr=fs.readFileSync('hr.html','utf8'),ui=fs.readFileSync('card-ledger-ui.js','utf8'),hub=fs.readFileSync('hub-texts.js','utf8');
function harness(settings={}){const c={Intl,Date};vm.createContext(c);vm.runInContext(ui,c);vm.runInContext(hub.replace('root.hubText=hubText;','root.ledgerDefs={texts:hubTextDefs,settings:HUB_SETTING_DEFS,lists:HUB_LIST_DEFS};root.hubText=hubText;'),c);c.HubUi.setSettings(settings);vm.runInContext(fs.readFileSync('spend-cycle.js','utf8'),c);return c;}
const row=(id,extra={})=>({id,card_issuer:'samsung',card_last4:'4430',event_kind:'purchase',transaction_at:'2026-10-01T23:50:00Z',currency:'KRW',amount_native:1000,amount_krw:1000,merchant:'원래 상호',merchant_id:1,...extra});
const merchant={id:1,merchant_key:'key',display_name:'고친 이름',category:'병원',memo:''};
const plain=x=>JSON.parse(JSON.stringify(x));
function state(extra={}){return {filters:{from:'2026-10-01',to:'2026-10-31',card:'',category:''},rows:[row(1)],merchants:[merchant],failed:[],subscriptions:[],errors:[null,null,null,null],...extra};}
function mockDb(data,errorTable){const calls=[];return {calls,from(table){const call={table,ops:[]};calls.push(call);const q={};for(const method of ['select','order','gte','lte','gt','eq','update'])q[method]=(...args)=>{call.ops.push([method,...args]);return q;};q.range=()=>Promise.resolve({data:data[table]||[],error:table===errorTable?{message:'synthetic'}:null});q.then=(resolve,reject)=>Promise.resolve({data:data[table]||[],error:table===errorTable?{message:'synthetic'}:null}).then(resolve,reject);return q;}};}
test('원장 전용 메뉴와 실제 render 경로가 연결됨',()=>{assert.match(hr,/CardLedgerUi\.render\(m,\{sb,me:ME/);const code=hr.match(/function installCardLedgerTab[\s\S]*?(?=if\(typeof TABS)/)[0];const c={};vm.createContext(c);vm.runInContext(code,c);const tabs=[],menu=[{key:'g-owner',children:['owner']}];c.installCardLedgerTab(tabs,menu);c.installCardLedgerTab(tabs,menu);assert.equal(tabs.length,1);assert.deepEqual(plain(tabs[0].roles),['owner']);assert.deepEqual(menu[0].children,['owner','ledger']);});
test('직원·관리자·부원장은 메뉴 예외로도 지출 점검에 들어올 수 없음',async()=>{for(const role of ['staff','manager','chief','deputy']){const c=harness();c.ME={role,id:'u'};c.TAB_OVERRIDES={u:{ledger:true}};c.TAB_ROLES={ledger:[role]};c.TABS=[{key:'ledger',roles:['owner']}];vm.runInContext(hr.match(/\/\* menu-restructure:test-start \*\/([\s\S]*?)\/\* menu-restructure:test-end \*\//)[1],c);assert.equal(c.visibleTabKeys().has('ledger'),false);const db=mockDb({});assert.equal(await c.CardLedgerUi.load({me:{role},sb:db},{}),null);const target={innerHTML:''};await c.CardLedgerUi.render(target,{me:{role},sb:db});assert.equal(db.calls.length,0);assert.match(target.innerHTML,/원장만/);}});
test('한국 날짜·기간·카드·용도 필터와 사전 편집값을 사용함',()=>{const c=harness(),a=c.CardLedgerUi;const rows=a.enrich([row(1),row(2,{card_issuer:'kb',card_last4:'0051',merchant_id:2}),row(3,{transaction_at:'2026-09-30T10:00:00Z'})],[merchant]);assert.equal(a.date(rows[0].transaction_at),'2026-10-02');const filtered=a.filter(rows,{from:'2026-10-01',to:'2026-10-02',card:'samsung:4430',category:'병원'});assert.deepEqual(plain(filtered.map(r=>r.id)),[1]);assert.equal(filtered[0].display_name,'고친 이름');});
test('취소는 합계에서 빠지고 원화 미환산은 금액 0과 구별됨',()=>{const c=harness(),a=c.CardLedgerUi;const rows=[row(1),row(2,{event_kind:'cancellation',amount_krw:-400}),row(3,{amount_krw:null,currency:'VND'})];const r=a.aggregate(rows,()=> '한달')[0];assert.deepEqual(plain(r),{key:'한달',count:3,amount:600,unconverted:1});const out=a.html(state({rows}));assert.match(out,/₩600/);assert.match(out,/원화 환산 전/);assert.match(out,/취소/);});
test('다른 달에도 같은 기간 합계를 계산함',()=>{const c=harness();const out=c.CardLedgerUi.html(state({filters:{from:'2025-01-01',to:'2025-01-31',card:'',category:''},rows:[row(1,{transaction_at:'2025-01-15T10:00:00Z',amount_krw:3210})]}));assert.match(out,/<b>합계 ₩3,210<\/b>/);});
test('문구·목록·숫자 기준은 기존 허브 DB 설정으로 변경됨',async()=>{const c=harness({'ledger.row_limit':'5','list.ledger_categories':JSON.stringify([{code:'병원',label:'진료비'}]),'list.ledger_cards':JSON.stringify([{code:'samsung:4430',label:'업무 카드'}])});await c.HubUi.load({from(){return {select(){return Promise.resolve({data:[{key:'ledger.title',value:'내 지출'}],error:null});}}}});const out=c.CardLedgerUi.html(state({rows:Array.from({length:7},(_,i)=>row(i))}));assert.match(out,/내 지출/);assert.match(out,/진료비/);assert.match(out,/업무 카드/);assert.match(out,/앞에서 5건/);const defs=c.ledgerDefs.texts();for(const k of Object.keys(c.CardLedgerUi.TEXTS))assert.ok(defs.some(d=>d.key==='ledger.'+k),k);assert.ok(defs.some(d=>d.key==='tab.ledger'));for(const k of ['default_days','row_limit','merchant_limit','failed_limit','memo_max','subscription_field_max'])assert.ok(c.ledgerDefs.settings.some(d=>d.key==='ledger.'+k));});
test('조회 실패를 빈 내역과 구분하고 부분 조회 오류를 표시함',async()=>{const c=harness(),db=mockDb({card_transactions:[row(1)],card_merchants:[merchant],app_settings:[{key:'ledger.subscriptions',value:'[]'}]},'card_transactions');const s=await c.CardLedgerUi.load({me:{role:'owner'},sb:db},{from:'2026-10-01',to:'2026-10-31'});assert.ok(s.errors[0]);assert.match(c.CardLedgerUi.html(s),/불러오지 못했습니다/);assert.doesNotMatch(c.CardLedgerUi.html(s),/월별 합계/);const read=db.calls.find(x=>x.table==='card_transactions');assert.ok(read.ops.some(x=>x[0]==='gte'&&x[2]==='2026-10-01T00:00:00+09:00'));assert.ok(db.calls.find(x=>x.table==='card_sms_failed_raw').ops.some(x=>x[0]==='gt'&&x[1]==='expires_at'));});
test('성공 거래는 원문을 조회하지 않으며 실패 문자만 원장 화면에 표시함',async()=>{const c=harness(),db=mockDb({});await c.CardLedgerUi.load({me:{role:'owner'},sb:db},{});for(const read of db.calls.filter(x=>x.table!=='card_sms_failed_raw'))assert.doesNotMatch(String(read.ops),/raw_text|\bbody\b/);const out=c.CardLedgerUi.html(state({failed:[{id:1,body:'<script>alert(1)</script>',received_at:'2026-10-01',expires_at:'2026-10-31',fail_reason:'bad'}]}));assert.match(out,/&lt;script&gt;/);assert.doesNotMatch(out,/<script>alert/);});
test('가맹점 저장은 원장 검사를 통과해야 하며 오류와 0행 갱신을 실패로 돌려줌',async()=>{const c=harness(),a=c.CardLedgerUi,value={display_name:'새 이름',category:'AI',ai_platform:'mimo',memo:'메모'};const db=mockDb({card_merchants:[{id:1}]});assert.equal((await a.saveMerchant({me:{role:'staff'},sb:db},1,value)).ok,false);assert.equal(db.calls.length,0);assert.equal((await a.saveMerchant({me:{role:'owner'},sb:db},1,value)).ok,true);assert.equal(db.calls[0].table,'card_merchants');assert.equal(db.calls[0].ops.find(o=>o[0]==='update')[1].category,'AI');assert.equal((await a.saveMerchant({me:{role:'owner'},sb:mockDb({})},1,value)).ok,false);assert.equal((await a.saveMerchant({me:{role:'owner'},sb:mockDb({},'card_merchants')},1,value)).ok,false);assert.equal(a.validateMerchant({...value,category:'unknown'}),false);});
test('정기결제는 DB 설정을 읽고 기존 값 일치 때 저장하며 새 항목도 추가됨',async()=>{const c=harness(),a=c.CardLedgerUi,value=Object.fromEntries(a.FIELDS.map(k=>[k,k==='service'?'서비스':''])),raw=JSON.stringify([value],null,2),db=mockDb({app_settings:[{key:'ledger.subscriptions',value:raw}]});const ctx={me:{role:'owner'},sb:db};const s=await a.load(ctx,{});assert.equal(s.subscriptionRaw,raw);const saveDb=mockDb({app_settings:[{key:'ledger.subscriptions'}]});const r=await a.saveSubscription({...ctx,sb:saveDb,subscriptionRaw:raw},s.subscriptions,-1,{...value,service:'새 서비스'});assert.equal(r.ok,true);assert.equal(r.rows.length,2);assert.ok(saveDb.calls[0].ops.some(o=>o[0]==='eq'&&o[1]==='value'&&o[2]===raw));assert.equal((await a.saveSubscription({...ctx,sb:mockDb({}),subscriptionRaw:raw},s.subscriptions,0,value)).ok,false);assert.equal((await a.saveSubscription({...ctx,me:{role:'chief'}},s.subscriptions,0,value)).ok,false);});
test('설정 파싱 오류 때 임의 기본 목록을 저장하지 않고 편집을 숨김',()=>{const c=harness(),a=c.CardLedgerUi;for(const bad of ['bad','{}','[{}]','[{"service":12}]','[{"service":"s","cycle":2}]'])assert.equal(a.subscriptions(bad),null);const out=a.html(state({subscriptions:null}));assert.match(out,/설정을 읽지 못해/);assert.doesNotMatch(out,/data-ledger-subscription=/);});
test('저장 실패 시 입력을 유지하며 클릭 이벤트를 한 패널에만 연결함',()=>{assert.match(ui,/button\.disabled=false;msg\.textContent/);assert.doesNotMatch(ui,/location\.reload|alert\(/);assert.match(ui,/target\.querySelector\('\[data-ledger-panel\]'\)/);assert.match(hr,/@media\(max-width:600px\).*?grid-template-columns:100px minmax\(0,1fr\)/);});
test('기간 재조회 때 기존 패널 안에 새 패널을 중첩하지 않음',async()=>{
 const c=harness(),db=mockDb({app_settings:[{key:'ledger.subscriptions',value:'[]'}]}),panels=[];let drawings=0;
 const target={set innerHTML(value){drawings++;this.value=value;},get innerHTML(){return this.value;},querySelector(){const p={listeners:{},addEventListener(name,fn){this.listeners[name]=fn;}};panels.push(p);return p;}};
 await c.CardLedgerUi.render(target,{me:{role:'owner'},sb:db},{from:'2026-10-01',to:'2026-10-31',card:'',category:''});
 const form={matches(){return true;},hasAttribute(name){return name==='data-ledger-filters';},querySelector(){return {};},elements:{namedItem(k){return {value:{from:'2026-09-01',to:'2026-09-30',card:'',category:''}[k]};}}};
 await panels[0].listeners.submit({target:form,preventDefault(){}});
 assert.equal(panels.length,2);assert.equal(drawings,4);assert.equal(panels[0].innerHTML,undefined);assert.match(target.innerHTML,/2026-09-01/);
 await panels[1].listeners.submit({target:form,preventDefault(){}});assert.equal(panels.length,3);assert.equal(panels[1].innerHTML,undefined);
});
test('늦게 끝난 이전 조회가 새 화면을 덮어쓰지 않음',async()=>{
 const c=harness(),db=mockDb({app_settings:[{key:'ledger.subscriptions',value:'[]'}]});let release;
 const pending=new Promise(resolve=>{release=resolve;}),target={innerHTML:'',querySelector(){return {addEventListener(){}};}};
 const first=c.CardLedgerUi.render(target,{me:{role:'owner'},sb:db,fetchAll:()=>pending},{from:'2026-09-01',to:'2026-09-30',card:'',category:''});
 await c.CardLedgerUi.render(target,{me:{role:'owner'},sb:db},{from:'2026-10-01',to:'2026-10-31',card:'',category:''});const current=target.innerHTML;
 release({data:[],error:null});await first;assert.equal(target.innerHTML,current);assert.match(current,/2026-10-01/);
});
