const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),html=read('hr.html');
test('inbox desktop and mobile cards keep the same records and detail action',()=>{const fn=html.match(/function inboxRenderList\(rows\)\{[\s\S]*?(?=async function inboxLoad)/)?.[0];const start=html.indexOf('/* consultation-inbox:test-start */'),end=html.indexOf('/* consultation-inbox:test-end */',start);assert.ok(fn);assert.ok(start>=0&&end>start);const block=html.slice(start,end);const callbacks=[],buttons=[{dataset:{inboxIds:'17'},addEventListener:(type,handler)=>callbacks.push(handler)},{dataset:{inboxIds:'17'},addEventListener:(type,handler)=>callbacks.push(handler)}],el={innerHTML:'',querySelectorAll:()=>buttons};const c={$:()=>el,PROFILES:[],esc:value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),formatLeaveTimestamp:()=> '2026.09.26 09:10',inboxNegative:row=>/Refund/.test(row.subject||''),inboxSelect:ids=>callbacks.push(ids)};vm.createContext(c);vm.runInContext(`${block};${fn};this.render=inboxRenderList;`,c);c.render([{id:'17',source:'phone',received_at:'2026-09-26T00:10:00Z',sender_name:'Patient',contact:'01012345678',subject:'Refund',status:'new'}]);assert.match(el.innerHTML,/inbox-desktop-list/);assert.match(el.innerHTML,/<th>/);assert.match(el.innerHTML,/inbox-mobile-list/);assert.match(el.innerHTML,/010-1234-5678/);assert.match(el.innerHTML,/NEW/);assert.equal(callbacks.length,2);assert.match(fn,/addEventListener\('click',\(\)=>inboxSelect\(button\.dataset\.inboxIds\.split\(','\)\)\)/);assert.match(html,/@media\(max-width:640px\)\{#inboxList \.inbox-desktop-list\{display:none\}#inboxList \.inbox-mobile-list\{display:block\}/);});

test('통합 문의함은 원본 문의를 정화하고 담당자를 명시 선택하며 전체 연락처를 표시한다',()=>{const block=html.match(/\/\* consultation-inbox:test-start \*\/[\s\S]*?\/\* consultation-inbox:test-end \*\//)?.[0];assert.ok(block);const c={PROFILES:[{user_id:'owner-id',name:'원장',role:'owner'}]};vm.createContext(c);vm.runInContext(block+';this.h={inboxSourceLabel,inboxSummary,inboxPayload};',c);assert.equal(c.h.inboxSourceLabel('kakao'),'카카오');assert.equal(c.h.inboxSourceLabel('naver_talktalk'),'네이버 톡톡');assert.equal(c.h.inboxSourceLabel('기타'),'기타');assert.equal(c.h.inboxSummary({source:'phone',sender_name:'홍길동',contact:'01012345678'}),'홍길동 · 010-1234-5678');assert.deepEqual(JSON.parse(JSON.stringify(c.h.inboxPayload({source:'manual',sender_name:' 홍길동 ',contact:'010-1234-5678',subject:'',message:' 문의 '}))),{source:'manual',sender_name:'홍길동',contact:'01012345678',subject:null,message:'문의'});assert.match(html,/id="inboxAssigned"/);assert.match(html,/assigned_to:assigned/);assert.match(html,/\['manager','chief','owner'\]/);assert.match(html,/통합 문의함 접근 권한이 없습니다/);assert.match(html,/async function inboxLoadHistory\(ids\)/);assert.match(html,/consultation_inbox_record_reply/);assert.match(html,/consultation_inbox_record_view/);assert.match(html,/INBOX_STATUSES=\[\['new','신규'\],\['in_progress','확인 중'\],\['recall_1','리콜 1차'\],\['recall_2','리콜 2차'\],\['recall_3','리콜 3차'\]/);});
test('문의함 SQL은 접근 차단·서버 SHA-256·열 단위 수정·원자 전환·service-role ingest·보존 rollback을 선언한다',()=>{const sql=read('db/consultation_inbox.sql'),rollback=read('db/consultation_inbox_rollback.sql'),edge=read('supabase/functions/consultation-ingest/index.ts'),config=read('supabase/config.toml');assert.match(sql,/create extension if not exists pgcrypto with schema extensions/i);assert.match(sql,/extensions\.digest\([^,]+,'sha256'\)/i);assert.match(sql,/on conflict\(source,external_event_id\)/i);assert.match(sql,/grant insert\(source,received_at,sender_name,contact,subject,message,created_via,created_by\) on public\.consultation_inbox/i);assert.match(sql,/grant update\(status,assigned_to\) on public\.consultation_inbox to authenticated/i);assert.match(sql,/consultation_inbox_assignee_allowed\(assigned_to\)/);assert.match(sql,/account_access_status<>'차단'/);assert.match(sql,/employee_hub_access_allowed\(\)/);assert.match(sql,/consultation_inbox_convert_to_journal/i);assert.match(sql,/consultation_inbox_ingest_service/i);assert.match(sql,/security definer/i);assert.match(sql,/new\.message is distinct from old\.message/i);assert.match(sql,/new\.received_at is distinct from old\.received_at/i);assert.match(sql,/revoke all on function public\.set_consultation_inbox_updated_at\(\) from public, anon, authenticated/i);assert.match(sql,/revoke all on function[\s\S]*from public, anon/i);assert.doesNotMatch(sql,/create policy consultation_inbox_delete/i);assert.match(rollback,/consultation_inbox contains data; rollback stopped/i);assert.match(config,/\[functions\.consultation-ingest\]\s+verify_jwt\s*=\s*true/i);assert.match(edge,/token!==serviceKey/);assert.match(edge,/Authorization:`Bearer \$\{serviceKey\}`/);assert.doesNotMatch(edge,/atob\(/);assert.match(edge,/validateIngestPayload/);assert.match(edge,/MAX_BODY_BYTES/);assert.doesNotMatch(edge,/console\.log\([^)]*(message|contact|sender|token|key)/i);});
test('Edge payload는 허용키·선택값 길이·RFC3339 달력 수신시각을 엄격히 검증한다',async()=>{const {validateIngestPayload}=await import('../supabase/functions/consultation-ingest/payload.mjs');const good={source:'kakao',event_id:'evt-1',received_at:'2026-09-22T09:00:00+09:00',sender_name:'홍길동',contact:'01012345678',subject:'문의',message:'내용'};assert.equal(validateIngestPayload(good).ok,true);assert.equal(validateIngestPayload({...good,received_at:'2024-02-29T23:59:59Z'}).ok,true);for(const bad of [{...good,extra:'x'},{...good,contact:3},{...good,received_at:'2026-99-99'},{...good,received_at:null},{...good,received_at:'2026-02-30T09:00:00+09:00'},{...good,received_at:'2025-02-29T09:00:00Z'},{...good,received_at:'2026-04-31T09:00:00Z'},{...good,sender_name:'x'.repeat(81)}])assert.equal(validateIngestPayload(bad).ok,false);});test('문의함 답변 링크는 출처별 공식 진입점을 쓰고 홈페이지 ID·전화번호를 검증한다',()=>{const block=html.match(/\/\* consultation-inbox:test-start \*\/([\s\S]*?)\/\* consultation-inbox:test-end \*\//)?.[1];assert.ok(block);const c={esc:value=>String(value).replaceAll('&','&amp;').replaceAll('"','&quot;')};vm.createContext(c);vm.runInContext(`${block};this.h={inboxReplyHref,inboxReplyLink};`,c);assert.equal(c.h.inboxReplyHref({source:'kakao'}),'https://center-pf.kakao.com/');assert.equal(c.h.inboxReplyHref({source:'naver_talktalk'}),'https://partner.talk.naver.com/');assert.equal(c.h.inboxReplyHref({source:'daangn'}),'https://chat.daangn.com/');assert.equal(c.h.inboxReplyHref({source:'homepage',external_event_id:'174'}),'https://jungplantdental.co.kr/bbs/board.php?bo_table=online&wr_id=174');for(const external_event_id of ['0','-1','../174','javascript:alert(1)',''])assert.equal(c.h.inboxReplyHref({source:'homepage',external_event_id}),'');assert.equal(c.h.inboxReplyHref({source:'phone',contact:'+82 (10) 1234-5678'}),'tel:+821012345678');for(const contact of ['123','010<script>',''])assert.equal(c.h.inboxReplyHref({source:'phone',contact}),'');assert.equal(c.h.inboxReplyHref({source:'manual'}),'');assert.match(c.h.inboxReplyLink({source:'kakao'}),/target="_blank" rel="noopener noreferrer">답하러 가기/);assert.match(c.h.inboxReplyLink({source:'phone',contact:'01012345678'}),/href="tel:01012345678">전화 걸기/);assert.match(html,/const replyLink=inboxReplyLink\(latest\)/);assert.match(html,/formatLeaveTimestamp\(row\.received_at\)/);assert.match(html,/formatLeaveTimestamp\(e\.received_at\)/);assert.match(html,/홈페이지·카카오·당근은 자동 접수되고/);});

test('문의함·AI비용 수신시각과 월별 합산은 Asia/Seoul 기준이다',()=>{const formatter=html.match(/function formatLeaveTimestamp\(value\)\{[\s\S]*?\n\}/)?.[0],monthFormatter=html.match(/function formatLeaveMonth\(value\)\{[\s\S]*?\n\}/)?.[0];assert.ok(formatter);assert.ok(monthFormatter);const c={};vm.createContext(c);vm.runInContext(`${formatter};${monthFormatter};this.format=formatLeaveTimestamp;this.month=formatLeaveMonth;`,c);assert.equal(c.format('2026-09-26T15:00:00Z'),'2026.09.27 00:00');assert.equal(c.format('2026-09-26T00:30:00+09:00'),'2026.09.26 00:30');assert.equal(c.month('2026-09-30T16:00:00Z'),'2026-10');assert.equal(c.month('2026-09-30T14:59:59Z'),'2026-09');assert.match(html,/네이버 톡톡·홈페이지·카카오·당근은 자동 접수되고, 전화·기타 문의는 수기로 접수할 수 있습니다/);assert.match(html,/formatLeaveMonth\(e\.received_at\)===AICOST_MONTH/);assert.match(html,/const ym=formatLeaveMonth\(e\.received_at\)/);});

test('문의함은 발신자 이름·채널 알림 닉네임과 전체 전화번호를 표시한다',()=>{const block=html.match(/\/\* consultation-inbox:test-start \*\/([\s\S]*?)\/\* consultation-inbox:test-end \*\//)?.[1];assert.ok(block);const c={};vm.createContext(c);vm.runInContext(`${block};this.h={inboxDisplayName,inboxFormatContact,inboxSummary};`,c);assert.equal(c.h.inboxDisplayName({source:'kakao',message:'채널명 - 닉네임\n내용'}),'닉네임');assert.equal(c.h.inboxDisplayName({source:'kakao',message:'시스템 안내입니다'}),'미상');assert.equal(c.h.inboxDisplayName({source:'daangn',message:'닉네임\n💬 메시지 내용'}),'닉네임');assert.equal(c.h.inboxDisplayName({source:'daangn',message:'💬 홍길동님이 메시지를 보냈습니다.'}),'미상');assert.equal(c.h.inboxDisplayName({source:'daangn',message:'광고 메시지입니다!'}),'미상');assert.equal(c.h.inboxDisplayName({source:'homepage',sender_name:'홍길동',message:'무시할 이름'}),'홍길동');assert.equal(c.h.inboxFormatContact('01012345678'),'010-1234-5678');assert.equal(c.h.inboxFormatContact('1234'),'1234');assert.equal(c.h.inboxSummary({source:'kakao',message:'채널 - dy',contact:'01012345678'}),'dy · 010-1234-5678');assert.match(html,/contact,subject,message,status,assigned_to/);assert.match(html,/inboxDisplayName\(latest\).*inboxFormatContact\(latest\.contact\)/);});
test('홈 문의함 카드는 지정 권한자에게만 노출되고 최근 문의 요약과 문의함 이동을 제공한다',()=>{
  const first=html.match(/\/\* inbox-first:test-start \*\/[\s\S]*?\/\* inbox-first:test-end \*\//)?.[0];
  const inbox=html.match(/\/\* consultation-inbox:test-start \*\/([\s\S]*?)\/\* consultation-inbox:test-end \*\//)?.[1];
  assert.ok(first);assert.ok(inbox);
  const c={};vm.createContext(c);vm.runInContext(`${first};${inbox};this.h={homeInboxCardEligible,homeInboxRecentRows};`,c);
  for(const me of [{role:'owner'},{role:'chief'},{role:'manager'},{role:'staff',department:'데스크'},{role:'staff',id:'212cef7e-8aab-4f72-b78d-4dfca59581e0'}])assert.equal(c.h.homeInboxCardEligible(me),true);
  assert.equal(c.h.homeInboxCardEligible({role:'staff',department:'진료',id:'other'}),false);
  assert.deepEqual(JSON.parse(JSON.stringify(c.h.homeInboxRecentRows([{received_at:'2026-09-28T00:00:00Z',source:'kakao',sender_name:'홍길동',message:'상담 문의'}]))),[{receivedAt:'2026-09-28T00:00:00Z',source:'카카오',name:'홍길동',message:'상담 문의'}]);
  assert.match(html,/if\(homeInboxCardEligible\(ME\)\)/);assert.match(html,/select\('id',\{count:'exact',head:true\}\)\.eq\('status','new'\)/);assert.match(html,/\.order\('received_at',\{ascending:false\}\)\.limit\(3\)/);assert.match(html,/onclick="go\('inbox'\)">문의함 열기/);assert.match(html,/catch\{inboxError='문의함 요약을 불러오지 못했습니다\.'/);
});

test('문의함은 같은 사람의 연속 문의를 30분 이내로 묶고 미상은 따로 남긴다',()=>{const block=html.match(/\/\* consultation-inbox:test-start \*\/[\s\S]*?\/\* consultation-inbox:test-end \*\//)?.[0];assert.ok(block);const c={};vm.createContext(c);vm.runInContext(block+';this.group=inboxGroupRows;this.summary=inboxGroupSummary;',c);const rows=[{id:'a',source:'kakao',sender_name:'민지',contact:'01012345678',received_at:'2026-09-27T23:55:00Z',status:'closed'},{id:'b',source:'kakao',sender_name:'민지',contact:'01012345678',received_at:'2026-09-28T00:25:00Z',status:'new'},{id:'c',source:'kakao',sender_name:'민지',received_at:'2026-09-28T00:56:00Z',status:'closed'},{id:'d',source:'daangn',sender_name:'수진',received_at:'2026-09-28T00:26:00Z',status:'new'},{id:'e',source:'kakao',received_at:'2026-09-28T00:26:00Z',status:'new'},{id:'f',source:'kakao',received_at:'2026-09-28T00:27:00Z',status:'new'}];const groups=c.group(rows);assert.equal(groups.length,5);assert.deepEqual(JSON.parse(JSON.stringify(groups.find(g=>g.ids.includes('a')).ids)),['b','a']);assert.equal(groups.find(g=>g.ids.includes('a')).status,'new');assert.equal(c.summary(groups.find(g=>g.ids.includes('a'))),'민지 · 010-1234-5678 (2건)');assert.deepEqual(JSON.parse(JSON.stringify(groups.find(g=>g.ids.includes('c')).ids)),['c']);assert.deepEqual(JSON.parse(JSON.stringify(groups.find(g=>g.ids.includes('e')).ids)),['e']);assert.deepEqual(JSON.parse(JSON.stringify(groups.find(g=>g.ids.includes('f')).ids)),['f']);assert.match(html,/.limit\(150\)/);assert.match(html,/data-inbox-ids/);assert.match(html,/\.in\('id',INBOX_SELECTED\.ids\)/);assert.match(html,/\.rpc\('consultation_inbox_convert_to_journal'/);});
test('문의함 조회는 출처뿐 아니라 상태 필터도 서버 질의에 함께 적용한다',()=>{assert.match(html,/if\(INBOX_FILTER\.source\)q=q\.eq\('source',INBOX_FILTER\.source\);if\(INBOX_FILTER\.status\)q=q\.eq\('status',INBOX_FILTER\.status\);/);});

test('문의함 상태 배지·그룹 상태 우선순위·처리 대상 판정·당근 이름 파싱 helper가 올바르게 동작한다',()=>{const block=html.match(/\/\* consultation-inbox:test-start \*\/[\s\S]*?\/\* consultation-inbox:test-end \*\//)?.[0];assert.ok(block);const c={};vm.createContext(c);vm.runInContext(block+';this.h={inboxStatusInfo,inboxGroupStatus,inboxGroupCounts,inboxStatusSummary,inboxProcessableRows,inboxReplyTarget,inboxDisplayName};',c);const info=status=>JSON.parse(JSON.stringify(c.h.inboxStatusInfo(status)));assert.deepEqual(info('new'),{label:'NEW(미처리)',className:'no'});assert.deepEqual(info('in_progress'),{label:'진행중',className:'wait'});assert.deepEqual(info('closed'),{label:'종결',className:'mid'});assert.deepEqual(info('converted'),{label:'상담일지 전환',className:'ok'});assert.deepEqual(info('알수없음'),{label:'알수없음',className:'mid'});assert.deepEqual(info(undefined),{label:'-',className:'mid'});assert.equal(c.h.inboxGroupStatus([{status:'closed',received_at:'2026-09-28T00:00:00Z'},{status:'new',received_at:'2026-09-27T00:00:00Z'}]),'new');assert.equal(c.h.inboxGroupStatus([{status:'closed',received_at:'2026-09-28T00:00:00Z'},{status:'in_progress',received_at:'2026-09-27T00:00:00Z'}]),'in_progress');assert.equal(c.h.inboxGroupStatus([{status:'closed',received_at:'2026-09-27T00:00:00Z'},{status:'converted',received_at:'2026-09-28T00:10:00Z'}]),'converted');assert.equal(c.h.inboxGroupStatus([{status:'converted',received_at:'2026-09-28T00:10:00Z'},{status:'closed',received_at:'2026-09-27T00:00:00Z'}]),'converted');const groups=[{status:'new'},{status:'new'},{status:'in_progress'},{status:'recall_2'},{status:'closed'},{status:'converted'},{status:'unknown'}];assert.deepEqual(JSON.parse(JSON.stringify(c.h.inboxGroupCounts(groups))),{new:2,in_progress:1,recall:1,closed:2,converted:1});const summaryLabels=['NEW 2',String.fromCharCode(51652,54665,51473)+' 1',String.fromCharCode(47532,53084)+' 1',String.fromCharCode(51333,44208)+' 2',String.fromCharCode(51204,54872)+' 1'].join(' '+String.fromCharCode(183)+' ');assert.equal(c.h.inboxStatusSummary(c.h.inboxGroupCounts(groups)),summaryLabels);const rows=[{id:'a',status:'new'},{id:'b',status:'converted'},{id:'c',status:'closed',journal_id:'j1'},{id:'d',status:'in_progress'}];assert.deepEqual(JSON.parse(JSON.stringify(c.h.inboxProcessableRows(rows).map(r=>r.id))),['a','d']);assert.equal(c.h.inboxDisplayName({source:'daangn',message:'💬 중요 메시지 알림 — 가상님 외 1명이 답변을 기다리고 있어요.'}),'가상님 외 1명');assert.equal(c.h.inboxDisplayName({source:'daangn',message:'💬 중요 메시지 알림 — 지민님이 답변을 기다리고 있어요.'}),'지민님');assert.equal(c.h.inboxDisplayName({source:'daangn',sender_name:'진짜이름',message:'💬 중요 메시지 알림 — 가상님 외 1명이 답변을 기다리고 있어요.'}),'진짜이름');});

test('홈 문의함 카드 최근 목록은 상태값을 그대로 넘긴다',()=>{const first=html.match(/\/\* inbox-first:test-start \*\/[\s\S]*?\/\* inbox-first:test-end \*\//)?.[0];const inbox=html.match(/\/\* consultation-inbox:test-start \*\/([\s\S]*?)\/\* consultation-inbox:test-end \*\//)?.[1];assert.ok(first);assert.ok(inbox);const c={};vm.createContext(c);vm.runInContext(`${first};${inbox};this.h={homeInboxRecentRows};`,c);assert.deepEqual(JSON.parse(JSON.stringify(c.h.homeInboxRecentRows([{received_at:'2026-09-28T00:00:00Z',source:'kakao',sender_name:'홍길동',message:'상담 문의',status:'new'}]))),[{receivedAt:'2026-09-28T00:00:00Z',source:'카카오',name:'홍길동',message:'상담 문의',status:'new'}]);});

test('문의함 필터 기본값·재진입 시 선택칸 유지·전환은 최근 처리 대상 줄·휴대폰 카드 마크업이 소스에 있다',()=>{assert.match(html,/let INBOX_FILTER=\{source:'',status:''\}/);assert.match(html,/<option value="" \$\{INBOX_FILTER\.source===''\?'selected':''\}>전체 출처<\/option>/);assert.match(html,/<option value="\$\{x\}" \$\{INBOX_FILTER\.source===x\?'selected':''\}>/);assert.match(html,/<option value="" \$\{INBOX_FILTER\.status===''\?'selected':''\}>전체 상태<\/option>/);assert.match(html,/<option value="new" \$\{INBOX_FILTER\.status==='new'\?'selected':''\}>NEW\(미처리\)<\/option>/);assert.match(html,/<option value="in_progress" \$\{INBOX_FILTER\.status==='in_progress'\?'selected':''\}>진행중<\/option>/);assert.match(html,/<option value="converted" \$\{INBOX_FILTER\.status==='converted'\?'selected':''\}>상담일지 전환<\/option>/);assert.match(html,/<option value="closed" \$\{INBOX_FILTER\.status==='closed'\?'selected':''\}>종결<\/option>/);assert.match(html,/const latest=processable\[processable\.length-1\],otherIds=processable\.slice\(0,-1\)\.map\(row=>row\.id\);/);assert.match(html,/rpc\('consultation_inbox_convert_to_journal',\{p_inbox_id:latest\.id\}\)/);assert.match(html,/class="inbox-mobile-list"/);assert.match(html,/inbox-mobile-card/);assert.match(html,/@media\(max-width:640px\)\{\.inbox-desktop-list\{display:none\}\.inbox-mobile-list\{display:block\}\}/);assert.match(html,/NEW\(미처리\) 문의 \$\{newCount\}건/);assert.match(html,/inboxStatusInfo\(row\.status\)\.className/);});

test('hr.html과 문의함 테스트 파일의 한글이 깨지지 않고 UTF-8로 저장돼 있다',()=>{const replacementChar=Buffer.from([0xEF,0xBF,0xBD]);const hrBuf=fs.readFileSync(path.join(root,'hr.html'));assert.equal(hrBuf.includes(replacementChar),false,'hr.html에 UTF-8 깨짐(교체 문자)이 있습니다.');const selfBuf=fs.readFileSync(__filename);assert.equal(selfBuf.includes(replacementChar),false,'테스트 파일 자체에 UTF-8 깨짐이 있습니다.');assert.match(html,/NEW\(미처리\)/);assert.match(html,/상담일지 전환/);});

test('reply RPC targets the latest processable inbox row and disables when none exist',async()=>{
  const start=html.indexOf('/* consultation-inbox:test-start */'),end=html.indexOf('/* consultation-inbox:test-end */',start),block=html.slice(start,end);assert.ok(start>=0&&end>start);
  const messages=[{id:'processable-old',status:'new',received_at:'2026-09-29T00:00:00Z'},{id:'converted-latest',status:'converted',received_at:'2026-09-29T00:01:00Z'}];
  const c={calls:[],INBOX_SELECTED:null,$:selector=>selector==='#inboxReply'?{value:'\uB2F5\uBCC0'}:selector==='#inboxReplyMsg'?{textContent:''}:null,sb:{rpc:async(name,args)=>{c.calls.push({name,args});return {error:null};}},inboxLoadHistory:async()=>{}};vm.createContext(c);
  vm.runInContext(block+';this.target=inboxReplyTarget;',c);const target=c.target(messages);assert.equal(target.id,'processable-old');c.INBOX_SELECTED={...messages[1],id:target.id,ids:[target.id]};
  const replyFn=html.match(/async function inboxRecordReply\(\)[\s\S]*?(?=async function inboxSave)/)?.[0];assert.ok(replyFn);vm.runInContext(replyFn,c);await c.inboxRecordReply();assert.deepEqual(JSON.parse(JSON.stringify(c.calls)),[{name:'consultation_inbox_record_reply',args:{p_inbox_id:'processable-old',p_reply:'\uB2F5\uBCC0'}}]);
  const noTarget=c.target([{id:'converted',status:'converted'},{id:'journal',status:'new',journal_id:'j1'}]);assert.equal(noTarget,null);assert.match(html,/replyTarget=inboxReplyTarget\(messages\),editable=!!replyTarget/);assert.match(html,/INBOX_SELECTED=\{\.\.\.latest,id:replyTarget\?\.id/);assert.match(html,/\(editable\?'':'disabled'\).*inboxRecordReply\(\)/);
});

test("recall statuses count separately and have selectable filters",()=>{const start=html.indexOf('/* consultation-inbox:test-start */'),end=html.indexOf('/* consultation-inbox:test-end */',start),block=html.slice(start,end);assert.ok(start>=0&&end>start);const c={};vm.createContext(c);vm.runInContext(block+';this.h={inboxGroupCounts,inboxStatusSummary};',c);const groups=['recall_1','recall_2','recall_3'].map(status=>({status}));assert.deepEqual(JSON.parse(JSON.stringify(c.h.inboxGroupCounts(groups))),{new:0,in_progress:0,recall:3,closed:0,converted:0});const summaryLabels=['NEW 0',String.fromCharCode(51652,54665,51473)+' 0',String.fromCharCode(47532,53084)+' 3',String.fromCharCode(51333,44208)+' 0',String.fromCharCode(51204,54872)+' 0'].join(' '+String.fromCharCode(183)+' ');assert.equal(c.h.inboxStatusSummary(c.h.inboxGroupCounts(groups)),summaryLabels);for(const status of ['recall_1','recall_2','recall_3'])assert.match(html,new RegExp('option value="'+status+'"'));assert.match(html,/리콜 = 다시 연락할 문의/);});
test('묶음 상태는 과거 리콜을 최신 종결보다 우선 집계하되 신규·진행중 우선순위와 단일 상태를 유지한다',()=>{const start=html.indexOf('/* consultation-inbox:test-start */'),end=html.indexOf('/* consultation-inbox:test-end */',start),block=html.slice(start,end);assert.ok(start>=0&&end>start);const c={};vm.createContext(c);vm.runInContext(block+';this.h={inboxGroupRows,inboxGroupCounts};',c);const groups=c.h.inboxGroupRows([{id:'old',source:'phone',sender_name:'같은 사람',received_at:'2026-09-30T00:00:00Z',status:'recall_1'},{id:'latest',source:'phone',sender_name:'같은 사람',received_at:'2026-09-30T00:10:00Z',status:'closed'}]);assert.equal(groups.length,1);assert.equal(groups[0].status,'recall_1');assert.deepEqual(JSON.parse(JSON.stringify(c.h.inboxGroupCounts(groups))),{new:0,in_progress:0,recall:1,closed:0,converted:0});const recalls=groups.filter(group=>['recall_1','recall_2','recall_3'].includes(group.status));assert.deepEqual(JSON.parse(JSON.stringify(c.h.inboxGroupCounts(recalls))),{new:0,in_progress:0,recall:1,closed:0,converted:0});assert.equal(c.h.inboxGroupRows([{id:'new',source:'phone',sender_name:'둘',received_at:'2026-09-30T00:00:00Z',status:'new'},{id:'recall',source:'phone',sender_name:'둘',received_at:'2026-09-30T00:10:00Z',status:'recall_1'}])[0].status,'new');assert.equal(c.h.inboxGroupRows([{id:'progress',source:'phone',sender_name:'셋',received_at:'2026-09-30T00:00:00Z',status:'in_progress'},{id:'recall',source:'phone',sender_name:'셋',received_at:'2026-09-30T00:10:00Z',status:'recall_1'}])[0].status,'in_progress');assert.equal(c.h.inboxGroupRows([{id:'recall',source:'phone',sender_name:'넷',received_at:'2026-09-30T00:00:00Z',status:'recall_1'}])[0].status,'recall_1');assert.equal(c.h.inboxGroupRows([{id:'closed',source:'phone',sender_name:'다섯',received_at:'2026-09-30T00:00:00Z',status:'closed'}])[0].status,'closed');});

test('kbook 카카오 예약은 분리되고 합성 카드에서 일정·상품·옵션을 읽으며 원문을 escape한다',()=>{const block=html.match(/\/\* consultation-inbox:test-start \*\/([\s\S]*?)\/\* consultation-inbox:test-end \*\//)?.[1];assert.ok(block);const c={formatLeaveTimestamp:()=> '10/01 09:00'};vm.createContext(c);vm.runInContext(block+';this.h={inboxIsKakaoBooking,inboxKakaoBookingDetails,inboxKakaoBookingListLines};',c);const row={source:'kakao',external_event_id:'kbook-synthetic',received_at:'2026-10-01T00:00:00Z',message:'신규예약 신청\n상품명: 합성 초진\n일정: 2026.10.03(토) 14:00\n옵션: 검진 (1)\n예약자명: 합성 예약자\n예약자 연락처: 01000000000'};assert.equal(c.h.inboxIsKakaoBooking(row),true);assert.equal(c.h.inboxIsKakaoBooking({...row,external_event_id:'kakao-synthetic'}),false);assert.equal(c.h.inboxIsKakaoBooking({...row,source:'naver_email'}),false);const details=JSON.parse(JSON.stringify(c.h.inboxKakaoBookingDetails(row)));assert.equal(details.schedule,'10/03(토) 14:00');assert.equal(details.product,'합성 초진');assert.equal(details.option,'검진 (1)');assert.equal(details.name,'합성 예약자');assert.equal(c.h.inboxKakaoBookingListLines(row).bottom,'합성 초진 · 검진 (1)');const unknown={...row,message:'예약 변경 알림\n<img src=x onerror=alert(1)>'};assert.equal(c.h.inboxKakaoBookingDetails(unknown).recognized,false);assert.equal(c.h.inboxKakaoBookingListLines(unknown).bottom,'예약 변경 알림');assert.match(html,/if\(messages.length===1&&inboxIsKakaoBooking\(latest\)\)/);assert.match(html,/esc\(row.message\|\|''\)/);assert.match(html,/https:\/\/partner-booking\.kakao\.com\//);});


test('예약 전용 필터는 모바일 2열로 배치되어 가로로 넘치지 않는다',()=>{assert.match(html,/id="inboxFilterRow" class="rowflex inbox-filter-row"/);assert.match(html,/\.inbox-filter-row\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.match(html,/\.inbox-filter-row #inboxReservationFilter\{grid-column:1\/-1\}/);assert.match(html,/\.inbox-mobile-card \.inbox-booking-line\{align-items:flex-start;flex-direction:column\}/);assert.match(html,/if\(INBOX_ONLY_RESERVATIONS\)q=q\.eq\('source','kakao'\)\.like\('external_event_id','kbook-%'\)/);});
