import assert from 'node:assert/strict';
import fs from 'node:fs';

const sql = fs.readFileSync('db/monthly_leave_accrual_draft.sql', 'utf8');
assert.match(sql, /create table if not exists public\.leave_accrual_runs/);
assert.match(sql, /unique \(user_id,due_date\)/);
assert.match(sql, /p\.profile_hire_date \+ make_interval\(months\s*=>\s*n\)/);
assert.match(sql, /p\.profile_hire_date \+ interval '1 year' \+ interval '1 day'/);
assert.match(sql, /accrual_kind text not null default 'monthly'/);
assert.match(sql, /months_completed between 1 and 12/);
assert.match(sql, /target_days numeric\(3,1\)/);
assert.match(sql, /accrual_kind='annual' and months_completed=12 and target_days=15/);
assert.match(sql, /26::numeric as milestone_cumulative_due_days/);
assert.match(sql, /attendance_confirmed_by uuid/);
assert.match(sql, /coalesce\(sum\(case when ll\.kind in \('부여','조정'\) then ll\.days else 0 end\),0\)/);
assert.match(sql, /language plpgsql security invoker/);
assert.doesNotMatch(sql, /language plpgsql security definer/);
assert.match(sql, /coalesce\(public\.my_role\(\),''\)<>\'owner\'/);
assert.match(sql, /explicit apply confirmation required; preview only/);
assert.match(sql, /full_attendance/);
assert.match(sql, /p_apply_confirmed boolean/);
assert.match(sql, /grant select,insert on table public\.leave_accrual_runs to authenticated/);
assert.match(sql, /create policy leave_accrual_runs_insert_owner[\s\S]*?for insert to authenticated[\s\S]*?with check/);
assert.match(sql, /grant usage,select on sequence public\.leave_accrual_runs_id_seq to authenticated/);
assert.match(sql, /language plpgsql security invoker/);
assert.match(sql, /revoke all on function public\.apply_monthly_leave_accruals\(date\) from public,anon/);
assert.match(sql, /revoke all on function public\.apply_monthly_leave_accruals\(date,jsonb,boolean\) from public,anon/);
assert.match(sql, /insert into public\.leave_ledger/);
assert.doesNotMatch(sql, /auth\.role\s*\(/);
console.log('MONTHLY_LEAVE_STATIC_PASS: 월말·퇴사·1주년 다음 날 별도 15일·수기상계·명시확인 적용 경계');
