import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const sql = fs.readFileSync('db/monthly_leave_accrual_draft.sql', 'utf8');
const html = fs.readFileSync('hr.html', 'utf8');
const rollback = fs.readFileSync('db/monthly_leave_accrual_safe_rollback.sql', 'utf8');
assert.match(sql, /create table if not exists public\.leave_accrual_runs/);
assert.match(sql, /unique \(user_id,due_date\)/);
assert.match(sql, /p\.profile_hire_date \+ make_interval\(months\s*=>\s*n\)/);
assert.match(sql, /p\.profile_hire_date \+ make_interval\(years => n\)/);
assert.match(sql, /p_as_of>\(now\(\) at time zone 'Asia\/Seoul'\)::date/);
assert.match(sql, /accrual_kind text not null default 'monthly'/);
assert.match(sql, /months_completed between 1 and 12/);
assert.match(sql, /target_days numeric\(3,1\)/);
assert.match(sql, /accrual_kind='annual' and months_completed=12 and target_days=15/);
assert.match(sql, /\(11 \+ 15\*n\)::numeric as milestone_cumulative_due_days/);
assert.match(sql, /milestone_due_date<m\.profile_employment_effective_date/);
assert.match(sql, /past boolean/);
assert.match(sql, /attendance_confirmed_by uuid/);
assert.match(sql, /coalesce\(sum\(case when ll\.kind in \('부여','조정'\) then ll\.days else 0 end\),0\)/);
assert.match(sql, /language plpgsql security invoker/);
assert.doesNotMatch(sql, /language plpgsql security definer/);
assert.match(sql, /coalesce\(public\.my_role\(\),''\)<>\'owner\'/);
assert.match(sql, /explicit apply confirmation required; preview only/);
assert.match(sql, /full_attendance/);
assert.match(sql, /p_apply_confirmed boolean/);
assert.match(sql, /grant select,insert on table public\.leave_accrual_runs to authenticated/);
assert.match(sql, /create policy leave_accrual_runs_insert_owner[\s\S]*?for insert to authenticated[\s\S]*?with check/);
assert.match(sql, /grant usage,select on sequence public\.leave_accrual_runs_id_seq to authenticated/);
assert.match(sql, /language plpgsql security invoker/);
assert.match(sql, /revoke all on function public\.apply_monthly_leave_accruals\(date\) from public,anon/);
assert.match(sql, /revoke all on function public\.apply_monthly_leave_accruals\(date,jsonb,boolean\) from public,anon/);
assert.match(sql, /insert into public\.leave_ledger/);
assert.doesNotMatch(sql, /auth\.role\s*\(/);
assert.match(html,/const accrualHtml=ME\.role==='owner'/);
assert.match(html,/async function previewLeaveAccrual\(\)[\s\S]*?sb\.rpc\('preview_monthly_leave_accruals',\{p_as_of:asOf\}\)/);
assert.match(html,/async function applyLeaveAccrual\(\)[\s\S]*?if\(!confirm\([\s\S]*?sb\.rpc\('apply_monthly_leave_accruals',\{p_as_of:LEAVE_ACCRUAL_AS_OF,p_attendance_confirmations:confirmations,p_apply_confirmed:true\}\)/);
assert.match(html,/LEAVE_ACCRUAL_AS_OF=asOf;LEAVE_ACCRUAL_PREVIEW=data\|\|\[\]/);
assert.match(html,/r\.past\?' <span class="sub">· 지난 발생분<\/span>':''/);
assert.match(html,/r&&!r\.already_recorded/);
assert.match(rollback,/automatic leave accrual paused; preview only/);
assert.doesNotMatch(rollback,/\b(delete|truncate|drop table|update public\.leave_ledger)\b/i);
const flow=html.slice(html.indexOf('async function previewLeaveAccrual(){'),html.indexOf('/* ── 결재함'));
const elements={laAsOf:{value:'2026-09-25'},laMsg:{textContent:''},laRows:{innerHTML:'',querySelectorAll:()=>[{dataset:{laIndex:'0'}}]},laApply:{disabled:true},main:{}};
const events=[];
let approved=false;
const context={ME:{role:'owner'},LEAVE_ACCRUAL_GENERATION:0,LEAVE_ACCRUAL_PREVIEW:[],LEAVE_ACCRUAL_AS_OF:'',today:()=> '2026-09-25',esc:String,$:selector=>elements[selector.slice(1)],setStatus:()=>{},confirm:()=>{events.push('confirm');return approved;},render:async()=>{events.push('render');},sb:{rpc:async name=>{events.push(name);return name==='preview_monthly_leave_accruals'?{data:[{user_id:'staff',user_name:'직원',hire_date:'2026-08-18',due_date:'2026-09-18',accrual_kind:'monthly',target_days:1,existing_credit_days:0,grant_days:1,past:true,already_recorded:false}]}:{data:[{granted_days:1}]};}}};
vm.runInNewContext(`${flow}\nthis.preview=previewLeaveAccrual;this.apply=applyLeaveAccrual;`,context);
await context.preview();
assert.equal(elements.laApply.disabled,false);
assert.match(elements.laRows.innerHTML,/지난 발생분/);
elements.laAsOf.value='2026-09-24';await context.apply();
assert.deepEqual(events,['preview_monthly_leave_accruals']);
elements.laAsOf.value='2026-09-25';await context.apply();
assert.deepEqual(events,['preview_monthly_leave_accruals','confirm']);
approved=true;await context.apply();
assert.deepEqual(events,['preview_monthly_leave_accruals','confirm','confirm','apply_monthly_leave_accruals','render','preview_monthly_leave_accruals']);
console.log('MONTHLY_LEAVE_STATIC_PASS: 월말·퇴사·입사 기념일별 연 15일·과거분 표시·수기상계·명시확인 적용 경계');
