const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(process.env.P7_HTML_UNDER_TEST||'hr.html','utf8');
const start=html.indexOf('async function submitPaymentRequest('),end=html.indexOf('\nasync function paymentRequestAct(',start);
function setup(){const calls=[],file={name:'receipt.pdf',type:'application/pdf',size:10},fields={'#paymentMsg':{textContent:''},'#paymentItem':{value:'구매'},'#paymentAmount':{value:'1000'},'#paymentBank':{value:'은행'},'#paymentHolder':{value:'직원'},'#paymentAccount':{value:'123'},'#paymentDeadline':{value:''},'#paymentFiles':{files:[file]}};let failUpload=true,failLink=false;const ctx={PAYMENT_REQUEST_RETRY:null,PAYMENT_REQUEST_SUBMITTING:false,$:id=>fields[id],ME:{id:'staff'},crypto:{randomUUID:()=>String(calls.length)},validateGeneralDocument:()=>null,hubT:(k,d,v)=>v?d.replace('{detail}',v.detail):d,setStatus:s=>calls.push(['status',s]),render:()=>calls.push(['render']),sb:{rpc:async(name,args)=>{calls.push([name,args]);if(name==='submit_payment_request')return {data:42,error:null};return {data:1,error:failLink?{message:'link failed'}:null};},storage:{from:()=>({upload:async(path)=>{calls.push(['upload',path]);return {error:failUpload?{message:'upload failed'}:null};},remove:async(paths)=>{calls.push(['remove',paths]);return {error:null};}})}}};vm.createContext(ctx);vm.runInContext(html.slice(start,end),ctx);return {ctx,calls,fields,file,setUpload:v=>failUpload=v,setLink:v=>failLink=v};}
test('영수증 업로드 실패 후 재시도는 같은 요청 번호를 재사용한다',async()=>{const s=setup();await s.ctx.submitPaymentRequest();s.setUpload(false);await s.ctx.submitPaymentRequest();assert.equal(s.calls.filter(c=>c[0]==='submit_payment_request').length,1);assert.equal(s.calls.find(c=>c[0]==='payment_request_add_receipt')[1].p_request_id,42);assert.ok(s.calls.some(c=>c[0]==='render'));});
test('연결 실패 후 재시도도 같은 요청을 사용하고 이미 연결한 영수증은 지우지 않는다',async()=>{const s=setup();s.setUpload(false);s.fields['#paymentFiles'].files.push({...s.file,name:'second.pdf'});let links=0;s.ctx.sb.rpc=async(name,args)=>{s.calls.push([name,args]);if(name==='submit_payment_request')return {data:42,error:null};links++;return {data:1,error:links===2?{message:'second link failed'}:null};};await s.ctx.submitPaymentRequest();await s.ctx.submitPaymentRequest();assert.equal(s.calls.filter(c=>c[0]==='submit_payment_request').length,1);assert.equal(s.calls.filter(c=>c[0]==='payment_request_add_receipt'&&c[1].p_original_name==='receipt.pdf').length,1);const first=s.calls.find(c=>c[0]==='payment_request_add_receipt')[1].p_storage_path;assert.ok(s.calls.filter(c=>c[0]==='remove').every(c=>!c[1].includes(first)));});
test('요청 저장 중 연속 클릭은 요청을 중복 생성하지 않는다',async()=>{const s=setup();s.setUpload(false);await Promise.all([s.ctx.submitPaymentRequest(),s.ctx.submitPaymentRequest()]);assert.equal(s.calls.filter(c=>c[0]==='submit_payment_request').length,1);});
test('예외가 나도 재시도 잠금은 풀리고 같은 요청 번호를 유지한다',async()=>{const s=setup();s.ctx.sb.storage.from=()=>({upload:async()=>{throw Error('network');}});await s.ctx.submitPaymentRequest();assert.equal(s.ctx.PAYMENT_REQUEST_SUBMITTING,false);assert.equal(s.ctx.PAYMENT_REQUEST_RETRY.id,42);assert.match(s.fields['#paymentMsg'].textContent,/network/);});
test('저장 후 화면 갱신 실패를 다시 눌러도 새 요청·영수증을 만들지 않는다',async()=>{const s=setup();s.setUpload(false);s.ctx.render=async()=>{throw Error('render failed');};await s.ctx.submitPaymentRequest();s.ctx.render=async()=>{};await s.ctx.submitPaymentRequest();assert.equal(s.calls.filter(c=>c[0]==='submit_payment_request').length,1);assert.equal(s.calls.filter(c=>c[0]==='payment_request_add_receipt').length,1);assert.equal(s.ctx.PAYMENT_REQUEST_RETRY,null);});
