const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('hr.html','utf8');
const sql=fs.readFileSync('db/payment_requests_draft.sql','utf8');
const rollback=fs.readFileSync('db/payment_requests_rollback.sql','utf8');
const receiptSelect=fs.readFileSync('db/payment_receipts_select_own_folder.sql','utf8');
const receiptSelectRollback=fs.readFileSync('db/payment_receipts_select_own_folder_rollback.sql','utf8');

assert.match(html,/paymentRequestCard\(/,'서류함에 결제 요청 카드가 있어야 합니다.');
assert.match(html,/결제 요청/,'직원이 서류함에서 결제 요청을 시작할 수 있어야 합니다.');
assert.match(html,/submit_payment_request/,'민감 필드는 RPC로만 접수해야 합니다.');
assert.match(html,/payment-receipts/,'영수증은 전용 비공개 Storage 버킷을 써야 합니다.');
assert.match(html,/payment_request_add_receipt/,'업로드한 영수증은 서버에서 요청에 연결해야 합니다.');
assert.match(html,/payment_request_act/,'실장·원장 결재는 서버 상태전이여야 합니다.');
assert.match(html,/<th>결제마감일<\/th><th>입금계좌<\/th>/,'결재선은 마감일과 계좌를 확인할 수 있어야 합니다.');
assert.match(html,/r\.bank_name,r\.account_holder,r\.account_number/,'계좌의 은행·예금주·번호를 결제 요청 행에 표시해야 합니다.');
assert.match(html,/r\.deadline_date\|\|'-'/,'마감일 없는 요청도 안전하게 표시해야 합니다.');
assert.match(sql,/create table if not exists public\.payment_requests/i);
assert.match(sql,/create table if not exists public\.payment_request_receipts/i);
assert.match(sql,/create table if not exists public\.payment_request_actions/i);
assert.match(sql,/create or replace function public\.submit_payment_request/i);
assert.match(sql,/create or replace function public\.payment_request_act/i);
assert.match(sql,/chief_pending.*owner_pending.*approved.*rejected/is);
assert.match(sql,/v_role='chief'/);
assert.match(sql,/v_role='owner'/);
assert.match(sql,/requester_id=auth\.uid\(\).*public\.my_role\(\) in \('chief','owner'\)/is,'본인과 결재선만 민감 요청을 읽어야 합니다.');
assert.match(sql,/bucket_id='payment-receipts'/);
assert.equal((receiptSelect.match(/drop policy/gi)||[]).length,1,'new SQL drops exactly one policy');
assert.equal((receiptSelect.match(/create policy/gi)||[]).length,1,'new SQL creates exactly one policy');
assert.match(receiptSelect,/drop policy if exists payment_receipts_select_approval_line on storage\.objects/i);
assert.match(receiptSelect,/create policy payment_receipts_select_approval_line on storage\.objects for select to authenticated using/i);
assert.match(receiptSelect,/split_part\(name,'\/',1\)=auth\.uid\(\)::text/i,'own-folder access is present');
assert.match(receiptSelect,/payment_request_receipts r join public\.payment_requests p/i,'existing linked-request access is preserved');
assert.doesNotMatch(receiptSelectRollback,/split_part\(name,'\/',1\)=auth\.uid\(\)::text/i,'rollback restores linked-only access');
const policyStatement=text=>text.match(/create policy payment_receipts_select_approval_line[\s\S]*?;/i)?.[0]?.replace(/\s+/g,' ').trim().toLowerCase();
assert.equal(policyStatement(sql),policyStatement(receiptSelect),'draft SELECT policy matches standalone migration');
assert.match(sql,/payment_request_receipts.*storage_path/is,'첨부 조회도 결재선 범위여야 합니다.');
assert.match(sql,/from storage\.objects o where o\.bucket_id='payment-receipts' and o\.name=p_storage_path and o\.owner_id=auth\.uid\(\)::text/is,'실제 Storage owner_id(text)와 인증 UUID를 같은 타입으로 대조해야 합니다.');
assert.match(sql,/o\.metadata->>'size'\)::bigint,-1\)=p_size_bytes/is,'영수증 연결 전 실제 Storage 객체 크기를 대조해야 합니다.');
assert.match(sql,/revoke all on table public\.payment_requests from public, anon, authenticated/i);
assert.match(sql,/grant select on table public\.payment_requests,public\.payment_request_receipts,public\.payment_request_actions to authenticated/i);
assert.match(rollback,/payment_requests contains data; rollback stopped/i);
const paymentCardSource=html.match(/function paymentRequestCard\([\s\S]*?\n(?=async function submitPaymentRequest)/)?.[0];
assert.ok(paymentCardSource,'결제 요청 카드를 검증할 수 있어야 합니다.');
const paymentCardContext={ME:{role:'staff'},esc:v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'),paymentRequestCanAct:()=>false,paymentRequestStatusLabel:()=>'',PAYMENT_RECEIPT_PREVIEWS:[]};
vm.createContext(paymentCardContext);vm.runInContext(paymentCardSource+';this.paymentRequestCard=paymentRequestCard;',paymentCardContext);
const maliciousReceipt=paymentCardContext.paymentRequestCard([{id:1,payment_item:'결제',amount_krw:1,status:'chief_pending'}],null,[{request_id:1,storage_path:"staff/1/a' onclick='alert(1)",original_name:"x'</button><img src=x onerror=alert(1)>",mime_type:'text/plain'}],null);
assert.doesNotMatch(maliciousReceipt,/onclick="previewStorageAttachment/,'사용자 파일명·경로를 onclick 문자열로 넣으면 안 됩니다.');
assert.match(maliciousReceipt,/data-payment-receipt-index="0"/,'미리보기 버튼은 검증된 숫자 인덱스만 HTML 속성에 넣어야 합니다.');
assert.match(maliciousReceipt,/&lt;img src=x onerror=alert\(1\)&gt;/,'악성 파일명은 텍스트로만 표시해야 합니다.');
console.log('PAYMENT_REQUESTS_ACCEPTANCE_PASS');
