const test=require('node:test'),assert=require('node:assert/strict'),p=require('../payroll-compare.js');
test('허용치 경계는 같으면 통과·넘으면 차이; 시간·분 단위를 맞춘다',()=>{assert.equal(p.payrollCompareCell(1,1.1,0.1).different,false);assert.equal(p.payrollCompareCell(1,1.11,0.1).different,true);assert.equal(p.payrollCompareCell(null,0,0).different,false);assert.equal(p.payrollCompareCell(0,0,0).different,false);assert.equal(p.payrollCompareCell(1,0,0).different,true);const m={monthly:[{userId:'u',name:'합성',overtime:1,overtimeOnly:1,late:0.25,early:0.25,holiday:8,holidayOvertime:0.17,bonus:100}],hourly:[]};const r=p.payrollComparisonModel(m,[{user_id:'u',items:{bonus:100},side:{'OT시간(시간)':1.1,'근태횟수(시간)':0.5,'휴일근로(시간)':8,'휴일연장(분)':10}}],[],{timeTolerance:0.1,moneyTolerance:0});assert.ok(r.rows[0].cells.every(c=>!c.different));});
test('노무사 대장이 없으면 한 줄 안내; 비교는 입력을 고치지 않는다',()=>{const m={monthly:[],hourly:[]},before=JSON.stringify(m),r=p.payrollComparisonModel(m,[],[],{});assert.equal(r.noLedger,true);assert.equal(JSON.stringify(m),before);});
test('시급제 4칸은 회신과 같은 허브 계산값을 비교하고 근거 없는 대장 칸을 0으로 만들지 않는다',()=>{const reply={monthly:[],hourly:[{userId:'u',name:'합성시급',weekdayWork:8,weekdayOver:0.5,weekendWork:2,weekendOver:0}]};const r=p.payrollComparisonModel(reply,[],[{source_sheet:'일용대장',user_id:'u',side:{'평일근무':8,'평일오버':1,'주말근무':2}}],{});assert.equal(r.rows[0].cells[1].different,true);assert.equal(r.rows[0].cells[3].ledger,null);});

test('휴일 8시간은 연장 대조에서 제외하고 회신 엑셀에는 합쳐서 유지한다',()=>{const reply=require('../payroll-reply.js'),m={month:'2026-09',employees:[{userId:'u',name:'가짜휴일직원',summary:{overtimeMinutes:630,lateMinutes:0,earlyMinutes:0},days:[{date:'2026-09-01',clockIn:'09:00',clockOut:'17:00',holidayMinutes:480}]}]};const r=reply.payrollReplyModel(m,[{user_id:'u',effective_from:'2026-01-01',inclusive_overtime_hours:10}],[],['2026-09-01'],{});const c=p.payrollComparisonModel(r,[{user_id:'u',side:{'OT시간(시간)':0.5,'휴일근로(시간)':8}}]);assert.equal(c.rows[0].cells.find(c=>c.key==='overtime').hub,0.5);assert.equal(c.rows[0].cells.find(c=>c.key==='overtime').different,false);assert.equal(c.rows[0].cells.find(c=>c.key==='holiday').hub,8);assert.equal(reply.payrollReplyWorkbook(r).sheets[0].rows[1][5],8.5);});

test('대조 상여 세 칸은 쉼표·0원·음수 표시, 시간은 숫자 그대로',()=>{const fs=require('node:fs'),vm=require('node:vm'),c={bonusOwner:()=>true,hubT:(k,d)=>d,esc:String};vm.createContext(c);vm.runInContext(fs.readFileSync('payroll-compare.js','utf8'),c);const m={noLedger:false,rows:[{name:'가짜',cells:[p.payrollCompareCell(2000000,1000000,0),p.payrollCompareCell(0,0,0),p.payrollCompareCell(1000,1000.5,1)].map((v,i)=>({...v,key:i===2?'overtime':'bonus'}))}]};const html=c.payrollComparisonHtml(m);assert.ok(html.includes('<td>2,000,000</td><td>1,000,000</td>'));assert.ok(html.includes('>-1,000,000</td>'));assert.ok(html.includes('<td>0</td><td>0</td>'));assert.ok(html.includes('<td>1000</td><td>1000.5</td>'));});

test('미확정 상여는 대조 허브·차이에 미확정 표시, 확정 뒤 금액과 차이를 표시',()=>{
 const vm=require('node:vm'),fs=require('node:fs'),reply=require('../payroll-reply.js'),source={month:'2026-09',employees:[{userId:'u',name:'합성',days:[{date:'2026-09-01',clockIn:'09:00',clockOut:'18:00'}]}]},entry={month:'2026-09',user_id:'u',amount:100,confirmed:false},ledger=[{user_id:'u',items:{bonus:200}}];
 const c={bonusOwner:()=>true,hubT:(k,d)=>d,esc:String};vm.createContext(c);vm.runInContext(fs.readFileSync('payroll-compare.js','utf8'),c);
 let model=p.payrollComparisonModel(reply.payrollReplyModel(source,[],[entry]),ledger),cell=model.rows[0].cells.find(r=>r.key==='bonus');assert.equal(cell.unconfirmed,true);assert.equal(cell.diff,null);assert.equal(cell.different,false);let html=c.payrollComparisonHtml(model);assert.match(html,/<td>200<\/td><td>미확정<\/td>/);assert.doesNotMatch(html,/NaN/);
 model=p.payrollComparisonModel(reply.payrollReplyModel(source,[],[{...entry,confirmed:true}]),ledger);cell=model.rows[0].cells.find(r=>r.key==='bonus');assert.equal(cell.hub,100);assert.equal(cell.diff,-100);assert.equal(cell.different,true);
});
