const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function settings(){const js=fs.readFileSync('hub-texts.js','utf8'),block=js.match(/\/\* hub-texts:test-start \*\/[\s\S]*?\/\* hub-texts:test-end \*\//)[0],c={HUB_BONUS_CATALOG:true};vm.createContext(c);vm.runInContext(block+';this.api={hubTextDefs,hubTextSetOverrides,hubText,hubSettingSetValues,hubSettingChecked,hubList,HUB_SETTING_DEFS,HUB_LIST_DEFS};',c);return c.api;}
test('실제 상여 스크립트 선행 로드로 글·숫자·목록이 허브 설정에 등록된다',()=>{const h=settings(),hr=fs.readFileSync('hr.html','utf8');assert.ok(hr.indexOf('src="payroll-bonus.js')<hr.indexOf('src="hub-texts.js'));for(const key of ['pay.bonus.amount','pay.extra.saved','pay.reply.rule_overtime','pay.reply.inclusive_missing','pay.compare.tab'])assert.ok(h.hubTextDefs().some(d=>d.key===key),key);for(const key of ['pay.bonus.months','pay.reply.digits','pay.reply.night_start','pay.reply.night_end','pay.reply.deadline','pay.reply.payday','pay.compare.time_tolerance','pay.compare.money_tolerance'])assert.ok(h.HUB_SETTING_DEFS.some(d=>d.key===key),key);assert.ok(h.HUB_LIST_DEFS.some(d=>d.key==='list.pay_bonus_kinds'));});

test('확정·기본값·CSV·미확정 회신 글은 중복 없는 편집 목록이고 변경 JS 캐시는 7차임',()=>{
 const h=settings(),defs=h.hubTextDefs(),hr=fs.readFileSync('hr.html','utf8');
 for(const key of ['pay.bonus.unconfirmed','pay.bonus.confirmed','pay.bonus.confirm','pay.bonus.confirm_all','pay.bonus.confirmation_summary','pay.bonus.defaults','pay.bonus.default_amount','pay.bonus.import','pay.bonus.import_apply','pay.bonus.import_result','pay.reply.bonus_unconfirmed','pay.reply.bonus_review','pay.reply.hourly_correction_basis','pay.compare.bonus_unconfirmed'])assert.equal(defs.filter(d=>d.key===key).length,1,key);
 for(const name of ['payroll-bonus','payroll-reply','payroll-compare','hub-texts'])assert.ok(hr.includes(name+'.js?v=2026101007'),name);
 h.hubTextSetOverrides([{key:'pay.bonus.confirm',value:'확정하기'},{key:'pay.bonus.defaults',value:'제안 기준'},{key:'pay.bonus.import_result',value:'입력 {inserted} · 제외 {skipped}'}]);
 assert.equal(h.hubText('pay.bonus.confirm','저장(확정)'),'확정하기');assert.equal(h.hubText('pay.bonus.import_result','',{inserted:2,skipped:1}),'입력 2 · 제외 1');
});
test('새 글·숫자·종류 이름을 원장이 고치면 엔진이 읽고 위험한 값은 기본값으로 돌아간다',()=>{const h=settings();h.hubTextSetOverrides([{key:'pay.bonus.amount',value:'수정한 상여'},{key:'pay.reply.rule_time',value:'소수 {digits} 자리 사용'}]);assert.equal(h.hubText('pay.bonus.amount','세후 상여'),'수정한 상여');assert.equal(h.hubText('pay.reply.rule_time','기본',{digits:3}),'소수 3 자리 사용');h.hubSettingSetValues({'pay.bonus.months':'5','pay.compare.time_tolerance':'0.2','pay.reply.deadline':'100','list.pay_bonus_kinds':JSON.stringify([{code:'amount',label:'원화'},{code:'points',label:'점수'}])});assert.equal(h.hubSettingChecked('pay.bonus.months',3),5);assert.equal(h.hubSettingChecked('pay.compare.time_tolerance',0.1),0.2);assert.equal(h.hubSettingChecked('pay.reply.deadline',3),3);assert.equal(h.hubList('list.pay_bonus_kinds',[])[0].label,'원화');});
test('돈·평가의 항목명·값·배점 단가는 원장 전용 표에만 저장한다',()=>{const js=fs.readFileSync('payroll-bonus.js','utf8');assert.match(js,/from\('bonus_criteria'\)\.upsert/);assert.match(js,/from\('bonus_entries'\)\.upsert/);assert.doesNotMatch(js,/from\('(app_settings|hub_ui_texts)'\)\.(upsert|insert|update)/);const h=settings();assert.ok(!h.HUB_SETTING_DEFS.some(d=>d.key==='pay.bonus.point_rate'));});
