const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),test=require('node:test');
const html=fs.readFileSync('hr.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),sql=fs.readFileSync('db/push_subscriptions_draft.sql','utf8'),rollback=fs.readFileSync('db/push_subscriptions_rollback.sql','utf8');
for(const [v,re,msg] of [[html,/pushNotificationCard\(/,'카드'],[html,/PUSH_VAPID_PUBLIC_KEY/,'VAPID 보호'],[html,/\.eq\('endpoint',subscription\.endpoint\)/,'현재 endpoint 삭제'],[sw,/addEventListener\('push'/,'push'],[sw,/addEventListener\('notificationclick'/,'click'],[sw,/new URL\(/,'origin 방어'],[sql,/constraint push_subscriptions_endpoint_key unique\(user_id,endpoint\)/i,'user별 endpoint UNIQUE'],[sql,/subscription->>'endpoint'=endpoint/i,'JSON endpoint'],[sql,/migration object collision; preserve state and stop/i,'apply fail-closed'],[rollback,/push subscription ownership manifest or schema snapshot mismatch; preserve state and stop rollback/i,'rollback fail-closed']])assert.match(v,re,msg);
function worker(){const events={},shown=[],opened=[],self={location:{origin:'https://jung-plant.com'},registration:{showNotification:async(...x)=>shown.push(x)},clients:{claim:async()=>{},matchAll:async()=>[]},skipWaiting(){},addEventListener:(n,f)=>events[n]=f};const c={self,clients:{matchAll:self.clients.matchAll,openWindow:async u=>opened.push(u)},fetch:async()=>{},Response,URL};vm.runInNewContext(sw,c);return{events,shown,opened,c};}
test('SW payload와 URL을 fail-closed로 정규화한다',async()=>{const x=worker(),wait=[];x.events.push({data:{json:()=>({url:'https://evil.example/a',title:'x'.repeat(201),body:{x:1}})},waitUntil:p=>wait.push(p)});await Promise.all(wait);assert.equal(x.shown[0][0].length,200);assert.equal(x.shown[0][1].body,'새 알림이 있습니다.');assert.equal(x.shown[0][1].data.url,'https://jung-plant.com/hr.html');const y=worker(),w=[];y.events.push({data:{json:()=>{throw Error('bad')}},waitUntil:p=>w.push(p)});await Promise.all(w);assert.equal(y.shown[0][1].data.url,'https://jung-plant.com/hr.html');});
test('SW click은 동일 origin hr 창만 focus한다',async()=>{const x=worker(),w=[],focused=[];x.c.clients.matchAll=async()=>[{url:'https://evil.example/hr.html',focus:async()=>focused.push('evil')},{url:'https://jung-plant.com/hr.html?x=1',focus:async()=>focused.push('ok')}];x.events.notificationclick({notification:{data:{url:'https://evil.example'},close(){}},waitUntil:p=>w.push(p)});await Promise.all(w);assert.deepEqual(focused,['ok']);assert.deepEqual(x.opened,[]);});
function ui(subscription,errors=[]){let text='',calls=[];const eq=(k,v)=>{calls.push([k,v]);return k==='endpoint'?Promise.resolve({error:errors.shift()||null}):{eq}};const c={navigator:{serviceWorker:{ready:Promise.resolve({pushManager:{getSubscription:async()=>subscription}})}},$:()=>({set textContent(v){text=v}}),ME:{id:'me'},sb:{from:()=>({delete:()=>({eq})})}};vm.runInNewContext(html.match(/async function unsubscribePushNotifications\(\)\{[\s\S]*?\n(?=function renderWorkDocuments)/)[0],c);return{run:()=>c.unsubscribePushNotifications(),get text(){return text},calls};}
test('UI는 현재 endpoint만 삭제하며 DB 실패 뒤 재시도에서만 browser 해제한다',async()=>{let unsub=0;const a=ui({endpoint:'https://push/a',unsubscribe:async()=>{unsub++;return true}},[{message:'DB'}]);await a.run();assert.equal(unsub,0);assert.match(a.text,/구독은 유지/);await a.run();assert.equal(unsub,1);assert.deepEqual(a.calls,[['user_id','me'],['endpoint','https://push/a'],['user_id','me'],['endpoint','https://push/a']]);assert.match(a.text,/해제했습니다/);const b=ui(null);await b.run();assert.deepEqual(b.calls,[]);assert.match(b.text,/일괄 삭제하지 않았습니다/);});
console.log('PUSH_NOTIFICATIONS_STATIC_AND_VM_PASS');
