const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('hr.html','utf8'),texts=fs.readFileSync('hub-texts.js','utf8');
const pure=html.match(/\/\* recall-list:test-start \*\/([\s\S]*?)\/\* recall-list:test-end \*\//)[1];
function context(extra={}){const c={inboxT:(k,d,v)=>String(d).replace(/\{([a-z_]+)\}/g,(m,k)=>v?.[k]??m),esc:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),inboxSourceLabel:x=>x,inboxFormatContact:x=>x,nameOf:x=>x,formatLeaveTimestamp:x=>x,canManageConsultation:()=>true,...extra};vm.createContext(c);vm.runInContext(pure+';this.h={recallCanAccess,recallGroupRows,recallCounts,recallFilterRows,recallRowsHtml};',c);return c;}
const data=[{kind:'inbox',id:'a',name:'가짜 이름',contact:'01012345678',source:'phone',stage:'recall_1',due_on:'2026-10-08',assigned_to:'m',memo:'메모',last_contact_at:'2026-10-01T00:00:00Z',message:'절대 표시되면 안 될 문자 원문'},{kind:'journal',id:'j',name:'같은 사람',contact:'010-1234-5678',source:'journal',stage:'journal',due_on:'2026-10-07',assigned_to:'c',memo:'최근 상담 연락',last_contact_at:'2026-10-02T00:00:00Z'},{kind:'inbox',id:'b',name:'오늘 사람',contact:'01000000000',source:'manual',stage:'recall_3',due_on:'2026-10-08',assigned_to:'m'},{kind:'inbox',id:'c',name:'미정',contact:null,stage:'recall_1',due_on:null},{kind:'journal',id:'k',name:'미정',contact:null,stage:'journal',due_on:'2026-10-10'}];
test('리콜은 문의함 하위 화면이며 데스크·관리자만 접근한다',()=>{const c=context();for(const role of ['owner','manager','chief'])assert.equal(c.h.recallCanAccess({role}),true);assert.equal(c.h.recallCanAccess({role:'staff',department:'데스크'}),true);assert.equal(c.h.recallCanAccess({role:'staff',department:'진료실'}),false);assert.equal(c.h.recallCanAccess({role:'anon'}),false);assert.match(html,/recallTabsHtml\(\)\+inboxCardFill/);assert.match(html,/if\(INBOX_SUBTAB==='recall'&&recallEnabled\(\)\)/);});
test('같은 연락처 문의·상담을 한 사람으로 묶고 빠른 예정일과 최근 메모를 표시한다',()=>{const c=context(),rows=c.h.recallGroupRows(data);assert.equal(rows.length,4);assert.equal(rows[0].rows.length,2);assert.equal(rows[0].due_on,'2026-10-07');assert.equal(rows[0].memo,'최근 상담 연락');assert.equal(rows[rows.length-1].due_on,null);});
test('오늘·기한 지난 인원은 사람 단위이고 필터가 묶음 안 모든 행에 적용된다',()=>{const c=context(),rows=c.h.recallGroupRows(data);assert.deepEqual(JSON.parse(JSON.stringify(c.h.recallCounts(rows,'2026-10-08'))),{today:1,overdue:1});assert.equal(c.h.recallFilterRows(rows,{stage:'journal'},'m','2026-10-08').length,2);assert.equal(c.h.recallFilterRows(rows,{assignee:'c',overdue:true},'m','2026-10-08').length,1);assert.equal(c.h.recallFilterRows(rows,{mine:true},'m','2026-10-08').length,2);});
test('오늘·지난 사람의 줄은 빨갛고 문자 원문을 넣지 않으며 메모와 이름을 이스케이프한다',()=>{const c=context(),markup=c.h.recallRowsHtml(c.h.recallGroupRows(data),'2026-10-08');assert.equal((markup.match(/class="recall-row recall-due"/g)||[]).length,2);assert.doesNotMatch(markup,/절대 표시되면/);assert.match(markup,/상담일지/);const unsafe=c.h.recallRowsHtml(c.h.recallGroupRows([{...data[0],name:'<img onerror=x>',memo:'<script>x</script>'}]),'2026-10-08');assert.doesNotMatch(unsafe,/<img|<script/);assert.match(unsafe,/&lt;script/);});
test('연락함은 묶음의 문의·상담 대상과 메모를 단일 RPC로 보내며 실패해도 메모를 자동 재시도하지 않는다',async()=>{const elements=[],msg={textContent:''},row={querySelector:s=>s==='.msg'?msg:s==='[data-recall-note]'?{value:'연락 메모'}:null},box={querySelector:()=>row};const calls=[],c=context({ME:{role:'manager',id:'m'},SETTINGS:{'recall.enabled':'true'},document:{querySelectorAll:()=>elements},$:s=>s==='#recallList'?box:null,sb:{rpc:async(name,args)=>{calls.push({name,args});return {error:{message:'일시 오류'}};}},setStatus:()=>{}});
 const runtime=html.slice(html.indexOf('let INBOX_SUBTAB='),html.indexOf('async function renderInbox(m){'));vm.runInContext(runtime+';RECALL_VISIBLE=recallGroupRows('+JSON.stringify(data)+');',c);await c.recallSave(0,'contact');assert.equal(calls.length,1);assert.equal(calls[0].name,'recall_update');assert.deepEqual(Array.from(calls[0].args.p_inbox_ids),['a']);assert.deepEqual(Array.from(calls[0].args.p_journal_ids),['j']);assert.equal(calls[0].args.p_note,'연락 메모');assert.match(msg.textContent,/새로 조회/);});
test('리콜 화면 글과 간격·알림 설정은 기존 허브 설정 편집기에 등록되어 있다',()=>{const textBlock=texts.match(/\/\* hub-texts:test-start \*\/([\s\S]*?)\/\* hub-texts:test-end \*\//)[1],c={HUB_RECALL_CATALOG:true};vm.createContext(c);vm.runInContext(textBlock+';this.defs=hubTextDefs();this.settings=HUB_SETTING_DEFS;',c);for(const key of ['recall.title','recall.summary','recall.save_error','recall.push_title','recall.push_body','recall.recall_1'])assert.ok(c.defs.some(d=>d.key===key),key);for(const key of ['interval_1','interval_2','interval_3','today_alert','push_enabled','enabled'])assert.ok(c.settings.some(d=>d.key==='recall.'+key),key);assert.match(html,/String\(SETTINGS\['recall.today_alert'\]/);});
test('375px에서는 두 열로 줄이 바뀌고 입력칸·긴 메모가 가로로 넘치지 않도록 배치한다',()=>{assert.match(html,/@media\(max-width:640px\)\{\.recall-row\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.match(html,/\.recall-cell\{min-width:0;overflow-wrap:anywhere\}/);assert.match(html,/\.recall-editor textarea,\.recall-editor input\{box-sizing:border-box;max-width:100%;width:100%\}/);});
test('허브 인라인 스크립트 전체가 구문 분석된다',()=>{for(const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))if(match[1].trim())new vm.Script(match[1]);});
test('리콜 푸시는 인원수만 담고 알림 설정·권한을 발송 직전에 재확인한다',async()=>{const {stripTypeScriptTypes}=require('node:module'),source=stripTypeScriptTypes(fs.readFileSync('supabase/functions/push-dispatcher/transport.ts','utf8')).replace(/export /g,''),c={URL};vm.createContext(c);vm.runInContext(source+';this.notify=safeNotification;',c);const payload=c.notify('recall_daily',{count:2,push_title:'오늘 연락',push_body:'{n}명 연락하기',message:'민감 원문',contact:'01012345678'});assert.equal(payload.body,'2명 연락하기');assert.equal(payload.url,'/hr.html?tab=inbox&recall=1');assert.equal(c.notify('recall_daily',{count:-1}),null);assert.match(fs.readFileSync('supabase/functions/push-dispatcher/dispatcher_core.ts','utf8'),/canDispatchRecallPush\?\.\(event\)/);});
test('상담일지로 이동할 때 비동기 화면 그리기가 끝난 뒤 편집 폼을 연다',async()=>{const calls=[],c=context({TAB:'inbox',renderNav:()=>calls.push('nav'),render:async()=>{await Promise.resolve();calls.push('rendered');},consultationEdit:async id=>calls.push(id)});vm.runInContext(html.match(/async function recallShowJournal\(id\)\{[^\n]+/)[0],c);await c.recallShowJournal('j1');assert.deepEqual(calls,['nav','rendered','j1']);assert.equal(c.TAB,'consult');});
test('실제 푸시 처리 함수는 리콜 설정이 꺼지거나 권한을 잃으면 보내지 않으며 허용되면 한 번 보낸다',async()=>{
 const {stripTypeScriptTypes}=require('node:module'),strip=file=>stripTypeScriptTypes(fs.readFileSync(file,'utf8')).replace(/^import [^\n]+\n/gm,'').replace(/export /g,'');
 const c={URL,Date};vm.createContext(c);vm.runInContext(strip('supabase/functions/push-dispatcher/transport.ts')+'\n'+strip('supabase/functions/push-dispatcher/dispatcher_core.ts')+';this.run=processClaimedEvent;',c);
 for(const allowed of [false,true]){const calls=[],db={renewClaim:async()=>{},getProfile:async()=>({data:{active:true,approved:true},error:null}),canDispatchRecallPush:async()=>({data:allowed,error:null}),getSubscriptions:async()=>({data:[{id:'s1',endpoint:'https://fcm.googleapis.com/synthetic',p256dh:'synthetic',auth:'synthetic'}],error:null}),disableUnsafeSubscription:async()=>{},seedDeliveries:async()=>null,getDeliveries:async()=>({data:[],error:null}),recordDelivery:async()=>{},releaseEvent:async(e,t,fields)=>calls.push(fields)};
 let sends=0;const result=await c.run({id:1,recipient_id:'manager',event_key:'recall-test',event_type:'recall_daily',attempts:1,payload:{count:2}},'claim',db,async()=>{sends++;});assert.equal(sends,allowed?1:0);assert.equal(result.status,allowed?'sent':'skipped');if(!allowed)assert.match(calls[0].last_error,/recall push/);}
});
