-- 통합 문의함 1차: 외부 원문 payload/비밀은 저장하지 않으며, 실제 채널 연동은 Edge Function service-role 경계로만 받는다.
create table if not exists public.consultation_inbox (
  id uuid primary key default gen_random_uuid(), source text not null check(source in('daangn','kakao','naver_email','homepage','phone','manual','other')),
  external_event_id text check(external_event_id is null or char_length(external_event_id) between 1 and 160), received_at timestamptz not null default now(),
  sender_name text check(sender_name is null or char_length(trim(sender_name))<=80), contact text check(contact is null or char_length(trim(contact))<=40), subject text check(subject is null or char_length(trim(subject))<=160), message text not null check(char_length(trim(message)) between 1 and 4000),
  status text not null default 'new' check(status in('new','in_progress','converted','closed')), assigned_to uuid references public.profiles(user_id), journal_id uuid references public.consultation_journals(id), dedupe_hash text not null check(char_length(dedupe_hash)=64), created_via text not null default 'manual' check(created_via in('manual','service_ingest')), created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(dedupe_hash), unique(source,external_event_id)
);
create index if not exists consultation_inbox_status_received_idx on public.consultation_inbox(status,received_at desc,id desc);
create index if not exists consultation_inbox_assigned_idx on public.consultation_inbox(assigned_to,status,received_at desc);
create or replace function public.set_consultation_inbox_updated_at() returns trigger language plpgsql set search_path=public,pg_temp as $$begin if new.id is distinct from old.id or new.source is distinct from old.source or new.external_event_id is distinct from old.external_event_id or new.received_at is distinct from old.received_at or new.sender_name is distinct from old.sender_name or new.contact is distinct from old.contact or new.subject is distinct from old.subject or new.message is distinct from old.message or new.created_via is distinct from old.created_via or new.created_by is distinct from old.created_by or new.created_at is distinct from old.created_at or new.dedupe_hash is distinct from old.dedupe_hash then raise exception 'consultation inbox immutable source or audit field cannot be changed';end if;new.updated_at:=now();return new;end$$;
drop trigger if exists consultation_inbox_set_updated_at on public.consultation_inbox;create trigger consultation_inbox_set_updated_at before update on public.consultation_inbox for each row execute function public.set_consultation_inbox_updated_at();
revoke all on function public.set_consultation_inbox_updated_at() from public, anon, authenticated;
alter table public.consultation_inbox enable row level security;
revoke all on table public.consultation_inbox from public,anon,authenticated;
grant select,insert,update on public.consultation_inbox to authenticated;
drop policy if exists consultation_inbox_select on public.consultation_inbox;create policy consultation_inbox_select on public.consultation_inbox for select to authenticated using(public.employee_hub_access_allowed() and (select public.my_role()) in('manager','owner'));
drop policy if exists consultation_inbox_insert on public.consultation_inbox;create policy consultation_inbox_insert on public.consultation_inbox for insert to authenticated with check(public.employee_hub_access_allowed() and (select public.my_role()) in('manager','owner') and created_via='manual' and created_by=(select auth.uid()));
drop policy if exists consultation_inbox_update on public.consultation_inbox;create policy consultation_inbox_update on public.consultation_inbox for update to authenticated using(public.employee_hub_access_allowed() and (select public.my_role()) in('manager','owner')) with check(public.employee_hub_access_allowed() and (select public.my_role()) in('manager','owner') and status in('new','in_progress','closed') and journal_id is null);
create or replace function public.consultation_inbox_ingest_service(p_source text,p_event_id text,p_received_at timestamptz,p_sender_name text,p_contact text,p_subject text,p_message text) returns public.consultation_inbox language plpgsql security definer set search_path='' as $$declare r public.consultation_inbox;v_hash text;begin if coalesce(current_setting('request.jwt.claim.role',true),'')<>'service_role' then raise exception 'service role required';end if;if p_source not in('daangn','kakao','naver_email','homepage','phone','other') or p_event_id is null or char_length(p_event_id) not between 1 and 160 or char_length(trim(coalesce(p_message,''))) not between 1 and 4000 then raise exception 'invalid inbox event';end if;v_hash=lpad(md5(p_source||':'||p_event_id),64,'0');insert into public.consultation_inbox(source,external_event_id,received_at,sender_name,contact,subject,message,status,dedupe_hash,created_via) values(p_source,p_event_id,coalesce(p_received_at,now()),nullif(btrim(p_sender_name),''),nullif(btrim(p_contact),''),nullif(btrim(p_subject),''),btrim(p_message),'new',v_hash,'service_ingest') on conflict(dedupe_hash) do update set updated_at=public.consultation_inbox.updated_at returning * into r;return r;end$$;
create or replace function public.consultation_inbox_convert_to_journal(p_inbox_id uuid) returns table(journal_id uuid) language plpgsql security definer set search_path='' as $$declare i public.consultation_inbox;v_journal uuid;v_source text;begin if auth.uid() is null or not public.employee_hub_access_allowed() or coalesce(public.my_role(),'') not in('manager','owner') then raise exception 'manager or owner access required';end if;select * into i from public.consultation_inbox where id=p_inbox_id for update;if not found then raise exception 'inbox not found';end if;if i.journal_id is not null or i.status='converted' then raise exception 'inbox already converted';end if;v_source=case when i.source='homepage' then '홈페이지' when i.source in('daangn','kakao','naver_email') then '카카오,네이버예약,당근' else '원본' end;insert into public.consultation_journals(patient_name,contact_phone,source_sheet,consulted_on,status,consultation_note,next_action,author_id) values(coalesce(i.sender_name,'미상'),i.contact,v_source,i.received_at::date,'대기',i.message,i.subject,auth.uid()) returning id into v_journal;update public.consultation_inbox set status='converted',journal_id=v_journal where id=i.id;return query select v_journal;end$$;
revoke all on function public.consultation_inbox_ingest_service(text,text,timestamptz,text,text,text,text),public.consultation_inbox_convert_to_journal(uuid) from public, anon, authenticated;
grant execute on function public.consultation_inbox_ingest_service(text,text,timestamptz,text,text,text,text) to service_role;
grant execute on function public.consultation_inbox_convert_to_journal(uuid) to authenticated;
