-- 운영 단계 A: 스키마·보존 이력·상태 RPC만 추가한다. 기존 RLS/UPDATE와 UI는 그대로 유지한다.
-- 선행조건: public.profiles, public.schedule_people. 후행검증: columns/history/RPC가 존재해야 한다.
begin;
alter table public.profiles add column if not exists employment_status text not null default '재직' check(employment_status in ('재직','자진퇴사','계약만료','권고사직')),add column if not exists employment_effective_date date,add column if not exists employment_reason text,add column if not exists account_access_status text not null default '활성' check(account_access_status in ('활성','차단')),add column if not exists account_disabled_at timestamptz,add column if not exists account_disabled_by uuid,add column if not exists account_disabled_reason text;
update public.profiles set employment_status=case when active then '재직' else '자진퇴사' end where employment_status is null or(employment_status='재직' and not active);
create table if not exists public.profile_employment_history(id bigint generated always as identity primary key,user_id uuid not null references public.profiles(user_id) on delete restrict,from_status text,to_status text not null check(to_status in ('재직','자진퇴사','계약만료','권고사직')),effective_date date not null,reason text,account_action text not null check(account_action in ('상태변경','계정차단')),acted_by uuid not null,acted_at timestamptz not null default now());
alter table public.profile_employment_history enable row level security;
drop policy if exists profile_employment_history_select_lead on public.profile_employment_history;
create policy profile_employment_history_select_lead on public.profile_employment_history for select to authenticated using(exists(select 1 from public.profiles p where p.user_id=auth.uid() and p.active and p.approved and p.role in('chief','owner')));
revoke all on public.profile_employment_history from anon; revoke insert,update,delete on public.profile_employment_history from authenticated; grant select on public.profile_employment_history to authenticated;
create or replace function public.assert_employment_owner(p_user_id uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare a uuid:=auth.uid();t public.profiles%rowtype;begin if not exists(select 1 from public.profiles p where p.user_id=a and p.active and p.approved and p.role='owner') then raise exception 'active approved owner required';end if;select * into t from public.profiles where user_id=p_user_id;if not found then raise exception 'profile not found';end if;if t.role='owner' and t.active and(select count(*) from public.profiles where role='owner' and active)<=1 then raise exception 'cannot change last active owner';end if;if a=p_user_id then raise exception 'cannot change your own employment status';end if;return a;end $$;
create or replace function public.set_employment_status(p_user_id uuid,p_employment_status text,p_effective_date date,p_reason text) returns void language plpgsql security definer set search_path='' as $$ declare a uuid;b text;s text;begin if p_employment_status not in('재직','자진퇴사','계약만료','권고사직') or p_effective_date is null then raise exception 'invalid employment status or effective date';end if;a:=public.assert_employment_owner(p_user_id);select employment_status,account_access_status into b,s from public.profiles where user_id=p_user_id for update;if p_employment_status='재직' and s='차단' then raise exception 'blocked account cannot return to employed status';end if;update public.profiles set employment_status=p_employment_status,employment_effective_date=p_effective_date,employment_reason=nullif(btrim(p_reason),''),active=(p_employment_status='재직'),approved=case when p_employment_status='재직' then approved else false end where user_id=p_user_id;if p_employment_status<>'재직' then update public.schedule_people set active=false,included_in_schedule=false where profile_user_id=p_user_id;end if;insert into public.profile_employment_history(user_id,from_status,to_status,effective_date,reason,account_action,acted_by) values(p_user_id,b,p_employment_status,p_effective_date,nullif(btrim(p_reason),''),'상태변경',a);end $$;
create or replace function public.disable_employee_account_preserve_records(p_user_id uuid,p_employment_status text,p_reason text,p_effective_date date) returns void language plpgsql security definer set search_path='' as $$ declare a uuid;b text;begin if p_employment_status not in('자진퇴사','계약만료','권고사직') or p_effective_date is null then raise exception 'account block requires a non-employed status';end if;a:=public.assert_employment_owner(p_user_id);select employment_status into b from public.profiles where user_id=p_user_id for update;update public.profiles set employment_status=p_employment_status,employment_effective_date=p_effective_date,employment_reason=nullif(btrim(p_reason),''),account_access_status='차단',account_disabled_at=now(),account_disabled_by=a,account_disabled_reason=nullif(btrim(p_reason),''),active=false,approved=false where user_id=p_user_id;update public.schedule_people set active=false,included_in_schedule=false where profile_user_id=p_user_id;insert into public.profile_employment_history(user_id,from_status,to_status,effective_date,reason,account_action,acted_by) values(p_user_id,b,p_employment_status,p_effective_date,nullif(btrim(p_reason),''),'계정차단',a);end $$;
revoke all on function public.assert_employment_owner(uuid) from public,anon;revoke all on function public.set_employment_status(uuid,text,date,text) from public,anon;revoke all on function public.disable_employee_account_preserve_records(uuid,text,text,date) from public,anon;grant execute on function public.set_employment_status(uuid,text,date,text),public.disable_employee_account_preserve_records(uuid,text,text,date) to authenticated;
commit;
