-- B rollback: 보존 데이터가 있으면 gate를 제거하지 않는다. A는 그대로 유지한다.
begin;
do $$ begin if exists(select 1 from public.profile_employment_history) or exists(select 1 from public.profiles where employment_status<>'재직' or account_access_status<>'활성' or account_disabled_at is not null) then raise exception 'employment phase B rollback blocked: preserved data exists';end if;end $$;
create or replace function public._remove_employee_hub_access_gate(p_table regclass) returns void language plpgsql set search_path='' as $$begin if p_table is not null then if p_table::text='storage.objects' then execute format('drop policy if exists employee_hub_storage_access_gate on %s',p_table);else execute format('drop policy if exists employee_hub_access_gate on %s',p_table);end if;end if;end$$;
select public._remove_employee_hub_access_gate(to_regclass('storage.objects'));select public._remove_employee_hub_access_gate(to_regclass('public.'||x)) from unnest(array['profiles','attendance','att_months','attendance_issues','schedule_weeks','schedules','schedule_people','leave_requests','leave_ledger','holidays','calendar_events','notices','notice_reads','contract_templates','contracts','approval_docs','approval_steps','payroll_rows','payslips','monthly_reviews','bonus_rules','applicants','ledger_files','onboarding_items','onboarding_checks','confidential_access','confidential_records','profile_employment_history','employee_contract_terms','employee_documents','employee_signature_vault','employee_signature_uses','employee_signature_audit','leave_application_documents','leave_application_document_events','push_subscriptions']::text[]) x;drop function public._remove_employee_hub_access_gate(regclass);
do $$ begin if to_regnamespace('employee_hub_private') is not null then execute $sql$
create or replace function employee_hub_private.push_subscription_access_allowed(p_user uuid) returns boolean language sql stable security definer set search_path='' as $fn$select p_user=auth.uid() and exists(select 1 from public.profiles p where p.user_id=p_user and p.active and p.approved)$fn$;
$sql$;revoke all on function employee_hub_private.push_subscription_access_allowed(uuid) from public,anon,authenticated,service_role;grant execute on function employee_hub_private.push_subscription_access_allowed(uuid) to authenticated;end if;end$$;
-- A의 원래 helper 정의를 복원해 A 단독 상태와 정확히 맞춘다.
create or replace function public.assert_employment_owner(p_user_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare a uuid:=auth.uid();t public.profiles%rowtype;begin if not exists(select 1 from public.profiles p where p.user_id=a and p.active and p.approved and p.role='owner') then raise exception 'active approved owner required';end if;select * into t from public.profiles where user_id=p_user_id;if not found then raise exception 'profile not found';end if;if t.role='owner' and t.active and(select count(*) from public.profiles where role='owner' and active)<=1 then raise exception 'cannot change last active owner';end if;if a=p_user_id then raise exception 'cannot change your own employment status';end if;return a;end$$;
revoke all on function public.assert_employment_owner(uuid) from public,anon,authenticated;
drop function if exists public.employee_hub_access_allowed();create or replace function public.my_role() returns text language sql stable security definer set search_path=public,pg_temp as $$select coalesce((select p.role from public.profiles p where p.user_id=auth.uid()),'staff')$$;revoke all on function public.my_role() from public,anon;grant execute on function public.my_role() to authenticated;commit;
