-- 운영 단계 C: 새 hr.html과 동시에 배포한다. profiles 직접 UPDATE/DELETE를 닫고 RPC만 허용한다.
-- 선행조건: phase A+B. 후행검증: authenticated profiles UPDATE/DELETE grant 없음, RPC만 실행 가능.
begin;
do $$ begin if to_regprocedure('public.employee_hub_access_allowed()') is null then raise exception 'employment phase B is required';end if;end $$;
drop policy if exists profiles_update_owner on public.profiles;drop policy if exists profiles_delete_owner on public.profiles;revoke update,delete on public.profiles from authenticated;revoke delete on public.profiles from anon;
create or replace function public.assert_employee_approver(p_user_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare a uuid:=auth.uid();begin if not public.employee_hub_access_allowed() then raise exception 'employee hub access required';end if;if not exists(select 1 from public.profiles p where p.user_id=a and p.active and p.approved and p.role in('chief','owner')) then raise exception 'active approved chief or owner required';end if;if a=p_user_id then raise exception 'cannot approve your own profile';end if;if not exists(select 1 from public.profiles where user_id=p_user_id) then raise exception 'profile not found';end if;return a;end$$;
create or replace function public.approve_employee_profile(p_user_id uuid) returns void language plpgsql security definer set search_path='' as $$declare s text;e text;begin perform public.assert_employee_approver(p_user_id);select account_access_status,employment_status into s,e from public.profiles where user_id=p_user_id for update;if s='차단' then raise exception 'blocked account cannot be approved';end if;if e<>'재직' then raise exception 'non-employed profile cannot be approved';end if;update public.profiles set approved=true where user_id=p_user_id;end$$;
create or replace function public.revoke_employee_profile_approval(p_user_id uuid) returns void language plpgsql security definer set search_path='' as $$declare t public.profiles%rowtype;begin perform public.assert_employee_approver(p_user_id);select * into t from public.profiles where user_id=p_user_id for update;if t.role='owner' and t.active and t.approved and(select count(*) from public.profiles where role='owner' and active and approved)<=1 then raise exception 'cannot revoke last active owner approval';end if;update public.profiles set approved=false where user_id=p_user_id;end$$;
create or replace function public.update_employee_profile_field(p_user_id uuid,p_field text,p_value text) returns void language plpgsql security definer set search_path='' as $$declare a uuid:=auth.uid();t public.profiles%rowtype;begin if not public.employee_hub_access_allowed() or not exists(select 1 from public.profiles p where p.user_id=a and p.role='owner') then raise exception 'active approved owner required';end if;if p_field not in('role','dept','fp_id') then raise exception 'profile field is not allowed';end if;select * into t from public.profiles where user_id=p_user_id for update;if not found then raise exception 'profile not found';end if;if p_field='role' then if p_value not in('owner','chief','manager','staff') then raise exception 'invalid profile role';end if;if a=p_user_id then raise exception 'cannot change your own role';end if;if t.role='owner' and t.active and t.role is distinct from p_value and(select count(*) from public.profiles where role='owner' and active and approved)<=1 then raise exception 'cannot change last active owner';end if;update public.profiles set role=p_value where user_id=p_user_id;elsif p_field='dept' then update public.profiles set dept=nullif(btrim(p_value),'') where user_id=p_user_id;else update public.profiles set fp_id=nullif(btrim(p_value),'') where user_id=p_user_id;end if;end$$;
revoke all on function public.assert_employee_approver(uuid),public.approve_employee_profile(uuid),public.revoke_employee_profile_approval(uuid),public.update_employee_profile_field(uuid,text,text) from public;grant execute on function public.approve_employee_profile(uuid),public.revoke_employee_profile_approval(uuid),public.update_employee_profile_field(uuid,text,text) to authenticated;commit;
