-- 운영 단계 B: 차단-aware 조회 gate만 추가한다. 기존 profiles UPDATE와 현재 UI는 유지한다.
-- 선행조건: phase A columns/history. 후행검증: blocked JWT는 gate 대상 RLS에서 0행이다.
begin;
do $$ begin if to_regclass('public.profile_employment_history') is null or not exists(select 1 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name='account_access_status') then raise exception 'employment phase A is required';end if;end $$;
create or replace function public.employee_hub_access_allowed() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles p where p.user_id=auth.uid() and p.active and p.approved and p.account_access_status='활성')$$;
create or replace function public.my_role() returns text language sql stable security definer set search_path='' as $$select case when public.employee_hub_access_allowed() then coalesce((select p.role from public.profiles p where p.user_id=auth.uid()),'staff') else 'pending' end$$;
revoke all on function public.employee_hub_access_allowed() from public,anon;revoke all on function public.my_role() from public,anon;grant execute on function public.employee_hub_access_allowed(),public.my_role() to authenticated;
-- A의 상태 RPC가 쓰는 actor helper도 B부터는 차단-aware여야 한다.
create or replace function public.assert_employment_owner(p_user_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare a uuid:=auth.uid();t public.profiles%rowtype;begin if not public.employee_hub_access_allowed() then raise exception 'employee hub access required';end if;if not exists(select 1 from public.profiles p where p.user_id=a and p.active and p.approved and p.role='owner') then raise exception 'active approved owner required';end if;select * into t from public.profiles where user_id=p_user_id;if not found then raise exception 'profile not found';end if;if t.role='owner' and t.active and(select count(*) from public.profiles where role='owner' and active)<=1 then raise exception 'cannot change last active owner';end if;if a=p_user_id then raise exception 'cannot change your own employment status';end if;return a;end$$;
revoke all on function public.assert_employment_owner(uuid) from public,anon,authenticated;
create or replace function public._install_employee_hub_access_gate(p_table regclass) returns void language plpgsql set search_path='' as $$begin if p_table is not null then execute format('alter table %s enable row level security',p_table);execute format('drop policy if exists employee_hub_access_gate on %s',p_table);execute format('create policy employee_hub_access_gate on %s as restrictive for all to authenticated using(public.employee_hub_access_allowed()) with check(public.employee_hub_access_allowed())',p_table);end if;end$$;
-- 명시 36개: hr_schema + 직원후속 + 기밀 + push. 존재하지 않는 선택 기능은 멱등적으로 건너뛴다.
select public._install_employee_hub_access_gate(to_regclass('public.'||x)) from unnest(array['profiles','attendance','att_months','attendance_issues','schedule_weeks','schedules','schedule_people','leave_requests','leave_ledger','holidays','calendar_events','notices','notice_reads','contract_templates','contracts','approval_docs','approval_steps','payroll_rows','payslips','monthly_reviews','bonus_rules','applicants','ledger_files','onboarding_items','onboarding_checks','confidential_access','confidential_records','profile_employment_history','employee_contract_terms','employee_documents','employee_signature_vault','employee_signature_uses','employee_signature_audit','leave_application_documents','leave_application_document_events','push_subscriptions']::text[]) x;
drop function public._install_employee_hub_access_gate(regclass);
drop policy if exists employee_hub_storage_access_gate on storage.objects;create policy employee_hub_storage_access_gate on storage.objects as restrictive for all to authenticated using(bucket_id not in('hr-docs','employee-signatures','leave-docs','notice-attachments') or public.employee_hub_access_allowed()) with check(bucket_id not in('hr-docs','employee-signatures','leave-docs','notice-attachments') or public.employee_hub_access_allowed());
do $$ begin if to_regnamespace('employee_hub_private') is not null then execute $sql$
create or replace function employee_hub_private.push_subscription_access_allowed(p_user uuid) returns boolean language sql stable security definer set search_path='' as $fn$select p_user=auth.uid() and public.employee_hub_access_allowed()$fn$;
$sql$;revoke all on function employee_hub_private.push_subscription_access_allowed(uuid) from public;grant execute on function employee_hub_private.push_subscription_access_allowed(uuid) to authenticated;end if;end$$;
commit;
