-- Task 7: private schema is created, never adopted; every collision stops before change.
begin;
do $$ begin
 if to_regnamespace('employee_hub_private') is not null or to_regclass('public.push_subscriptions') is not null or exists(select 1 from pg_proc where pronamespace=to_regnamespace('employee_hub_private') and proname in ('push_subscription_active_approved','guard_push_subscription_timestamps','push_subscription_schema_snapshot')) then raise exception 'push subscription migration object collision; preserve state and stop'; end if;
end $$;
create schema employee_hub_private;
revoke all on schema employee_hub_private from public,anon,authenticated,service_role;
create table employee_hub_private.push_subscriptions_migration_marker (fingerprint text primary key check(fingerprint='task7-push-v3-5d9a'),manifest text not null check(manifest='push-v3-private-5d9a'),snapshot jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
revoke all on employee_hub_private.push_subscriptions_migration_marker from public,anon,authenticated,service_role;
insert into employee_hub_private.push_subscriptions_migration_marker(fingerprint,manifest) values('task7-push-v3-5d9a','push-v3-private-5d9a');
create function employee_hub_private.push_subscription_active_approved() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles p where p.user_id=auth.uid() and p.active and p.approved) $$;
revoke all on function employee_hub_private.push_subscription_active_approved() from public,anon,authenticated,service_role;
grant usage on schema employee_hub_private to authenticated;
grant execute on function employee_hub_private.push_subscription_active_approved() to authenticated;
create table public.push_subscriptions (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(user_id) on delete cascade,endpoint text not null unique,subscription jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(endpoint ~ '^https://([[:alnum:]]([[:alnum:]-]{0,61}[[:alnum:]])?)(\.([[:alnum:]]([[:alnum:]-]{0,61}[[:alnum:]])?))*(:(6553[0-5]|655[0-2][0-9]|65[0-4][0-9]{2}|6[0-4][0-9]{3}|[1-5][0-9]{4}|[1-9][0-9]{0,3}))?(/[^[:space:]]*)?$'),check(jsonb_typeof(subscription)='object' and subscription->>'endpoint'=endpoint and jsonb_typeof(subscription->'keys')='object' and length(coalesce(subscription->'keys'->>'p256dh',''))>0 and length(coalesce(subscription->'keys'->>'auth',''))>0));
alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from public,anon,authenticated,service_role;
grant select,insert,update,delete on public.push_subscriptions to authenticated;
create policy push_subscriptions_select_own on public.push_subscriptions for select to authenticated using (user_id=auth.uid() and (select employee_hub_private.push_subscription_active_approved()));
create policy push_subscriptions_insert_own on public.push_subscriptions for insert to authenticated with check (user_id=auth.uid() and (select employee_hub_private.push_subscription_active_approved()));
create policy push_subscriptions_update_own on public.push_subscriptions for update to authenticated using (user_id=auth.uid() and (select employee_hub_private.push_subscription_active_approved())) with check (user_id=auth.uid() and (select employee_hub_private.push_subscription_active_approved()));
create policy push_subscriptions_delete_own on public.push_subscriptions for delete to authenticated using (user_id=auth.uid() and (select employee_hub_private.push_subscription_active_approved()));
create function employee_hub_private.guard_push_subscription_timestamps() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op='INSERT' then new.created_at:=now();new.updated_at:=now();elsif new.created_at is distinct from old.created_at then raise exception 'created_at is immutable';else new.updated_at:=now();end if;return new;end $$;
revoke all on function employee_hub_private.guard_push_subscription_timestamps() from public,anon,authenticated,service_role;
create trigger guard_push_subscription_timestamps before insert or update on public.push_subscriptions for each row execute function employee_hub_private.guard_push_subscription_timestamps();
create function employee_hub_private.push_subscription_schema_snapshot() returns jsonb language sql stable security definer set search_path='' as $$ select jsonb_build_object('manifest','push-v3-private-5d9a','schema',(select jsonb_build_object('oid',n.oid,'owner',n.nspowner,'acl',coalesce(to_jsonb(n.nspacl),'null'::jsonb),'objects',(select jsonb_agg(c.oid order by c.oid) from pg_class c where c.relnamespace=n.oid)) from pg_namespace n where n.nspname='employee_hub_private'),'table',(select jsonb_build_object('oid',c.oid,'owner',c.relowner,'acl',coalesce(to_jsonb(c.relacl),'null'::jsonb),'rls',c.relrowsecurity,'forcerls',c.relforcerowsecurity,'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped)) from pg_class c where c.oid='public.push_subscriptions'::regclass),'functions',(select jsonb_agg(jsonb_build_object('oid',p.oid,'name',p.proname,'owner',p.proowner,'config',coalesce(to_jsonb(p.proconfig),'null'::jsonb),'acl',coalesce(to_jsonb(p.proacl),'null'::jsonb),'definition',pg_get_functiondef(p.oid)) order by p.proname) from pg_proc p where p.pronamespace=to_regnamespace('employee_hub_private')),'policies',(select jsonb_agg(jsonb_build_object('name',p.policyname,'cmd',p.cmd,'roles',to_jsonb(p.roles),'qual',p.qual,'with_check',p.with_check,'permissive',p.permissive) order by p.policyname) from pg_policies p where p.schemaname='public' and p.tablename='push_subscriptions'),'triggers',(select jsonb_agg(jsonb_build_object('oid',t.oid,'name',t.tgname,'definition',pg_get_triggerdef(t.oid)) order by t.tgname) from pg_trigger t where t.tgrelid='public.push_subscriptions'::regclass and not t.tgisinternal),'constraints',(select jsonb_agg(jsonb_build_object('oid',x.oid,'name',x.conname,'definition',pg_get_constraintdef(x.oid,true)) order by x.conname) from pg_constraint x where x.conrelid='public.push_subscriptions'::regclass),'indexes',(select jsonb_agg(jsonb_build_object('oid',x.indexrelid,'definition',pg_get_indexdef(x.indexrelid)) order by x.indexrelid) from pg_index x where x.indrelid='public.push_subscriptions'::regclass),'marker',(select jsonb_build_object('oid',c.oid,'owner',c.relowner,'acl',coalesce(to_jsonb(c.relacl),'null'::jsonb),'rls',c.relrowsecurity,'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull) order by a.attnum) from pg_attribute a where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped)) from pg_class c where c.oid='employee_hub_private.push_subscriptions_migration_marker'::regclass)) $$;
revoke all on function employee_hub_private.push_subscription_schema_snapshot() from public,anon,authenticated,service_role;
update employee_hub_private.push_subscriptions_migration_marker set snapshot=employee_hub_private.push_subscription_schema_snapshot() where fingerprint='task7-push-v3-5d9a' and manifest='push-v3-private-5d9a';
commit;
